### ISSUE TITLE
Looks lik 1.3 is broken, or could just be me?

### ISSUE THREAD

**Issue by DumbJoe** [JonasNilson/idle_master_extended#10]
Doesn't show the mobile authentication window anymore, skips it entirely and tries to save and of course won't login since it's guarded with a code...which is never presented....

**Comment by Frederisk** [comment]
I don't know what happened to you. But it works fine on my device. Maybe you can try to replace another computer to run.

**Comment by JonasNilson** [comment]
I have no way of verifying the behavior at the moment. You could try the tips available at the forum: https://steamcommunity.com/groups/idlemastery/discussions/0/133257636766989675/?ctp=6

**Comment by DumbJoe** [comment]
> I have no way of verifying the behavior at the moment. You could try the tips available at the forum: https://steamcommunity.com/groups/idlemastery/discussions/0/133257636766989675/?ctp=6

Thanks, tried all those except #5 since I don't have Internet Explorer, but Microsoft Edge as that's replaced it, I believe.

Maybe I can pass a log of some sort that might tell you why it won't go for me?

**Comment by JonasNilson** [comment]
I have no issue using the login window in 1.3. Hopefully it solved itself.

I doubt Idle Master has a logging feature, but if you are able to debug that could definitely help finding the cause of the issue.
