### ISSUE TITLE
-1 Card drops remaining on all game

### ISSUE THREAD

**Issue by lucasredway** [JonasNilson/idle_master_extended#100]
im not receive cards. help me please

**Comment by JonasNilson** [comment]
@lucasredway Can you provide some examples of the games that doesn't work?

Also, a screenshot of your Idle Master Extended window would help me understand

**Comment by lucasredway** [comment]
> @lucasredway Can you provide some examples of the games that doesn't work?
> 
> Also, a screenshot of your Idle Master Extended window would help me understand

**Comment by lucasredway** [comment]
Here is my games
![Uploading screencapture-steamcommunity-id-csgogamblingcloud-badges-2020-08-06-14_23_52.png…]()

**Comment by lucasredway** [comment]
https://imgur.com/a/IDtPII5

**Comment by lucasredway** [comment]
![image](https://user-images.githubusercontent.com/56044384/89531956-51f01480-d7f1-11ea-98d6-7b596cc240fc.png)

**Comment by JonasNilson** [comment]
@lucasredway Based on your screenshot of your badge page you don't have any card drops remaining (you have already received all the cards you are eligible for)

Idling Dead Bits will not give you more cards since you have no more cards to get for free: https://steamcommunity.com/tradingcards/faq
