### ISSUE TITLE
"steam is not running"

### ISSUE THREAD

**Issue by carlosscrcs** [JonasNilson/idle_master_extended#101]
i've opened my steam and the idle master, but this keep saying "steam is not running"

**Comment by JonasNilson** [comment]
You can ignore Steam status in case it gives you issues: https://github.com/JonasNilson/idle_master_extended/issues/45#issuecomment-611694923

**Comment by carlosscrcs** [comment]
thank you!

**Comment by carlosscrcs** [comment]
but , i have another problem, this is saying "idling complete" every time

**Comment by JonasNilson** [comment]
@carlosscrcs

What games on Steam do you have with card drops remaining? You can check under your badge page.
