### ISSUE TITLE
Rework "Shutdown Windows when done"

### ISSUE THREAD

**Issue by Your-teammate** [JonasNilson/idle_master_extended#102]
The problem is that even if there are no games to idle, the Idle Master sends a shutdown request to Windows, giving only a somewhat brief opportunity to untick the setting, what is pretty annoying. I would suggest being able to tick this setting only for one boot (and permanently as well), or, for example, just don't make the program shut down your PC if there were no games to idle from the start.

**Comment by JonasNilson** [comment]
@Your-teammate Definitely sounds reasonable. I will make sure to address it in the upcoming release
