### ISSUE TITLE
The application not farm , the cards... help me

### ISSUE THREAD

**Issue by RazvuK** [JonasNilson/idle_master_extended#103]
The idle master doesn't want to make me those cards and I will put here what appears to me in error.log   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/76561198334332289
System.Exception: Response is null or empty. Added (+1) to RetryCount
   at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   at IdleMaster.frmMain.<GetBadgePageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()

**Comment by JonasNilson** [comment]
@RazvuK Can you provide a screenshot of Idle Master Extended?

Also, what games do you have to idle?

**Comment by RazvuK** [comment]
![Capture](https://user-images.githubusercontent.com/39533194/90248891-2ea51500-de42-11ea-9960-9f4e85561142.PNG)

**Comment by JonasNilson** [comment]
@RazvuK And how many cards are you eligible to get from that game? You can see that on your badge page: https://steamcommunity.com/my/badges

**Comment by RazvuK** [comment]
![Capture2](https://user-images.githubusercontent.com/39533194/90249521-4df07200-de43-11ea-8195-18dfcc2fc5b4.PNG) 
he has, but he doesn't give me the cards, I tried with several accounts.

**Comment by JonasNilson** [comment]
@RazvuK

According to the screenshot there are "No card drops remaining", so idling the game will not give you any cards

**Comment by RazvuK** [comment]
bro but i try with another account , with a free games. and not working.

**Comment by RazvuK** [comment]
bro i make a new account . and i see this 
![image](https://user-images.githubusercontent.com/39533194/90251408-5ac29500-de46-11ea-8b39-0b1455f182cc.png)

**Comment by RazvuK** [comment]
and no cards =( 
![image](https://user-images.githubusercontent.com/39533194/90251493-7e85db00-de46-11ea-944e-2d44b57595cd.png)

**Comment by JonasNilson** [comment]
@RazvuK Free games don't give you card drops unless you spend money in them.

https://steamcommunity.com/tradingcards/faq/
