### ISSUE TITLE
There is no game appearing 

### ISSUE THREAD

**Issue by BrenoXDMoon** [JonasNilson/idle_master_extended#104]
![image](https://user-images.githubusercontent.com/38464369/90313598-2ef5ec80-dee4-11ea-8cba-2a1d6afb1367.png)

Any game appear at the screen. I tried adding games in the whitelist too, but didn't worked

**Comment by JonasNilson** [comment]
@BrenoXDMoon What games do you own with card drops remaining?

Note that you are eligible for roughly half of the badge cards.

**Comment by mando7holo** [comment]
here are the screenshots

Am Do., 27. Aug. 2020 um 14:41 Uhr schrieb Jonas Nilson <
notifications@github.com>:

**Comment by JonasNilson** [comment]
@mando7holo There's no screenshot attached

**Comment by mando7holo** [comment]
![Screenshot (34)](https://user-images.githubusercontent.com/52405915/91599616-d81df780-e966-11ea-96d2-f7ba73ea741e.png)
![Screenshot (35)](https://user-images.githubusercontent.com/52405915/91599621-d9e7bb00-e966-11ea-979c-8e1144115c98.png)

soo sry

**Comment by JonasNilson** [comment]
@mando7holo as you can see it says "no card drops remaining" so you don't have any cards to get from idling.

You can use the whitelist mode if you want to gain hours in some specific games
