### ISSUE TITLE
It dont idle any game 

### ISSUE THREAD

**Issue by mando7holo** [JonasNilson/idle_master_extended#105]
21.08.2020 19:43:04   frmMain -> SortBadges -> The method (mostvalue) resulted in an exception
System.Net.WebException: Der Remotename konnte nicht aufgelöst werden: 'api.enhancedsteam.com'
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadString(Uri address)
   bei System.Net.WebClient.DownloadString(String address)
   bei IdleMaster.frmMain.SortBadges(String method)

**Comment by JonasNilson** [comment]
@mando7holo Change to default sorting mode to avoid this error message.
