### ISSUE TITLE
I don't see any game to idle and i have this error

### ISSUE THREAD

**Issue by QuerakTV** [JonasNilson/idle_master_extended#109]
8/29/2020 5:40:53 AM   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/76561199060945868
System.Exception: Response is null or empty. Added (+1) to RetryCount
   at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   at IdleMaster.frmMain.<GetBadgePageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()

**Comment by JonasNilson** [comment]
@QuerakTV What kind of issue are you experiencing? This error message is due to not being able to load your badge page

**Comment by QuerakTV** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/43861529/91637295-0b0fcc00-e9f7-11ea-9319-36da22d0b487.png)

**Comment by QuerakTV** [comment]
i don't see any game to idle

**Comment by JonasNilson** [comment]
@QuerakTV What games do you own that have card drops remaining? 

https://steamcommunity.com/my/badges

**Comment by QuerakTV** [comment]
Only csgo

**Comment by QuerakTV** [comment]
and i want boost my hours

**Comment by JonasNilson** [comment]
@QuerakTV then you could use whitelist mode:https://github.com/JonasNilson/idle_master_extended/wiki/Whitelist-mode

**Comment by QuerakTV** [comment]
ohhh thanks for help
