### ISSUE TITLE
Idling Complete

### ISSUE THREAD

**Issue by 1Legend1** [JonasNilson/idle_master_extended#11]
As soon as i open the program it says "Idling Complete"

**Comment by JimmyBassy** [comment]
It may be because you already have all the cards for all the games on your library

**Comment by JonasNilson** [comment]
> 
> 
> As soon as i open the program it says "Idling Complete"

Could you provide more information on the issue? How many games do you have that are eligible for card drops?

**Comment by mls41** [comment]
I have the same problem, idle master never works for me. When I run it, I see only ‘idle complete’ and nothing more. I have so many cards to drop.
