### ISSUE TITLE
Not openning other games

### ISSUE THREAD

**Issue by Lrozcz** [JonasNilson/idle_master_extended#110]
I have too much games and for first time it searched at all games. for a while. now i selled these cards but progress wasnt done and if i run idle master it starts games that i havent cards before (do i need to wait until done? to search for the cards AGAIN) 

because i didnt completed any set and realy want to complete it :/

**Comment by JonasNilson** [comment]
@Lrozcz If I understand your situation correctly you will not receive more cards for the games you sold the cards from. 

In short you only receive half the badge for each game for free, and then you are expected to trade or buy the rest: https://steamcommunity.com/tradingcards/

If you look under your badge page you can see which games you can receive more cards from: http://steamcommunity.com/my/badges/

"No card drops remaining" means you will not receive any more free cards for that game. But you can trade or buy the cards or booster packs from other users

**Comment by Lrozcz** [comment]
And what if i selled the free cards? Can i get them again?

Od: Jonas Nilson
Odesláno:neděle 30. srpna 2020 10:15
Komu: JonasNilson/idle_master_extended
Kopie: Lrozcz; Mention
Předmět: Re: [JonasNilson/idle_master_extended] Not openning other games(#110)

@Lrozcz If I understand your situation correctly you will not receive more cards for the games you sold the cards from.
In short you only receive half the badge for each game for free, and then you are expected to trade or buy the rest: https://steamcommunity.com/tradingcards/
If you look under your badge page you can see which games you can receive more cards from: http://steamcommunity.com/my/badges/
"No card drops remaining" means you will not receive any more free cards for that game. But you can trade or buy the cards or booster packs from other users

**Comment by JonasNilson** [comment]
> And what if i selled the free cards? Can i get them again? 

In short, no. If you've received cards from Steam for free and sold them you have to either trade them back, buy them or buy booster packs.
