### ISSUE TITLE
Need EA Acces Update

### ISSUE THREAD

**Issue by ensaryusuf** [JonasNilson/idle_master_extended#113]

**Comment by JonasNilson** [comment]
Can you provide more information on what this does? I am not particularly familiar with EA Access and how it relates to Steam.

**Comment by Luckz** [comment]
EA Play (not Access) https://store.steampowered.com/subscriptions/ea is a subscription service that gives you app ID ownership as long as you keep paying for them. 
I'm not sure if they still drop cards, but at launch they did. https://steamdb.info/sub/474127/info/ has no information about this being blocked; it could of course be blocked by now. https://steamcommunity.com/app/1289670/discussions/0/2948124408711149240/ seems inconclusive.

**If** they're truly (entirely!) blocked from dropping cards, then you would want to filter out those app IDs. In `[dynamicstore/userdata](https://store.steampowered.com/dynamicstore/userdata/)`, they're listed in rgMasterSubApps (and in rgOwnedApps).
