### ISSUE TITLE
Dont work on Linux

### ISSUE THREAD

**Issue by MonsterVerde** [JonasNilson/idle_master_extended#114]
Trying to run through Wine, it runs but stuck in steam login screen, when i write my username & password, i accept it, and the cases go reset and nothing happens :/ 
maybe we need a linux version?

**Comment by JonasNilson** [comment]
@MonsterVerde what version are you using?

Also you can give the Python version a try: https://github.com/jshackles/idle_master_py

**Comment by arvislacis** [comment]
Just an update if someone is still interested - I managed to successfully run IME from Steam with Proton 7.0-5 compatibility layer in Manjaro Linux.

![2023-01-18_18-41](https://user-images.githubusercontent.com/626982/213241503-dcf34bfd-bf5b-4225-bbc4-f11d28aa0212.png)

**Comment by marekkloc1** [comment]
> Just an update if someone is still interested - I managed to successfully run IME from Steam with Proton 7.0-5 compatibility layer in Manjaro Linux.
> 
> ![2023-01-18_18-41](https://user-images.githubusercontent.com/626982/213241503-dcf34bfd-bf5b-4225-bbc4-f11d28aa0212.png)

Very nice good job, but can you try or figure out, how to run only single game or multiple? Just for steam hour boost.

**Comment by arvislacis** [comment]
The same IME Settings are available as for Windows version so it's possible to do the fast idling (multiple games at once) and also single game idling - worked without problems for me, sometimes you need to go into Settings manually and then Apply changes for idling mode to change.
