### ISSUE TITLE
Weird Bug; Can't Use Anything

### ISSUE THREAD

**Issue by Felflamee** [JonasNilson/idle_master_extended#116]
Hi, so I made an account just to report this; usually it works perfectly fine and I use it everyday but suddenly it stopped working.
The whole program is messed up, the characters and letters are out of place and I cannot use anything.

Here's what it looks like and the error logs:

![bruh](https://user-images.githubusercontent.com/71282082/93115556-a18fee80-f681-11ea-9ee5-526b2f6a9bdc.PNG)

[error.log](https://github.com/JonasNilson/idle_master_extended/files/5219894/error.log)

**Comment by 9ofe** [comment]
redownload it
and sign in again

**Comment by Felflamee** [comment]
> redownload it
> and sign in again

I already did, I deleted it and redownloaded it and it did not fix the problem

**Comment by JonasNilson** [comment]
> [error.log](https://github.com/JonasNilson/idle_master_extended/files/5219894/error.log)

```
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize ---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 14, position 1. (C:\Users\brand\AppData\Local\IdleMaster\IdleMaster.exe_Url_rrx5ixwfkmrm3cmdvigsojscg1qjfyw1\1.5.0.0\user.config line 14) ---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 14, position 1.
```

Based on the log information I think you can delete your IdleMaster-AppData-directory (`C:\Users\brand\AppData\Local\IdleMaster\`) and restart the application which should generate a fresh AppData-directory with the respective files.
