### ISSUE TITLE
EA Play trading cards not working 

### ISSUE THREAD

**Issue by Evocta** [JonasNilson/idle_master_extended#117]
Hey. I created an account to ask you this question. I think there is no easy fix for this but I just want to make sure.
Basically, with the new EA Play subscription system, you can get a ton of games which they state drop trading cards, however they somehow seem to have found a solution to idling. 
I hope you manage to find a way around that, thank you for your work for the community.

**Comment by JonasNilson** [comment]
Looks like EA Play makes the games count as "free-to-play" and therefore you don't get card drops from them:

- https://steamcommunity.com/app/1289670/discussions/0/2953755260412098275/
- https://steamcommunity.com/app/1289670/discussions/0/2948124408711149240/

**Comment by Evocta** [comment]
Thank you for looking into it and thank you again for your work for the community.
