### ISSUE TITLE
Not working something bad.

### ISSUE THREAD

**Issue by Prot0o1** [JonasNilson/idle_master_extended#12]
![image](https://user-images.githubusercontent.com/39096158/62859809-8f18e800-bcfe-11e9-86ac-9961f13450b1.png)
Hello, program not woring for me. Stuck at this screen :S

**Comment by SuperSandro2000** [comment]
You have nothing to idle.

**Comment by JonasNilson** [comment]
Is this still an issue? If you don't have games that are eligible for card drops they won't appear in Idle Master.
