### ISSUE TITLE
Quick login automatically re-ticks itself

### ISSUE THREAD

**Issue by BackSurpriser** [JonasNilson/idle_master_extended#120]
When I click on log in, the pop-up says that javascript should be enabled, i tried to fix it by unticking quick login but quick login re-ticks itself.

**Comment by cztrollolcz** [comment]
Open IdleMaster.exe -> File -> Settings - untick Quick Login and relaunch. Worked for me

**Comment by BackSurpriser** [comment]
nope, still doesn't work

**Comment by JonasNilson** [comment]
You can try the latest version and see how it works for you. The quick login setting has been removed, and now there's a button to attempt to log in using your steam client
