### ISSUE TITLE
Steamguard code not being asked in v1.5

### ISSUE THREAD

**Issue by DumbJoe** [JonasNilson/idle_master_extended#122]
Can't idle for cards if the program can't login, and it can't login because it doesnt ask for a steamguard code...

_Originally posted by @DumbJoe in https://github.com/JonasNilson/idle_master_extended/issues/31#issuecomment-703079259_

**Comment by dattabayo** [comment]
I downloaded it today and i am facing similar issue as @DumbJoe

**Comment by DumbJoe** [comment]
Oh...I guess I'm not the only one....nice to know...

**Comment by Much-Dig** [comment]
I have the same problem because of the QuickLogin, i put my nick and password quick and the Steam Guard opened but it closed fast

**Comment by Much-Dig** [comment]
I went to configuration, and uncheck the QuickLogin option, i restarted IdleMaster and i could login.

**Comment by JonasNilson** [comment]
It could be related to issues with Internet Explorer (which is the base for the C# browser window)

Can you try out the latest version and see if it helps?

**Comment by DumbJoe** [comment]
The latest version is 11....can't you have the browser window piggerback off firefox or chrome? Or some other browser?

**Comment by DumbJoe** [comment]
huh....still not working on 1.6 for me.....any more ideas?

**Comment by JonasNilson** [comment]
@DumbJoe Currently a lot of the code is based on the C# WebBrowser which is based on Internet Explorer.

You can try and use this method to log in: https://github.com/JonasNilson/idle_master_extended/issues/27#issuecomment-577597720
