### ISSUE TITLE
Unable to connect my Steam Account with Idle Master.

### ISSUE THREAD

**Issue by luxness** [JonasNilson/idle_master_extended#124]
When I login, yes i can login but it still says 'idle master is not connected with Steam.'

**Comment by Jeadness** [comment]
I tried using v.1.5 version, i can login, but cant login in v1.6 version.

**Comment by 0lm** [comment]
checked any firewall settings? with new software versions, usually new firewall rights need to be given.

**Comment by JonasNilson** [comment]
@Jeadness 

Can you provide a description on what part of the login fails?

Maybe a screenshot or two as well

**Comment by Jeadness** [comment]
![image](https://user-images.githubusercontent.com/68141999/96469977-7d05d400-1236-11eb-838a-494e6eed322a.png)

![image](https://user-images.githubusercontent.com/68141999/96470053-91e26780-1236-11eb-8769-70a652c00a30.png)

sorry if its turkish

**Comment by JonasNilson** [comment]
@Jeadness what happens when you try to sign in?

**Comment by Denso95** [comment]
Same problem here. The window closes after I click on "login" after a few seconds and nothing else happens.

**Comment by Kastronoth** [comment]
I have the same problem too. I cannot log in at all, whether I choose the quick-login option or try to enter my credentials manually. The login window closes very quickly and doesn't save any information.

**Comment by Jeadness** [comment]
> @Jeadness what happens when you try to sign in?

when i enter my password & username, i can sign in, but it says idle master is not connected with steam idk how to explain

**Comment by Jeadness** [comment]
So I'm using v.1.5 version, it works

**Comment by Kastronoth** [comment]
Yes, I just reverted back to v.1.5 and it works fine.

**Comment by JonasNilson** [comment]
@Jeadness @Kastronoth @Denso95 

Do you get any output in your `error.log` ? I have not been able to reproduce the issue myself.

Also you can look into logging in using another method: https://github.com/JonasNilson/idle_master_extended/wiki/Not-able-to-login

**Comment by Jeadness** [comment]
i dont see a file named error.log i dont know

**Comment by felidira** [comment]
[error.log](https://github.com/JonasNilson/idle_master_extended/files/5419203/error.log)
i have the same issue, here is my error.log

**Comment by Jeadness** [comment]
Yeah i think you guys should remake the v.1.6 version or idk

**Comment by JonasNilson** [comment]
@Jeadness

It's just me here, and I need to find a way to reproduce the issue myself before I can fix it

**Comment by Trismogestos** [comment]
[error.log](https://github.com/JonasNilson/idle_master_extended/files/5422863/error.log)

**Comment by Mertk21** [comment]
22.10.2020 20:08:16   
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)  "Error.log"

**Comment by Mertk21** [comment]
@JonasNilson 
[error.log](https://github.com/JonasNilson/idle_master_extended/files/5424445/error.log)

**Comment by sinncraft** [comment]
Same issue here, I enter my details and the window just closes after like 10 seconds with no response, I wish I could give you the error log but it does not produce one

**Comment by Jeadness** [comment]
Somehow it worked for me now, idk.

**Comment by Jeadness** [comment]
wait no it doesnt work anaymore

**Comment by Jeadness** [comment]
and also, when i try to run v.1.5 it says its v.1.6 version but i can login.

**Comment by JesWhite** [comment]
i cant join with 1.6 with my username and password.
i joined with 1.6 Quick-Join button.
And 1.4 working with username and password login.

**Comment by Jeadness** [comment]
i recommend everyone to use 1.5 and if you cant login, use 1.4
i use 1.5

**Comment by JonasNilson** [comment]
@JesWhite @luxness @sinncraft @Kastronoth @Trismogestos 

If you are able to test out the pre-release of v1.7 I would appreciate it greatly: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.7-pre-release

**Comment by AlanRubioESP** [comment]
> @JesWhite @luxness @sinncraft @Kastronoth @Trismogestos
> 
> Si puede probar el prelanzamiento de v1.7, lo agradecería enormemente: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.7-pre-release

In the new version 1.7 preliminary it gives me the wrong password when I start with my steam account, I don't know if someone else happens to him

**Comment by JonasNilson** [comment]
> In the new version 1.7 preliminary it gives me the wrong password when I start with my steam account, I don't know if someone else happens to him

Can you explain a bit more around this in a separate issue?

**Comment by AlanRubioESP** [comment]
Yes, sorry if I did it in the wrong place

**Comment by AlanRubioESP** [comment]
> > En la nueva versión 1.7 preliminar me da la contraseña equivocada cuando comienzo con mi cuenta de Steam, no sé si le pasa alguien más
> 
> ¿Puede explicar un poco más sobre esto en otro número?

Yes, sorry if I did it in the wrong place
