### ISSUE TITLE
Minimizing Idle Master to system tray does not work

### ISSUE THREAD

**Issue by infernushawk** [JonasNilson/idle_master_extended#125]
I can send a screenshot if you would like, but essentially I have the box checked to minimize Idle Master to my system tray but it does nothing, even after minimizing or closing the application.

**Comment by JonasNilson** [comment]
I am not able to reproduce the issue myself. What version of Idle Master Extended are you using?

Currently if I have the setting enabled and minimize the window Idle Master will appear in my system tray:
- ![image](https://user-images.githubusercontent.com/5990550/97809893-3c637d00-1c70-11eb-976b-b6426a459969.png)
