### ISSUE TITLE
Problem with one of the accounts

### ISSUE THREAD

**Issue by MyauAmerican** [JonasNilson/idle_master_extended#126]
Hey there. Thank you very much for your effort creating this program. When I used the program on my first profile, everything worked great. However, I can't say the same about my second account. I started the program one and a half hours ago, and I did not get any cards. This is strange, considering that on my first account, it took the program only 30 minutes to get all cards.  Can you help me? Thank you in advance!

**Comment by MyauAmerican** [comment]
Okay, now, the problem seems to be gone. But maybe there is a bug causing it. Thank you anyways.

**Comment by JonasNilson** [comment]
What version of Idle Master Extended were you running?
