### ISSUE TITLE
[Browser] Internet Explorer is dead in Win 10

### ISSUE THREAD

**Issue by valko18** [JonasNilson/idle_master_extended#128]
I don't have IE in my Windows 10 and Idle Master simply can't log in

**Comment by Klekots** [comment]
@valko18 try set default browser is chrome or mozila

**Comment by valko18** [comment]
> 
> 
> @valko18 try set default browser is chrome or mozila

On Win 10? It's already set by me here, I never used or use IE 11

**Comment by JonasNilson** [comment]
> I don't have IE in my Windows 10 and Idle Master simply can't log in

Can you explain or show more of the scenario? The browser in Idle Master is based on the `WebBrowser` component in C#, which is based on Internet Explorer: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser

**Comment by valko18** [comment]
> 
> 
> > I don't have IE in my Windows 10 and Idle Master simply can't log in
> 
> Can you explain or show more of the scenario? The browser in Idle Master is based on the `WebBrowser` component in C#, which is based on Internet Explorer: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.webbrowser

Have you heard that IE won't work in Win 10 anymore? Well, it's not working for me already...

**Comment by JonasNilson** [comment]
@valko18 So I guess it depends on what version of Windows 10 you have. 

What happens when Idle Master tries to open the browser window?

**Comment by valko18** [comment]
> 
> 
> @valko18 So I guess it depends on what version of Windows 10 you have.
> 
> What happens when Idle Master tries to open the browser window?
> 
> You could also use the Cookie method to sign in through Idle Master: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

I have 2004 Win 10 version and what happens when I try to log in: 
![idle master](https://user-images.githubusercontent.com/35011192/97826650-c3f2cf80-1cf4-11eb-931d-a8718f4e7edb.jpg)

Thanks, I'll try cookie solution!

**Comment by JonasNilson** [comment]
@valko18 That sure looks odd. I might have to rework the browser window to tackle this issue in a future release

**Comment by valko18** [comment]
> 
> 
> @valko18 That sure looks odd. I might have to rework the browser window to tackle this issue in a future release

Maybe WIndows 10 tries to shut IE down and replace it with Edge?

**Comment by Katakuari** [comment]
@valko18 even in a new, fresh Windows 10 20H2 installation, the Internet Explorer 11 feature should be enabled. Maybe check if it is enabled and "reinstall" (uncheck > OK > restart PC > check > OK > restart PC) it? 
I'm not really sure if that would actually help though.
(also sorry about the german screenshots, I wasn't able to get an english iso)

You should be able to find it by searching something like "features"

![image](https://user-images.githubusercontent.com/24562538/98558915-4c014800-22a6-11eb-911e-b6445c78c64f.png)

![image](https://user-images.githubusercontent.com/24562538/98558205-7272b380-22a5-11eb-8825-fd13e00d1079.png)

**Comment by luxness** [comment]
install internet explorer 11 if you did not already try doing it

**Comment by luxness** [comment]
if you already have ie 11, try reinstalling it

**Comment by valko18** [comment]
> 
> 
> @valko18 even in a new, fresh Windows 10 20H2 installation, the Internet Explorer 11 feature should be enabled. Maybe check if it is enabled and "reinstall" (uncheck > OK > restart PC > check > OK > restart PC) it?
> I'm not really sure if that would actually help though.
> (also sorry about the german screenshots, I wasn't able to get an english iso)
> 
> You should be able to find it by searching something like "features"
> 
> ![image](https://user-images.githubusercontent.com/24562538/98558915-4c014800-22a6-11eb-911e-b6445c78c64f.png)
> 
> ![image](https://user-images.githubusercontent.com/24562538/98558205-7272b380-22a5-11eb-8825-fd13e00d1079.png)

Thanks, not IE 11 works, but Idle Master doesn't :-)

**Comment by JonasNilson** [comment]
> Thanks, now IE 11 works, but Idle Master doesn't :-)

What version are you running, and what isn't working?

**Comment by valko18** [comment]
> 
> 
> > Thanks, now IE 11 works, but Idle Master doesn't :-)
> 
> What version are you running, and what isn't working?

Already wrote here
https://github.com/JonasNilson/idle_master_extended/issues/128#issuecomment-720214250

IE 11, Idle Master 1.6, Win 10 v2004

**Comment by ravenor8787** [comment]
I have the same problem and I have id 1.7 I also have the Windows 7 system and it won't let me log in to id

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
