### ISSUE TITLE
windows 10 steam login failed

### ISSUE THREAD

**Issue by boss-subham** [JonasNilson/idle_master_extended#135]
cant login into my steam account even after repeated trails.

**Comment by Techmo79** [comment]
Yeah i have the same problem

**Comment by notslipjack** [comment]
the cookie method (or [advanced authentication](https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods)) works.

**Comment by lugum** [comment]
it stopped working since today and the cookies method does not work, it says something like login failed, try again.
