### ISSUE TITLE
Cannot log in with steam to IdleMaster

### ISSUE THREAD

**Issue by Qu3re** [JonasNilson/idle_master_extended#136]
Hello, i am not able to log in to IdleMaster with my steam. Could you help me somehow?

**Comment by luc4sv** [comment]
I have the same problem, I've done everything, old versions and nothing. It was dropping a lot, but it happened.

**Comment by Miademora** [comment]
Same here. was working yesterday.
No Windowsupdate or similar.
All i see is a request with no reply when i try to sign in.
High Resolution Date & Time:	18.11.2020 18:41:47,9393024
Event Class:	Network
Operation:	TCP Receive
Result:	SUCCESS
Path:	mypc:28467 -> a23-63-121-119.deploy.static.akamaitechnologies.com:https
TID:	0
Duration:	0.0000000
Length:	31
seqnum:	0
connid:	0

**Comment by arrow2514** [comment]
Hello, i am not able to log in to IdleMaster with my steam. Could you help me somehow?

**Comment by milhouz** [comment]
In the same boat here tried a few different versions and all at the login page do nothing once hitting the Sign In button.

**Comment by arrow2514** [comment]
yes i agree with that milhouz

**Comment by arrow2514** [comment]
Can anyone help us

**Comment by milhouz** [comment]
@arrow2514 Chill out, this issue was reported and it will take the devs a bit to get around to looking at the issue since this isn't their full time job.

**Comment by milhouz** [comment]
@arrow2514 @Qu3re I do have a work around for the time being reading through the docs. https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods is the page that gives you the instruction to login via Cookies in your web browser.

**Comment by arrow2514** [comment]
I tried it didn't

**Comment by milhouz** [comment]
> I tried it didn't

Mine worked first try so not sure what is up. Are you sure you pasted in the correct SessionID value and cookie value.

**Comment by arrow2514** [comment]
Thank you. I got in wrong so I couldn't get in

**Comment by arrow2514** [comment]
Şimdi rahatça kullanabilirim

**Comment by luc4sv** [comment]
> @arrow2514 @Qu3re I do have a work around for the time being reading through the docs. https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods is the page that gives you the instruction to login via Cookies in your web browser.

Thank You so much bro, I will use it like this until they fix it, but thank very well.

**Comment by Miademora** [comment]
For me all 3 loginmethods dont work anymore. steamparental doesnt show up as a value in my cookie though.

**Comment by gore99** [comment]
hello, have been using v1.5 for months, just today i logged off my main to access my alt and when coming back to my main i can log into steam using idle master.exe, i saw v1.7 had been released so i gave it a try and i still cannot get the idlemaster.exe to login to my steam, haven't changed any passwords, when i put in my details on v1.7 and hit enter nothing happens, same goes for quick login. tried uninstalling and reinstalling, same for v1.5 D: pls help need my idle

**Comment by luc4sv** [comment]
> For me all 3 loginmethods dont work anymore. steamparental doesnt show up as a value in my cookie though.

But steamparental doesn't even appear, and you can login without it. Just with seassonid and steamlogin. If you get an error message when you click update, just close and apply it.

**Comment by luc4sv** [comment]
> hello, have been using v1.5 for months, just today i logged off my main to access my alt and when coming back to my main i can't log into steam using idle master.exe, so i looked online and saw v1.7 had been released so i gave it a try and i still cannot get the idlemaster.exe to login to my steam, haven't changed any passwords, when i put in my details on v1.7 and hit enter nothing happens, same goes for quick login. tried uninstalling and reinstalling, same for v1.5 D: pls help need my idle

that's what we're discussing, try login using the id's for the cookies and be happy: D
tutorial: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

**Comment by Miademora** [comment]
> 
> 
> > For me all 3 loginmethods dont work anymore. steamparental doesnt show up as a value in my cookie though.
> 
> But steamparental doesn't even appear, and you can login without it. Just with seassonid and steamlogin. If you get an error message when you click update, just close and apply it.

doesnt work here. i tried setting both values and then accept but it doesnt login
even setting the values manually in the .config file doesnt work

sometimes i get the following error in the error.log but dont know if its related
```
19.11.2020 08:39:50   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/76561198009344754
System.Exception: Response is null or empty. Added (+1) to RetryCount
   at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   at IdleMaster.frmMain.<GetBadgePageAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__24.MoveNext()

```

**Comment by Miademora** [comment]
> 
> 
> > > For me all 3 loginmethods dont work anymore. steamparental doesnt show up as a value in my cookie though.
> > 
> > 
> > But steamparental doesn't even appear, and you can login without it. Just with seassonid and steamlogin. If you get an error message when you click update, just close and apply it.
> 
> doesnt work here. i tried setting both values and then accept but it doesnt login
> even setting the values manually in the .config file doesnt work
> 
> sometimes i get the following error in the error.log but dont know if its related
> 
> ```
> 19.11.2020 08:39:50   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/76561198009344754
> System.Exception: Response is null or empty. Added (+1) to RetryCount
>    at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
>    at IdleMaster.frmMain.<GetBadgePageAsync>d__25.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at IdleMaster.frmMain.<LoadBadgesAsync>d__24.MoveNext()
> ```

i have 2fa enabled
i tried logging in to steam website with internet explorer 11 and it doesnt work. maybe thats why the popup doesnt work?
second i logged in to steam with a new browsersession, going through 2fa and now it works with manually entering sessionid and steamloginsecure. maybe my session was expired? it was working in the browser all the time without logging in again

**Comment by gore99** [comment]
i was able to get idle master to sign into my account for v1.7 using account cookies, would recommend using that method considering its fairly easy and only needs to be done once :D

**Comment by luc4sv** [comment]
> i was able to get idle master to sign into my account for v1.7 using account cookies, would recommend using that method considering its fairly easy and only needs to be done once :D

Yes! ;D

**Comment by luc4sv** [comment]
> > > > For me all 3 loginmethods dont work anymore. steamparental doesnt show up as a value in my cookie though.
> > > 
> > > 
> > > But steamparental doesn't even appear, and you can login without it. Just with seassonid and steamlogin. If you get an error message when you click update, just close and apply it.
> > 
> > 
> > doesnt work here. i tried setting both values and then accept but it doesnt login
> > even setting the values manually in the .config file doesnt work
> > sometimes i get the following error in the error.log but dont know if its related
> > ```
> > 19.11.2020 08:39:50   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/76561198009344754
> > System.Exception: Response is null or empty. Added (+1) to RetryCount
> >    at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
> >    at IdleMaster.frmMain.<GetBadgePageAsync>d__25.MoveNext()
> > --- End of stack trace from previous location where exception was thrown ---
> >    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> >    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> >    at IdleMaster.frmMain.<LoadBadgesAsync>d__24.MoveNext()
> > ```
> 
> i have 2fa enabled
> i tried logging in to steam website with internet explorer 11 and it doesnt work. maybe thats why the popup doesnt work?
> second i logged in to steam with a new browsersession (chrome/edge), going through 2fa and now it works with manually entering sessionid and steamloginsecure. maybe my session was expired? it was working in the browser all the time without logging in again

It's crazy, never seen it before

**Comment by JonasNilson** [comment]
As some of you have mentioned the login issues seem to be connected to the browser window being based on Internet Explorer.

https://github.com/JonasNilson/idle_master_extended/issues/139#issuecomment-731637786

**Comment by HSoeren** [comment]
Same, cannot log in, i enter my username and click on the password field and it clears all fields

**Comment by JonasNilson** [comment]
> Same, cannot log in, i enter my username and click on the password field and it clears all fields

What version are you using? https://github.com/JonasNilson/idle_master_extended/releases

**Comment by JonasNilson** [comment]
Dead issue.
