### ISSUE TITLE
[Interface] Incorrect Darkmode color

### ISSUE THREAD

**Issue by Blanco27** [JonasNilson/idle_master_extended#137]
![IdleMasterExtended_QQq8lvMTu7](https://user-images.githubusercontent.com/56546322/99586816-85456080-29e8-11eb-9fda-7b83edbef4c2.png)

As you can see in the screenshot the label `Derzeit aktives Spiel` is using the wrong fontcolor.

**Comment by IceCrunk** [comment]
ty

**Comment by JonasNilson** [comment]
Thanks for the feedback. I will look into the textbox font and color.
