### ISSUE TITLE
Blacklisting games doesn't work

### ISSUE THREAD

**Issue by fk-826** [JonasNilson/idle_master_extended#138]
Hey, Im not sure if its just me but the blacklisting option doesn't seem to work for me.I went into the settings and then blacklisting, it asked for the ids of the game so i googled the game's steam ids and added a few there and saved it.But later on it still was idling those games that i had blacklisted.What am i missing?

**Comment by JonasNilson** [comment]
Not sure to be honest. I will have to look into it when I get the time.

**Comment by JonasNilson** [comment]
The blacklist seems to work for me, but only after I have restarted the application.

**Comment by fk-826** [comment]
> The blacklist seems to work for me, but only after I have restarted the application.

Okay thanks will try retarting it
