### ISSUE TITLE
@Jeadness

### ISSUE THREAD

**Issue by Gonza587** [JonasNilson/idle_master_extended#139]
@Jeadness 

Can you provide a description on what part of the login fails?

Maybe a screenshot or two as well

_Originally posted by @JonasNilson in https://github.com/JonasNilson/idle_master_extended/issues/124#issuecomment-712213787_

In my case, the program does not load me directly after putting my data

**Comment by ananashe** [comment]
I also have this problem for 2 days :(

**Comment by JonasNilson** [comment]
> In my case, the program does not load me directly after putting my data

I believe this is caused by the browser window being based on Internet Explorer.

I tried using plain Internet Explorer and the login button does nothing:
![image](https://user-images.githubusercontent.com/5990550/99887735-1b76c200-2c47-11eb-9ac6-acde7e7d90de.png)
