### ISSUE TITLE
Build Issues ~ Cannot Compile

### ISSUE THREAD

**Issue by HoldOffHunger** [JonasNilson/idle_master_extended#14]
**1** - `packages` is not a directory in the repo.

In `steamidle.csproj`, I see this...

    <Reference Include="Steamworks.NET">
      <HintPath>..\packages\Steamworks.NET.dll</HintPath>
    </Reference>

And yet, I do not see any "packages" folders within the repo.  The code did not compile until I updated `steamidle.csproj` to have the correct location of the Steamworks DLL file.

**2** - My machine is 64bit, the DLL wrapper you have for steam is 32bit.

If you try to compile, it errors out (" Could not run the "GenerateResource" task because MSBuild could not create or connect to a task host with runtime "CLR4" and architecture "x86".").  Additionally, there's a new Steamworks DLL wrapper, and it has 64bit support.  Unfortunately, both Visual Studio/Visual Studio Code say it's a corrupted file.

I used this hack to get it to compile: `<PropertyGroup><DisableOutOfProcTaskHost>true</DisableOutOfProcTaskHost></PropertyGroup>`

**3** - Yay, now it compiles!

And, it doesn't run or emit any logging or debugging.  Resulting file is 426kb.

**Comment by HoldOffHunger** [comment]
Would be super cool if someone knew something about the build process and could help out here.  I have some ideas for features to implement. =)

**Comment by JonasNilson** [comment]
I currently have no way of reproducing the issues, but:

1. That's definitely an incorrect path. I guess I never pushed the change I made locally.
2. I believe the original project had x86 specified, and I didn't bother trying the 64bit version of Steamworks.

You could try building it with a target platform as x86 and see if that helps.
