### ISSUE TITLE
Basically it doesn't log in when it did before. Besides that, it doesn't allow me to unlock every card for every game. More bellow.

### ISSUE THREAD

**Issue by AuN3T** [JonasNilson/idle_master_extended#141]
Recently I downloaded an instance of the 1.7 build, and it worked fine, although it just detected a few games of my hole library, not everyone. It confused me, but I thought it was a momentary glitch or something, and proceeded to unlock the cards it allowed me to unlock. Here comes the other rarity, and it is that I didn't get every card for every game it idle. Idk if that's how it works, but it just unlocked an aprox of 3 to 5 cards for each game, and then discarded them as if it was done with the entire set. Not awkward enough, when I concluded with all of them ("concluded" since it wasn't my entire library and didn't drop a whole single set for any gamexd), I decided to redownload the software and then try to log in again to see if it could be solved that way, quite wrong I was, cos at the moment of attempting it, and putting my data on, it standed still in the log page, with no signs of progress during aprox 40 minutes. Also tried with the quick login script with non positive results. In correlation to the how the program operates and if it is supposed to unlock every card, Im not sure if that's not its purpose, and its only for dropping a few. Would be glad to know:)
Have a great day!

**Comment by JonasNilson** [comment]
You typically are only eligible to get around half the cards for each game: https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete
