### ISSUE TITLE
Can't stay logged in

### ISSUE THREAD

**Issue by tonelesspanic** [JonasNilson/idle_master_extended#142]
I'm using the cookies method to log in because the browser doesn't do anything when I click the sign in button, but when I add my details it logs in for a second and then instantly logs out. I've tried v1.7, v1.5 and v1.3.
In v1.7 I can log in but it won't register that steam is running, and in 1.5 and 1.3 it will register that steam is running but wont stay logged in. 

In my error log for 1.5 I get

> 22/11/2020 3:32:39 PM   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/76561198018472061
> System.Exception: Response is null or empty. Added (+1) to RetryCount
>    at IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
>    at IdleMaster.frmMain.<GetBadgePageAsync>d__33.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()

I have tried running both IM and steam as administrator. Is there something I'm missing?

**Comment by JonasNilson** [comment]
You can ignore the steam status under Settings

**Comment by tonelesspanic** [comment]
I have that ticked but nothing happens (I have gotten 0 cards)

**Comment by JonasNilson** [comment]
Can you provide a screenshot of the application to show the issue?

**Comment by tonelesspanic** [comment]
![image](https://user-images.githubusercontent.com/4241258/100497942-cf7dcd00-31b2-11eb-986b-92dad1d92e7a.png)

**Comment by tonelesspanic** [comment]
![image](https://user-images.githubusercontent.com/4241258/100497959-e1f80680-31b2-11eb-94af-415029e9ac93.png)

**Comment by JonasNilson** [comment]
> ![image](https://user-images.githubusercontent.com/4241258/100497942-cf7dcd00-31b2-11eb-986b-92dad1d92e7a.png)

Interesting. The actual Steam status is fetched using Steamworks and calling `SteamAPI.IsSteamRunning()` so I guess that fails to begin with for some reason. 

I am not able to reproduce the issue myself and if the setting for ignoring the Steam client status is really active it should result in a string with the text: 'Steam client status ignored'

* ![image](https://user-images.githubusercontent.com/5990550/100551500-3b2e6b80-3281-11eb-9373-1ac9cfdb6e78.png)

Can you provide a screenshot of where you are running Idle Master Extended from (directory), and where Steam is installed (directory). Any information could help 🐱‍💻

**Comment by tonelesspanic** [comment]
IME is running from C:\idle_master_extended_v1.7-pre-release, 
Steam is running from C:\Program Files (x86)\Steam

**Comment by JonasNilson** [comment]
Since I can't reproduce the issue myself, maybe you can look into some of the common solutions: https://steamcommunity.com/groups/idlemastery/discussions/0/133257636766989675/
