### ISSUE TITLE
 He tells me that I don't have any chroma to farm, but actually I do

### ISSUE THREAD

**Issue by Davii10** [JonasNilson/idle_master_extended#144]
When I turn on the application it says that I no longer have chroma to farm, but I look at steam and I still have, what do I have to do to solve it?

**Comment by Davii10** [comment]
I mean, in steam I see that I am missing several chromas in several games and when I installed the application it farmed 4 cards and stopped working

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete
