### ISSUE TITLE
Not running any game

### ISSUE THREAD

**Issue by malekbkm** [JonasNilson/idle_master_extended#145]
Hello there, i'm having an issue while running idle master, i haven't used to program a long time ago (about 2years) so i'm not quite sure if i'm missing any steps or something, the errors that are shown are : 
28/11/2020 11:51:25 AM   frmMain -> SortBadges -> The method (mostvalue) resulted in an exception
System.Net.WebException: The remote name could not be resolved: 'api.enhancedsteam.com'
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at IdleMaster.frmMain.SortBadges(String method)

**Comment by malekbkm** [comment]
Here's what it looks like on the IDLE MASTER 

![image](https://user-images.githubusercontent.com/75164488/100514005-97a26580-3171-11eb-861d-ea1fd8a7d34e.png)

**Comment by JonasNilson** [comment]
Can you verify that you have card drops remaining?

https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

**Comment by malekbkm** [comment]
> Can you verify that you have card drops remaining?
> 
> https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

Omg, i feel so dumb that i didn't check that, I'm so confused tbh lol, i just collected some free steam keys yesterday so i thought that there are so many cards to collect, Eventually there are not.
Thank you for the reply :D 
![image](https://user-images.githubusercontent.com/75164488/100518283-e4e1ff80-3190-11eb-836f-cc190778a425.png)

**Comment by JonasNilson** [comment]
@malekbkm That is very common. It's not the most intuitive reward system and took time for me to figure out myself. Just finding information about it is a hassle.
