### ISSUE TITLE
hola . no me aparecen todos los juegos para farmear los cromos 

### ISSUE THREAD

**Issue by xXTIKYXx** [JonasNilson/idle_master_extended#151]
hola  , buenas tardes  como se puede hacer para agregar juegos , ejem  yo quiero farmear de juegos como dark soul 3, for honor , etc , pero no me aparecen  en la lista , desde ya muchas gracias

**Comment by Masitaa** [comment]
Si no te aparecen es porque ya no hay cromos que farmear, saludos.
