### ISSUE TITLE
[Login / Logout] steam randomly disconnecting after a while

### ISSUE THREAD

**Issue by Bluestacker** [JonasNilson/idle_master_extended#156]
Hi, sometimes idle master randomly disconnects from steam after a while, i have all default but minimize to tray enabled, using quick login script..., i just turn "shutdown windows when done" and go afk, but after some time like 1h or something steam disconnects and i stop getting cards, this even happens when im playing a game

(its only idle master, my steam app doesn't disconnect)

**Comment by link2110** [comment]
I also have this issue, just did a new install on a fresh windows install today.  I've had to sign in at least 3 or 4 times in the last two hours.

**Comment by Proutbedaine** [comment]
I have the exact same issue. I have the latest version (1.7) and randomly/intermitently my idlemaster app will disconnect from steam even though nothing else does and don't experience network issues. I'm on Win10 fyi. 

I'd like to know if that affects the drops? Does it mean nothing will drop or it's not too bad?

**Comment by JonasNilson** [comment]
@Proutbedaine it shouldn't affect the drop rate as Steam just thinks you closed the games as the background processes exits

**Comment by Proutbedaine** [comment]
Ah oki, so that means the drops do stop happening though. So we have to reconnect like I suspected (which only makes sense ofc, but wanted to make sure). Thanks for the answer!
