### ISSUE TITLE
So it always just says "idling complete" and if i try again it still the same thing so it no work advise?

### ISSUE THREAD

**Issue by Silacoplayz** [JonasNilson/idle_master_extended#157]

**Comment by Silacoplayz** [comment]
advise?

**Comment by JonasNilson** [comment]
Can you confirm that you have card drops remaining for those specific games?

**Comment by Kingpandaree** [comment]
i have the same problem, it says idling complete and wont let me continue idling after

**Comment by Kingpandaree** [comment]
actually im retarded, i just realized i cant get any more cards
