### ISSUE TITLE
Client saying steam is not running, was working before

### ISSUE THREAD

**Issue by blain-e** [JonasNilson/idle_master_extended#159]
I have tried logging out and back in on both steam and the client and it is stuck on "Steam is not running (Lastest release)" It was working on Release 1.7

**Comment by w2131978** [comment]
same problem,. I uninstall steam and reinstall it. now it's ok

**Comment by JonasNilson** [comment]
@blain-e You can disable the steam status check in the settings ("ignore Steam status")

**Comment by psyco752** [comment]
> @blain-e You can disable the steam status check in the settings ("ignore Steam status")

Good Jonas even if you do that it still does not work, at least it does not work for me, I hope you can repair this failure even with quick login I can not get it to work, the farm is frozen.

**Comment by JonasNilson** [comment]
@psyco752 Can you provide more info of the "failure"?

**Comment by tiago615** [comment]
i still have the same problem  and i uninstall steam and reinstall it. Any solution?

**Comment by PatrickWehri** [comment]
I had the same error yesterday, caused by my own stupidity:
I was running the .exe from within the unextracted .zip file. I was able to log into steam, but it would never been detected as running.
Today, after a reboot and actually extracting the .zip, it works fine.

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Steam-is-not-running
