### ISSUE TITLE
Not working with latest beta client

### ISSUE THREAD

**Issue by matrixino** [JonasNilson/idle_master_extended#16]
With the latest beta client (the new UI) steam is never recognized as running, so no idling starts.
Even ticking the "ignore steam client running" option has no effect (idling starts but no cards are collected, no in-game change on friend list).
The client is obsiously open but not detected anymore.

**Comment by JonasNilson** [comment]
Interesting. I'll see if I can take a look at the issue later this week :+1:

**Comment by JonasNilson** [comment]
@matrixino I'm sorry for the late reply. I haven't had much time on this project due to several reasons. 

Do you know if this still is an issue?

**Comment by matrixino** [comment]
> @matrixino I'm sorry for the late reply. I haven't had much time on this project due to several reasons.
> 
> Do you know if this still is an issue?

Sorry, I didn't use it lately. I'm on vacation till the 6th Jan. I can check when I'm back.

**Comment by defenderix** [comment]
hello guys.
this is happening for me too
https://steamuserimages-a.akamaihd.net/ugc/792003508800492211/18C2B6DFC1CA26413266E4D4783BAC37A237AAD6/
it was working well but i just restarted it then that happened.
how can i solve it?

**Comment by rodier** [comment]
Just start this program as admin by right clicking on exe and run as admin..

**Comment by JonasNilson** [comment]
As I am running with the latest beta client it seems like this is no longer an issue.
