### ISSUE TITLE
[Browser] Login web page is broken

### ISSUE THREAD

**Issue by MrL0G1C** [JonasNilson/idle_master_extended#162]
Valve have wrecked it again, maybe code could be copied from ASF for more reliable logins. - MrL0G1C

**Comment by JonasNilson** [comment]
Sounds like I need to look into it soon

**Comment by Areopagit** [comment]
JonasNilson, please, fix it.

**Comment by Heathcore** [comment]
same error bro

**Comment by JVSkellington** [comment]
Temporary solution : https://steamcommunity.com/groups/idlemastery/discussions/0/1697168437864920721/

**Comment by JonasNilson** [comment]
> Valve have wrecked it again, maybe code could be copied from ASF for more reliable logins. - MrL0G1C

> JonasNilson, please, fix it.

> same error bro

I haven't had much time for this project, but is this still an issue?

I can use the 1.7 version myself (both manual login and the 'quick login' button):

- ![image](https://user-images.githubusercontent.com/5990550/107129941-6f4d8a80-68c9-11eb-9f5b-52a11840bb9a.png)

**Comment by JVSkellington** [comment]
![Screenshot_9](https://user-images.githubusercontent.com/78332186/107130037-bf682500-68a8-11eb-81ae-268864afd0b5.png)
![Screenshot_10](https://user-images.githubusercontent.com/78332186/107130038-c0995200-68a8-11eb-9127-5a0873353e57.png)

**Comment by MrL0G1C** [comment]
Tried on 2 different PCs, problem occurs on 1 PC and not the other, I suspect it's something to do with IE version.

Doesn't work: IE V11.0.4
Does work: IE V11.0.9 (KB3049563)

Maybe installing KB3049563 will fix the issue.

**Comment by MrL0G1C** [comment]
Weird, works from France, doesn't work from UK.
Solution, use a VPN.

**Comment by MrL0G1C** [comment]
gdfghdfgh

**Comment by MrL0G1C** [comment]
I can't edit or delete comments, disregard the VPN one.

**Comment by MrL0G1C** [comment]
Going to IdleMasterExtended Menu > File > Settings > Padlock (bottomLeft) 
Copying the data from cookies for store.steampowered.com to the 1st and 2nd boxes
Worked.

**Comment by MrL0G1C** [comment]
The working page was only working because it was cached, the reason the login page isn't working is because Valve have updated the web-page and it no longer works in Internet Explorer. Grabbing the Cookie data after logging in steam in some other browser is currently the only option.

**Comment by JonasNilson** [comment]
@MrL0G1C Alright. I must've had a cached page myself. Thanks for the research 💪🏻

**Comment by JonasNilson** [comment]
The latest release removes the web browser: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
