### ISSUE TITLE
This is safe to use?

### ISSUE THREAD

**Issue by ZeskOficial** [JonasNilson/idle_master_extended#164]
I can get a VAC ban or any type of punishment in my account, thanks for your tope to reply/read this

**Comment by zakuma666** [comment]
using this every now and then for a few years now. Never had any problem. Dont use it and play maybe.

**Comment by JonasNilson** [comment]
You will not get a VAC ban as Idle Master: https://steamcommunity.com/groups/idlemastery/discussions/0/1470840994972378287/

But you may experience issues (not able to connect to servers) if you play VAC games and have Idle Master running: https://support.steampowered.com/kb_article.php?ref=2117-ilzv-2837
