### ISSUE TITLE
[Idle mode] spam bug (mid level priority)

### ISSUE THREAD

**Issue by MarceloBrazolim** [JonasNilson/idle_master_extended#166]
been using for years the non extended version and came across this one recently as i didn't know the jshackles version was discontinued.

been using for 5 hours at this moment and was running in the "idle games simultaneously up to 2 hours, then individually" settings for this time, and a lot of friends complained about me "changing games each 2 seconds", at the point. I started the idle master at 10am, the game change flood started at 12pm and continued until i changed the mode to "idle each game individually" at 3pm.

bugs
1. 
i don't know C# yet to appoint the problem but this is what **i think might be** the problem: the priority of the chosen game to display on playing at steam is based on seconds played, meaning each second it increments, the idler pick the next played game for less hours.

2.
what i don't understand is that the program should(?) change to individual mode once every game has 2+ hours, wich was the case, but it continued in simultaneous mode.

hope this helps on fixing the bugs <3
regards.
aka Hiro.

**Comment by JonasNilson** [comment]
> and a lot of friends complained about me "changing games each 2 seconds", at the point. I started the idle master at 10am, the game change flood started at 12pm and continued until i changed the mode to "idle each game individually" at 3pm.

That sounds like the "Fast mode" was activated. https://github.com/JonasNilson/idle_master_extended/wiki/Fast-mode

> 1.
> i don't know C# yet to appoint the problem but this is what **i think might be** the problem: the priority of the chosen game to display on playing at steam is based on seconds played, meaning each second it increments, the idler pick the next played game for less hours.

That should not be the issue as far as I understand. The list of games to idle is based on the games found on your badge page and the card drops remaining, not the hours. The hours do count when checking if it has passed 2 hours.

- https://github.com/JonasNilson/idle_master_extended/blob/fea60bdf7ed0c86c98fe9241df1458040d1a8cfe/Source/IdleMasterExtended/frmMain.cs#L40
- https://github.com/JonasNilson/idle_master_extended/blob/fea60bdf7ed0c86c98fe9241df1458040d1a8cfe/Source/IdleMasterExtended/frmMain.cs#L617

> what i don't understand is that the program should(?) change to individual mode once every game has 2+ hours, wich was the case, but it continued in simultaneous mode.

That is true. It should change, if that setting is active:
- https://github.com/JonasNilson/idle_master_extended/blob/fea60bdf7ed0c86c98fe9241df1458040d1a8cfe/Source/IdleMasterExtended/frmMain.cs#L305

**Comment by MarceloMarchezini** [comment]
> That sounds like the "Fast mode" was activated.

It was not. print of settings for idle master on 2/6/2021:

![image](https://user-images.githubusercontent.com/22665661/108286153-549bd100-7167-11eb-9df9-ef90c997a845.png)

> That is true. It should change, if that setting is active:

Maybe it has something to do with @deividbreck 's error?:
```log
06/02/2021 08:26:39   
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMasterExtended.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```
Still unsure what it affects tho.. but found the same log on error.log

I'm running on Win 8.1 v6.3 b9600 / indle master v1.7 c801eaf
