### ISSUE TITLE
@JonasNilson 

### ISSUE THREAD

**Issue by deividbreck** [JonasNilson/idle_master_extended#167]
System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
   em IdleMasterExtended.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   em System.Windows.Forms.Timer.OnTick(EventArgs e)
   em System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I have this error in the idle master can someone help me
?

**Comment by JonasNilson** [comment]
@deividbreck How does this error affect you? Some screenshots of the application would help
