### ISSUE TITLE
Can't log in to Steam

### ISSUE THREAD

**Issue by broman** [JonasNilson/idle_master_extended#17]
I sign in to Steam and it tells me "Idle Master is Saving your Information..." and never connects to Steam.

**Comment by JonasNilson** [comment]
I'm sorry for the late reply, is this still an issue?

I was able to log in just now: 
![image](https://user-images.githubusercontent.com/5990550/66715126-e3544d00-edbf-11e9-9ada-9bf35335b1ba.png)
