### ISSUE TITLE
window to refresh steam login keeps popping  up

### ISSUE THREAD

**Issue by JacProsser** [JonasNilson/idle_master_extended#171]
![Screenshot_1](https://user-images.githubusercontent.com/48368615/107967234-c7a91a00-6fa4-11eb-84a3-896a1acb294f.png)

**Comment by JonasNilson** [comment]
That's the first time I've seen this issue. Can you provide more information on when this happens and how often?

**Comment by JacProsser** [comment]
well it started happening as soon as i started the program and then it would constantly keep doing it. however right now and since i've made this issue it has decided to stop bringing up this page
