### ISSUE TITLE
idle master extended dont drop nothing 

### ISSUE THREAD

**Issue by Fasquito** [JonasNilson/idle_master_extended#172]
idle master doesn't drop anything and doesn't count the hours in the games, how do I solve it?
![image](https://user-images.githubusercontent.com/79133856/108031565-d678e680-700f-11eb-9456-b7c256ff2b7f.png)

**Comment by souvikcr7** [comment]
well it happend to me also...nothing drop

**Comment by JonasNilson** [comment]
@Fasquito Idle Master extended can't make the cards drop. This is fully controlled by Steam.

It should start dropping between 2-3 hours so that you don't get cards and then do a refund of the game, but if that's not the case and your hours have been counted by Steam you should get in contact with them.

**Comment by souvikcr7** [comment]
Actually my was dropping, but it suddenly stopped.....
After exit i try to sign in another account, but it also doesn't work

**Comment by Fasquito** [comment]
i think that the problem is not steam because it dosent count the hours in the game, i have played 2,9 hours the scapist and i had the idle master 7 hours open and the hours in the scapist still the same

**Comment by souvikcr7** [comment]
So how to fix it?? Card are not dropping from new account too

**Comment by JonasNilson** [comment]
@souvikcr7 can you provide a screenshot of your badge page?

https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

**Comment by Vinedelux** [comment]
just find out you have to wait 7 days to drop more cards i made some research on google

**Comment by souvikcr7** [comment]
cannot find where to give screenshot

**Comment by souvikcr7** [comment]
like no card is dropping

**Comment by JonasNilson** [comment]
@souvikcr7 You can paste (CTRL+V) a screenshot directly in this GitHub issue

**Comment by JonasNilson** [comment]
> just find out you have to wait 7 days to drop more cards i made some research on google

@Vinedelux Can you provide a source of that information? It could come in handy when helping others
