### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by uzdiiilekk** [JonasNilson/idle_master_extended#173]
i have this aplication maybe 6 months back and it working nice but now i download it again but for other steam account and it say me this (idling complete. no more card drops available)
![image](https://user-images.githubusercontent.com/73359998/108628891-878edf00-745d-11eb-8111-7e8ef01e0003.png)

can you help me please ?

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

If your account don't have card drops remaining there is not much Idle Master Extended can do about it
