### ISSUE TITLE
[Browser] error message in log file 

### ISSUE THREAD

**Issue by ANGELO121234** [JonasNilson/idle_master_extended#178]
![Screenshot_1](https://user-images.githubusercontent.com/80230075/110262047-1be65f00-7f91-11eb-8542-170e11756203.png)

Wha i do?

**Comment by JonasNilson** [comment]
@ANGELO121234 how does this error affect you?

**Comment by RobtouCarlinhos** [comment]
I have the same case. When I try to log in with my steam acount, an extra note block is created in the folder of idle master. The name of that file is error and it contains the same message as @ANGELO121234. That doesn't let me sing in with steam manually or even with the quick login, and I couldn't start idle. i'm running it on windows 8.1 in 1.7 version of IM.  I already don't now the solution for that

**Comment by JonasNilson** [comment]
The latest release removes the web browser: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
