### ISSUE TITLE
Automatic login feature?

### ISSUE THREAD

**Issue by int22** [JonasNilson/idle_master_extended#18]
There's a web server running in the Steam client that lets you utilize it to login much faster in web browser. With this added, you can login without having to provide an auth code.

`LoginUsingSteamClient(window.location.origin);`

**Comment by JonasNilson** [comment]
Interesting. I'd appreciate a pull request with the feature, if you are able to test it 🐱‍💻

**Comment by int22** [comment]
Alright, I've made a pull request with it
#20
