### ISSUE TITLE
Idling complete... When not

### ISSUE THREAD

**Issue by alxs893** [JonasNilson/idle_master_extended#180]
It says "Idling complete"
![image](https://user-images.githubusercontent.com/57545686/111262506-2218b300-8603-11eb-9f84-9d86b220c169.png)

but it really isn't, there are lots of game that haven't been idle'd and i never played
like:
![image](https://user-images.githubusercontent.com/57545686/111262622-4d030700-8603-11eb-8df5-5c7c423cea20.png)
![image](https://user-images.githubusercontent.com/57545686/111262662-62783100-8603-11eb-9848-671eafa0c537.png)
![image](https://user-images.githubusercontent.com/57545686/111262715-76239780-8603-11eb-8f58-f61a8bb76d7c.png)
![image](https://user-images.githubusercontent.com/57545686/111262785-93f0fc80-8603-11eb-9e54-65a376795a96.png)

And i can continue, i don't know why is this happening

I'm sorry if my english is sorta broken, i never write in english. 
As you can see in my screenshots i talk spanish.

**Comment by JonasNilson** [comment]
Hopefully this can shine some light on the issue: https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

**Comment by alxs893** [comment]
> Hopefully this can shine some light on the issue: https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

ty a lot

**Comment by JonasNilson** [comment]
@alxs893 No worries 🤘🏻
