### ISSUE TITLE
it says i dont have games to idol whene i do pls help

### ISSUE THREAD

**Issue by AKO1465** [JonasNilson/idle_master_extended#181]
[](url)
![2eaa4a3f-ac91-40e1-8dea-f671e463bab5](https://user-images.githubusercontent.com/80847626/111513476-8483c780-8759-11eb-98c3-7e94caaede4e.jpg)

**Comment by AKO1465** [comment]
![image](https://user-images.githubusercontent.com/80847626/111513777-d0cf0780-8759-11eb-8b5c-cdcfc10197c8.png)

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

That should give you an idea of what is required to get cards
