### ISSUE TITLE
Trouble farming trading cards

### ISSUE THREAD

**Issue by NeoHowls** [JonasNilson/idle_master_extended#182]
add the Error log, for a few weeks it has given me this error that it no longer farms the cards, it remains static, I also cannot log into the program.
[error.log](https://github.com/JonasNilson/idle_master_extended/files/6164921/error.log)

![1](https://user-images.githubusercontent.com/80903773/111645309-55179e00-87df-11eb-868d-0659b82f3393.PNG)

I have the latest version uploaded

**Comment by JonasNilson** [comment]
Looks like the application is starting in a weird state. I will have a look at the error log later when I have time.

https://github.com/JonasNilson/idle_master_extended/wiki/Get-started
