### ISSUE TITLE
[Login / Logout] Sign out not work correctly 

### ISSUE THREAD

**Issue by hjalalian** [JonasNilson/idle_master_extended#183]
i have 2 steam account and want to switch the steam account from idle master extended and when i click sign out and sign in again its automaly sign in to my default account so i cant change the login information

**Comment by PauloWar** [comment]
the same here

**Comment by PauloWar** [comment]
bro i found a solution:
https://steamcommunity.com/groups/idlemastery/discussions/0/1697168437864920721/
work for me

**Comment by F9RogerF** [comment]
holaa, ayudaa por favor. me esta pasando lo mismo y cuando copio eso y lo busco no me aparece en mi computadora. me podrian explicar paso a paso como es en español? muchisimas gracias

**Comment by JonasNilson** [comment]
Related: https://github.com/JonasNilson/idle_master_extended/issues/184

**Comment by JonasNilson** [comment]
If you still experience these issues you can give the latest release a try: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA
