### ISSUE TITLE
[Question] Playing a game at the same time?

### ISSUE THREAD

**Issue by Proutbedaine** [JonasNilson/idle_master_extended#185]
Hi, sorry to bother you with this but I looked everywhere on info about this relative to this version and couldn't find anything.

I wanna know if playing a game on steam while it is running is a bad thing for the process of dropping cards? And if so, what does it affect? Because if it's still productive I'll continue having it open at the same time.

So essentially, what's more productive long term (I have 1000+ games to idle lel), keeping it open while I play or nah?

Thank you for this project btw <3

**Comment by graphixela** [comment]
You can play a game at the same time it's running.

**Comment by Proutbedaine** [comment]
> You can play a game at the same time it's running.

Like implied in my question, I know I can. I just wondered if it affected the idling at all. I've seen in some places saying if you play a game at the same time the cards can take wayyyy longer to drop depending on the game. But they are all 3+ old answers. So dunno if it was just an old issue that got corrected or etc. Or if there is new issues or other stuff not mentioned.

**Comment by graphixela** [comment]
> 
> 
> > You can play a game at the same time it's running.
> 
> Like implied in my question, I know I can. I just wondered if it affected the idling at all. I've seen in some places saying if you play a game at the same time the cards can take wayyyy longer to drop depending on the game. But they are all 3+ old answers. So dunno if it was just an old issue that got corrected or etc. Or if there is new issues or other stuff not mentioned.

That's what I was implying, it's fine. But I've only played a game while idling games individually. I stopped doing games in fast mode. While obviously faster, I had issues with TrueSteamAcheivements not picking up achievements won in new games after I did that mode. That was a few months ago. You can always just try it. Your mileage may vary from others.

I've always had cards drop at the same intervals. Sometimes if you manually pause it, it will drop faster. And by faster, I don't mean you idle the game less but in my experience, the program is generally about 5 - 10 minutes behind. Games that are longer in game length tend to have longer drop intervals.

**Comment by Proutbedaine** [comment]
> > > You can play a game at the same time it's running.
> > 
> > 
> > Like implied in my question, I know I can. I just wondered if it affected the idling at all. I've seen in some places saying if you play a game at the same time the cards can take wayyyy longer to drop depending on the game. But they are all 3+ old answers. So dunno if it was just an old issue that got corrected or etc. Or if there is new issues or other stuff not mentioned.
> 
> That's what I was implying, it's fine. But I've only played a game while idling games individually. I stopped doing games in fast mode. While obviously faster, I had issues with TrueSteamAcheivements not picking up achievements won in new games after I did that mode. That was a few months ago. You can always just try it. Your mileage may vary from others.
> 
> I've always had cards drop at the same intervals. Sometimes if you manually pause it, it will drop faster. And by faster, I don't mean you idle the game less but in my experience, the program is generally about 5 - 10 minutes behind. Games that are longer in game length tend to have longer drop intervals.

Ahhh oki I see. As long as I can do my achievement regularly in steam itself I don't care too much. Anyways been a while I finish idling all my games now I'll only have to do new ones if they have cards. Thanks for the various precise info though it's appreciated! :)
