### ISSUE TITLE
I clicked remember account

### ISSUE THREAD

**Issue by leanduo** [JonasNilson/idle_master_extended#187]
I clicked remember account and now whenever I want to log in, I enter exactly the account that I remembered, even uninstalling the program and reinstalling it does not help, I have many accounts that are not limited to Steam and I need to farm cards on them, what should I do?

**Comment by JonasNilson** [comment]
https://steamcommunity.com/groups/idlemastery/discussions/0/152392786912268315/

You could try:

- Remove all file in this folder below and try again, this is where IM stores it's settings.
C:\Users\<username>\AppData\Local\IdleMaster

**Comment by leanduo** [comment]
Thank you!

> https://steamcommunity.com/groups/idlemastery/discussions/0/152392786912268315/
> 
> You could try:
> 
> * Remove all file in this folder below and try again, this is where IM stores it's settings.
>   C:\Users<username>\AppData\Local\IdleMaster

Thank you!

**Comment by pontifezo** [comment]
> https://steamcommunity.com/groups/idlemastery/discussions/0/152392786912268315/
> 
> You could try:
> 
> * Remove all file in this folder below and try again, this is where IM stores it's settings.
>   C:\Users<username>\AppData\Local\IdleMaster

Not working for me. Deleted C:\Users\<username>\AppData\Local\IdleMasterExtended but Idle Master Extended still auto logins  into the remembered account.

**Comment by Kryakz** [comment]
> Not working for me. Deleted C:\Users<username>\AppData\Local\IdleMasterExtended but Idle Master Extended still auto logins into the remembered account.
Im also still getting the issue after deleting the local data and reextracting the zip to my documents. I'm not even logged into that account on the pc.

**Comment by alisaedi76** [comment]
the solution didnt work for me and even after deleting the data still logs in to the same account

**Comment by JonasNilson** [comment]
You could try open Internet Explorer and clear data and caches. The browser window is based on IE, so it might fetch some cookies from there.

Or you could try the cookie method to log into another account (it's not the easiest way but should work)

**Comment by JonasNilson** [comment]
> Thank you!
> 
> > https://steamcommunity.com/groups/idlemastery/discussions/0/152392786912268315/
> > You could try:
> > 
> > * Remove all file in this folder below and try again, this is where IM stores it's settings.
> >   C:\Users\AppData\Local\IdleMaster
> 
> Thank you!

**Solution**: The original author fixed the issue by clearing the stored settings.

https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files
