### ISSUE TITLE
Idle master stopped working

### ISSUE THREAD

**Issue by ElJanero** [JonasNilson/idle_master_extended#189]
like 2 days ago, idle master took 4 to 5 hours to idle all the cards per game. But, now it's taking more than 10 hours per game and it haven't idle the cards yet.

**Comment by JonasNilson** [comment]
Idle Master can't affect when Steam drops the cards, sadly. What specific games required 10+ hours?

**Comment by ElJanero** [comment]
It weren't the games. It took +10 hs because i was using a limited account

**Comment by JonasNilson** [comment]
Conclusion: a limited account requires more hours to get cards

https://support.steampowered.com/kb_article.php?ref=3330-iagk-7663
