### ISSUE TITLE
Idle free games?

### ISSUE THREAD

**Issue by burgerlX** [JonasNilson/idle_master_extended#19]
Can this program be extended to idle free games? Would anything like this even work?

**Comment by JonasNilson** [comment]
You can use the executable delivered with Idle Master, called "steam-idle.exe".

For example: 

- Find the ID of the game you want to idle (for example: https://store.steampowered.com/app/252950 has the ID 252950)
-- Alternatively use https://steamdb.info/ to search for the game you want to idle
- Find the installation location of Idle Master Extended (for example: `C:\Users\<you>\Downloads\idle_master_extended_v1.3`)
- Start Command Prompt (CMD)
- Type in: 
`"C:\Users\Jonas\Downloads\idle_master_extended_v1.3\steam-idle.exe" 252950`
![image](https://user-images.githubusercontent.com/5990550/66715070-3548a300-edbf-11e9-9877-812f534b7b77.png)

Now you should have a process called `steam-idle` actively idling your game.

![image](https://user-images.githubusercontent.com/5990550/66715053-177b3e00-edbf-11e9-84df-9515329f929e.png)
