### ISSUE TITLE
Doesn't work after selling trading cards

### ISSUE THREAD

**Issue by byzocker** [JonasNilson/idle_master_extended#190]
So i thought it would be nice to get some trading cards to fill up my gem collection.
I ran it for about 3 hours and after that, it just stopped idling games
![image](https://user-images.githubusercontent.com/59401089/113350520-de7bb400-9339-11eb-8f09-9eed6540d487.png)
although I don't have the cards in my steam inventory because I converted them to steam gems
![image](https://user-images.githubusercontent.com/59401089/113350638-0703ae00-933a-11eb-8071-40d52016888f.png)
what do I do now? Since it doesn't work

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

You are eligible for a limited number of cards per game. When they've dropped you're expected to trade or buy the rest of the set
