### ISSUE TITLE
Steam is not running.

### ISSUE THREAD

**Issue by KucheEdno** [JonasNilson/idle_master_extended#191]
Hello, it says Steam is n
![Screenshot_1](https://user-images.githubusercontent.com/81798609/113391118-4f02ef00-9393-11eb-9158-0a54fc242a0c.png)
ot running but Steam is ON. How to fix it?

**Comment by JonasNilson** [comment]
This can happen if you run Steam as administrator and not idle master /or the other way around.

You can ignore the steam status under file > settings
