### ISSUE TITLE
talha erkoc

### ISSUE THREAD

**Issue by erkoctalhap** [JonasNilson/idle_master_extended#192]
dit werkt niet bij mij het telt af maar ik krijg geen ruilkaarten

**Comment by JonasNilson** [comment]
> this doesn't work for me it counts down but i don't get trading cards (Google Translate)

What games are you idling and how many hours do you have on them? Depending on how Steam sets their limits your account status will affect how many hours are required and how often your cards drop.

Free games also don't give you any card drops.
