### ISSUE TITLE
[Browser] steam login not working

### ISSUE THREAD

**Issue by Codesolist** [JonasNilson/idle_master_extended#193]
not working steam login

![image](https://user-images.githubusercontent.com/62503761/114050743-34e67680-9895-11eb-9f29-2313b35754da.png)

**Comment by khaledlab** [comment]
You have to close the steam login 2nd page after 5 minutes

**Comment by JonasNilson** [comment]
> not working steam login
> 
> ![image](https://user-images.githubusercontent.com/62503761/114050743-34e67680-9895-11eb-9f29-2313b35754da.png)

How are you running the application and do you get any error logs in your Idle Master Extended directory?
