### ISSUE TITLE
[Main window] Suma el tiempo de juego pero no me farmea y tampoco agrega nuevos juegos 

### ISSUE THREAD

**Issue by LilUmTitti** [JonasNilson/idle_master_extended#197]
![image](https://user-images.githubusercontent.com/82408833/114443844-8ef08000-9ba4-11eb-9b8e-a2f17b8fb167.png)

**Comment by LilUmTitti** [comment]
Me sube el tiempo de juego pero no me farmea ningun cromo y no me agrega ningun juego, ademas de q cdo termina el tiempo de comprobacion yo tengo q volver a clickear el actualizar el estado de los juegos

**Comment by LilUmTitti** [comment]
esta bugeado me toma como que esta farmeando los cromos pero no me dropea ninguno

**Comment by EliasEatsPants** [comment]
Traduje el texto con Google Translate, lo siento por el mal gramattik.

Yo tuve el mismo problema.
Pruebe en la configuración el comportamiento inactivo de "inactivo cada juego individualmente" y ejecute el programa como administrador.

**Comment by Fancrak27** [comment]
![imagen_2022-01-10_235004](https://user-images.githubusercontent.com/97491769/148872742-316b68cb-46ba-49bf-a774-b886b59bb758.png)
A mi me pasa que me dice que no tengo mas juegos para conseguir cromos pero esto no es asi...
![imagen_2022-01-10_235116](https://user-images.githubusercontent.com/97491769/148872878-ba6d14b3-8c1d-4677-a2de-87d98c1e3170.png)
Y este juego lo compre hace un rato
