### ISSUE TITLE
[Browser window] Quick Login Error

### ISSUE THREAD

**Issue by MdBourg98** [JonasNilson/idle_master_extended#198]
Quick Login shows my profile, but stops there. Didn't log in, still shows "Login Script Activated"

**Comment by JonasNilson** [comment]
What happens if you try to interact with your profile (e.g. clicking any any links?)

**Comment by MdBourg98** [comment]
Nothing, no links work, no scrolling or interaction whatsoever. almost like its just an image.

**Comment by JonasNilson** [comment]
@MdBourg98 can you provide screenshots of the issue and possibly some error log?

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
