### ISSUE TITLE
[Browser window] Omeu esta diferente ("mine is different")

### ISSUE THREAD

**Issue by MFSTROYA** [JonasNilson/idle_master_extended#199]
ele fica assim e nao faz o loguin 
![Screenshot_2](https://user-images.githubusercontent.com/83142905/115974129-f1e10000-a530-11eb-964e-0acbaaf57bf0.png)

**Comment by JonasNilson** [comment]
Related: https://github.com/JonasNilson/idle_master_extended/issues/219

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
