### ISSUE TITLE
[Main window] Badge page didn't load, will retry in 10 seconds - THE PROBLEM IT NEVER LOADS

### ISSUE THREAD

**Issue by DryreL** [JonasNilson/idle_master_extended#200]
![image](https://user-images.githubusercontent.com/20909077/116278143-809a8a80-a786-11eb-8918-a0793f601c51.png)

Please fix this problem in the next version. Thank you.

**Comment by JonasNilson** [comment]
Do you get any errors in the log file (should be available in the Idle Master Extended directory)

**Comment by DryreL** [comment]
Sure, here it is.
[error.log](https://github.com/JonasNilson/idle_master_extended/files/6531073/error.log)

**Comment by Hyyrokkin** [comment]
I have the same Problem but with a different error log
[error.log](https://github.com/JonasNilson/idle_master_extended/files/7091492/error.log)
