### ISSUE TITLE
NO issue but request

### ISSUE THREAD

**Issue by psychadelix** [JonasNilson/idle_master_extended#201]
It would be nice if you could add the possibility, that the program saves the black- and whitelist to a .ini or .config, this way we could easily add/remove game ID's. Right now it's a bit fiddly to handle ID's while the program is running.

**Comment by JonasNilson** [comment]
You can find the configuration file under:

- `%USERPROFILE%\AppData\Local\IdleMasterExtended\`

The whitelist goes under `name="whitelist"`:
```xml
<setting name="whitelist" serializeAs="Xml">
  <value>
  <ArrayOfString xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
```

**Comment by psychadelix** [comment]
Thanks for the answer, I really appreciate it. Didn't expect an appdata folder because of portable app. Maybe I should have checked that before, next time I do so ;)

**Comment by JonasNilson** [comment]
@psychadelix no worries. The legacy version of Idle Master was not portable but I kept the configuration setup in Idle Master Extended
