### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Etheriul** [JonasNilson/idle_master_extended#203]
I use the program usually but today I cant even open the app properly
![image](https://user-images.githubusercontent.com/72504182/116855352-e7de9180-ac01-11eb-9ebb-d160433aff30.png)

**Comment by JonasNilson** [comment]
@Etheriul if you open the .exe from the zip this can happen.

Make sure to extract the zip contents and run the .exe from that directory

**Comment by Etheriul** [comment]
I use the program extracted to my apps folder.I reinstalled the program several times
![image](https://user-images.githubusercontent.com/72504182/116855828-b6b29100-ac02-11eb-919d-2278a20fa9f5.png)

**Comment by Etheriul** [comment]
I runned the app from the zip and it worked thank you for developing the app btw

**Comment by Raidennnn** [comment]
Hello,
Could it be that the button to put the next game in inactive no longer appears? I mean the button next to the pause.
![WhatsApp Image 2021-06-13 at 05 45 29](https://user-images.githubusercontent.com/85822718/121800896-b991a000-cc0a-11eb-94ce-6eac2820341d.jpeg)

**Comment by Lemuradam** [comment]
![Ekran Alıntısı](https://user-images.githubusercontent.com/117944633/201501418-41b79020-f598-44ed-8065-3c93d26c1809.PNG)
