### ISSUE TITLE
[Sign in] Hi, Idle Master Extended keeps using my other account

### ISSUE THREAD

**Issue by Realal** [JonasNilson/idle_master_extended#204]
Hi there,

first thanks for checking bugs for Idle Master Extended!

Now I use two steam accounts. And I have tried to idle my first account today, and no matter what I do, like erasing the idlemaster files in appdata as explained in your advices, I get no window to change my username, and the program automatically uses my 2nd steam account for idling.

I deleted also Idle Master Extended + in appdata + every single cookie I stored manually, but alas, always the wrong account. How is this possible it remembers my previous account, because I deleted every history of it? Or so I believe.

So I cannot idle my main account. I also tried to type my steamid cookie (which section?), + steamSecure (where?) and parental (how?) to no avail.

This is the first time that happens, after several months of using v1.7 sporadically. I just idled my 2nd account before that problem, and it cannot be changed now. 

I also don't have the option to type my username and steam password, well to do this manually. This is odd because I read that there's normally this option left in the program options.

That's all. So the program doesn't work for me anymore (or for my 2nd account, yeah it works, but there's nothing left to idle now, there). Cheers!

**Comment by enzosanchezc** [comment]
Hi, i've just replied to another similar issue (#184). Please try that and let me know if it helps

**Comment by Realal** [comment]
Hi, I replied in the thread you linked. Thanks.

**Comment by Realal** [comment]
Hi there Jonas,

I read your response today, and then the thread you linked, by any chance.

And I have found your Cookie login method! 
https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

I did read this method somewhere else, but the explanations were incomplete. 
Now I have followed the Cookie method in the link, and it works now! 

My games from the correct account are iddling.

Thank you Jonas! and enzosanchezc
Big cheers

**Comment by Realal** [comment]
Please note, that when I stop iddling, and connect again, I have to use the Cookie method again. It is not repaired. -Cheers

**Comment by JonasNilson** [comment]
If you still experience these issues you can give the latest release a try: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
