### ISSUE TITLE
[Browser window] No carga los datos de la ventana de inicio de Steam

### ISSUE THREAD

**Issue by krizx100** [JonasNilson/idle_master_extended#205]
![iddle](https://user-images.githubusercontent.com/83935106/117601716-06222100-b11d-11eb-9015-12f1be99d7cb.png)

El error no me deja iniciar sesion en steam, por favor arregla el problema

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
