### ISSUE TITLE
[Sign in] Cant Sign into new account

### ISSUE THREAD

**Issue by thekais3r** [JonasNilson/idle_master_extended#206]
When try to sign out of an old account into a new one, it just keeps going back into the old account.
How do I sign into a new account?

**Comment by JonasNilson** [comment]
That sounds related to #204

**Comment by thekais3r** [comment]
it's also similar to #184 but there still hasnt been a fix yet

**Comment by JonasNilson** [comment]
You could try the cookie login method:https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

**Comment by JonasNilson** [comment]
If you still experience these issues you can give the latest release a try: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
