### ISSUE TITLE
Do you have to pay to get card drops?

### ISSUE THREAD

**Issue by rawtorp** [JonasNilson/idle_master_extended#21]
Hi, love your program! But i have a question, Do you have to pay for games to get card drops in them? ive read some articles and some say you have to pay 10$ in a game to be able to get card drops from them. Is this true?

**Comment by JonasNilson** [comment]
That is only true for free to play games. If you look under your badges page on Steam you should see all cards that you are eligible for 🤷🏻‍♂️
