### ISSUE TITLE
[Card drops] NOT IDLING

### ISSUE THREAD

**Issue by CsK1000** [JonasNilson/idle_master_extended#212]
It doesn´t matter how much time i left the thing idling, not a single card popped in my inventory

**Comment by JonasNilson** [comment]
@CsK1000 what games have you idled and for how long?

Also, what idling mode are you using?

**Comment by CsK1000** [comment]
I´ve been idling Battlepaths and Mind Spheres for 2 hours in the default mode. In the previous games i tried it happened the same. I know how idling works, but i just can´t realize what is the problem and can´t solve it. Maybe is a thing from my computer? Idk.. I used to Idle before with other games and it worked perfectly, but it seems it doesn´t anymore

**Comment by JonasNilson** [comment]
Can you provide some more information from your Steam badge page?

Also make sure you have card drops remaining, and that your account isn't limited in some way:
* https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete#make-sure-you-are-eligible-for-card-drops
* https://support.steampowered.com/kb_article.php?ref=3330-iagk-7663
