### ISSUE TITLE
[Main window] Doesn't idle

### ISSUE THREAD

**Issue by Warklot** [JonasNilson/idle_master_extended#213]
![image](https://user-images.githubusercontent.com/66135900/119620566-cdb55f00-be0d-11eb-905f-3dafa6183377.png)

all day it looks like this and doesnt idle any game

**Comment by Totesfleisch** [comment]
Im having the same issue, i already tried deleting the entire idlemaster folder and redownload it, but it stays exactly the same.
(Left is mine for reference, right is this thread.)
I cant click anything except "Latest Release", cant even log into my account, or access the Settings.
![6841e5e19a656a131883567e1631362d](https://user-images.githubusercontent.com/62449841/119748242-bf5e5600-be94-11eb-8f5f-b0ce976a7f38.png)

**Comment by JonasNilson** [comment]
Have you followed the steps to extract the program from the zip?

https://github.com/JonasNilson/idle_master_extended/wiki/Get-started

It might be a silly tip, but the application doesn't seem to execute properly...

**Comment by Warklot** [comment]
> Have you followed the steps to extract the program from the zip?
> 
> https://github.com/JonasNilson/idle_master_extended/wiki/Get-started
> 
> It might be a silly tip, but the application doesn't seem to execute properly...

sometimes it works sometimes it doesn't.So i dont think so that how i extrascted the progam  matters.

**Comment by Warklot** [comment]
![image](https://user-images.githubusercontent.com/66135900/120528799-84a07480-c3e4-11eb-8f7e-4c45b4c9512e.png)
looks like this but never idles it loads forever

**Comment by SpendIce** [comment]
I have a similar issue, I've been idling for about a day now, but the game hours are all still at 0.
![image](https://user-images.githubusercontent.com/62260972/120792359-cb3cbe80-c50b-11eb-9a46-657406cf2a37.png)

**Comment by Warklot** [comment]
> I have a similar issue, I've been idling for about a day now, but the game hours are all still at 0.
> ![image](https://user-images.githubusercontent.com/62260972/120792359-cb3cbe80-c50b-11eb-9a46-657406cf2a37.png)

btw try to reinstall or reopen multiply times or run  as administrator and it might work

**Comment by SpendIce** [comment]
Reinstalling it worked, thanks
