### ISSUE TITLE
[Steam API] Steam is not running

### ISSUE THREAD

**Issue by IkuSenpai** [JonasNilson/idle_master_extended#214]
Just says steam is not running. Restarting steam doesn't help. Nor does restarting the idle master or my computer. Just doesn't detect steam properly anymore and needs to get updated. 

![image](https://user-images.githubusercontent.com/28810005/119764804-f0279680-be66-11eb-8507-ac2075fcbe20.png)

**Comment by Totesfleisch** [comment]
Start steam as admin, that works for me.

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Steam-is-not-running
