### ISSUE TITLE
[Browser window] steam login window doesn't work

### ISSUE THREAD

**Issue by Seiyaan222** [JonasNilson/idle_master_extended#215]
![Screenshot_852](https://user-images.githubusercontent.com/85028363/120075502-ede85680-c077-11eb-9dc4-18df0aaa8e60.png)

**Comment by Seiyaan222** [comment]
nothing in this window works.

**Comment by JonasNilson** [comment]
Related: https://github.com/JonasNilson/idle_master_extended/issues/219

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
