### ISSUE TITLE
[Idling] Steam keeps online while idling

### ISSUE THREAD

**Issue by eldokanawolno** [JonasNilson/idle_master_extended#216]
![brokenidle](https://user-images.githubusercontent.com/85076280/120115234-042f0900-c183-11eb-9faa-fe2a08fd9130.png)
Idle Master looking like its working great, but my steam acc is showing "Online", not running game. Also i dont get any card from idling.

**Comment by JonasNilson** [comment]
If you look into your Task Manager, do you see steam-idle.exe processes starting up?

![image](https://user-images.githubusercontent.com/5990550/120536108-0ba11d00-c3e4-11eb-9078-6edfb1b7134c.png)

**Comment by JonasNilson** [comment]
Stale issue. Closing.
