### ISSUE TITLE
help please 

### ISSUE THREAD

**Issue by uzdiiilekk** [JonasNilson/idle_master_extended#218]
Hello i can´t find fix for this : 
![image](https://user-images.githubusercontent.com/73359998/120514725-e43f5580-c3cd-11eb-9ea4-ce4f3f1f23a7.png)
![image](https://user-images.githubusercontent.com/73359998/120514778-f1f4db00-c3cd-11eb-846f-db4b6a1d0807.png)
![image](https://user-images.githubusercontent.com/73359998/120514862-046f1480-c3ce-11eb-8ac0-0acabd4bb5fb.png)

**Comment by Warklot** [comment]
because it says in 3picture no cards left? or it translated bad on google translator

**Comment by uzdiiilekk** [comment]
sorry i am idiot.. i don´t know about this 
Now i reading something about it and i read that i can get limited number of cards

**Comment by colo13verdadeo** [comment]
Si tu juego fue canjeado gratis en steam y no por codigo, seguramente no te daran cartas por ser gratis.

**Comment by JonasNilson** [comment]
Reason: No more card drops remaining
