### ISSUE TITLE
[Browser window] Cannot sign in

### ISSUE THREAD

**Issue by ookaminoken** [JonasNilson/idle_master_extended#219]
Hi, I'm having the same problem some other users have while trying to sign in to Steam from the Idle Master window... I basically get this window:

![IME](https://user-images.githubusercontent.com/85372121/120863849-996b3c80-c58b-11eb-9fce-0c9cf5a13cc0.jpg)

I'm using Windows 7 on a borrowed old desktop PC since my laptop's hard drive died (the program worked fine on my laptop running Win10). 

I can't sign in via the Quick Login button (it stays showing "Login script activated..." forever) and the login button in the window doesn't work (so I can't sign in manually either). Each time I click on the Quick Login button I get this message in the error.log file:

System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMasterExtended.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I hope this info helps identify (and potentially solve) this issue.

Thanks a lot in advance for the help!

**Comment by ookaminoken** [comment]
Oh, I also tried to run IME with and without administrator privileges. It's a single-user system (so no log in to windows itself), I don't know if administrator privileges are always active, so I don't know if the Steam client runs with or without them.

**Comment by JonasNilson** [comment]
Can you open up Internet Explorer and look under "About Internet Explorer" to see what version you are using and respond with some more details?

![image](https://user-images.githubusercontent.com/5990550/120923007-8ca23200-c6cc-11eb-9abe-b4cbfb9afab6.png)
![image](https://user-images.githubusercontent.com/5990550/120923031-a2175c00-c6cc-11eb-882c-a4d8f9ee825b.png)

It might be due to running on Windows 7 but I have no way of confirming right now, so it's worth comparing the IE versions.

**Comment by ookaminoken** [comment]
IE v.11.0.9600.19596

**Comment by JonasNilson** [comment]
> IE v.11.0.9600.19596

What happens if you use Internet Explorer and browse to: https://steamcommunity.com/login/home/

**Comment by ookaminoken** [comment]
The login page shows just fine

**Comment by svecka** [comment]
I have the same problem. 3 Days ago it was all fine.

**Comment by matrixino** [comment]
Just right click -> refresh, it load just fine then.
Also to login press the Login button, enter won't work.
If you fail a login you need to refresh again.

**Comment by blazeb** [comment]
> 
> 
> Just right click -> refresh, it load just fine then.
> Also to login press the Login button, enter won't work.
> If you fail a login you need to refresh again.

just wanted to say that this worked for me, ty!

**Comment by ookaminoken** [comment]
Well, after a long while without even trying, I just by chance retried earlier today and the issue seems to have fixed itself (without even needing to do anything else), so I guess I can close the post now. Thanks a lot everyone!

**Comment by Beulu** [comment]
It's better for me, gui login was well. but can't connect, even I click on the button...
