### ISSUE TITLE
[Inquiry] Version for Ubuntu Server?

### ISSUE THREAD

**Issue by ngsoftDE** [JonasNilson/idle_master_extended#22]
Please develop a Version compatible with **Ubuntu Server**. Then its much easier for some users who owns a simple linux server [link to Ubuntu Sever page](https://ubuntu.com/download/server)

[SteamCMD](https://developer.valvesoftware.com/wiki/SteamCMD)

**Comment by ngsoftDE** [comment]
This will save electric power in most cases...

**Comment by JonasNilson** [comment]
Have you tried the Python version of idle master? https://github.com/jshackles/idle_master_py

**Comment by ngsoftDE** [comment]
Thanks! Helped a lot!
