### ISSUE TITLE
[Enhancement] Got a card drop with 7 minutes of gameplay.

### ISSUE THREAD

**Issue by krevlinmen** [JonasNilson/idle_master_extended#220]
![image](https://user-images.githubusercontent.com/56278440/120936147-b9f6dc00-c6dc-11eb-9013-c10dd1623b9b.png)
![image](https://user-images.githubusercontent.com/56278440/120936151-bebb9000-c6dc-11eb-89c2-a68b4ceaea2a.png)

I got 1 card for this specific game after letting IME run on multiple games for 7 minutes and then closing the app. Also, you can see that I received 7 cards in quick succession.

Card drops probably have some correlation with the act of opening and closing the applications, so maybe it would be interesting if IME restarted idling apps every so often?

**Comment by JonasNilson** [comment]
You're correct that Steam tends to favor exiting games. This behavior is leveraged while using Fast Mode: https://github.com/JonasNilson/idle_master_extended/wiki/Fast-mode
