### ISSUE TITLE
[Quick Login] quick login script not working anymore 

### ISSUE THREAD

**Issue by 0lm** [JonasNilson/idle_master_extended#221]
since today's steam client update, the quick login script is not working anymore. it gets stuck at "login script activated". (it worked fine just yesterday before steam client's update)

**Comment by Anfia** [comment]
+1

**Comment by Anfia** [comment]
> since today's steam client update, the quick login script is not working anymore. it gets stuck at "login script activated". (it worked fine just yesterday before steam client's update)

+1

**Comment by raffa258** [comment]
+1

**Comment by docsvs** [comment]
+1

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/issues/227

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
