### ISSUE TITLE
[Login] I can not login

### ISSUE THREAD

**Issue by Reidosmemes9000** [JonasNilson/idle_master_extended#224]
I can't log in to my main account, it only connects to the secondary account because the other day I was online on it, but it got buggy and I can't log out to be able to change the account

**Comment by svecka** [comment]
I also cannot login anymore :(

**Comment by Reidosmemes9000** [comment]
and how do i solve this can you help me?


Em seg., 14 de jun. de 2021 às 10:59, svecka ***@***.***>
escreveu:

**Comment by aiznation** [comment]
Delete the Idle master folder from AppData>Local. It's the solution for most of the sign in issues.

**Comment by Beulu** [comment]
Hi guys !

Impossible to connect, login window does nothing...

![steam_idle](https://user-images.githubusercontent.com/72515988/128574119-c9cd1369-8548-45af-b8c9-c2d11159ae16.png)

Tried on 2 differents computers, no folder in appdata/local.

**Comment by JonasNilson** [comment]
If you still experience these issues you can give the latest release a try: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
