### ISSUE TITLE
[Login] cant sign in my steam 

### ISSUE THREAD

**Issue by emironmp** [JonasNilson/idle_master_extended#226]
i tried with vpn and  already changed my internet connection but i cant login to steam and this is my issuse

error here : 

https://s4.uupload.ir/files/sharedscreenshot_9fh7.jpg

**Comment by aiznation** [comment]
Close idle master. Delete the idle master folder from AppData>Local. Launch app. See if it's fixed.

**Comment by docsvs** [comment]
> 
> 
> Close idle master. Delete the idle master folder from AppData>Local. Launch app. See if it's fixed.

Tried it, did not work.

**Comment by JonasNilson** [comment]
If you still experience this issue you can give the latest release a try: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
