### ISSUE TITLE
Can't get cards

### ISSUE THREAD

**Issue by iRaiZz** [JonasNilson/idle_master_extended#230]
Hi ! 
Since the beginning of June, I have not been able to obtain a card, is this normal?

**Comment by Siberet333** [comment]
For me it started malfunctioning yesterday. No card drops, application is showing some strange behavior, won't give me cards when running but after closing sometimes 5 cards will pop-up at the same time on steam.... It's also messing up with my Wifi connection and noticed a high CPU usage too, I have a very decent rig and it's noticeable.

**Comment by BlackBetaHD** [comment]
i cant either

**Comment by N0-Zero** [comment]
I Just started the Program Today I Will till you guys if i get anything 

> 
> 
> i cant either

You and

> 
> 
> Hi !
> Since the beginning of June, I have not been able to obtain a card, is this normal?

You

**Comment by 5P4RK3Y** [comment]
I am having the same issue with Ver 1.7 And it's October 19th, no matter which mode I set the idler to, nothing changes, no cards dropped, not sure how to resolve this...

**Comment by JonasNilson** [comment]
@5P4RK3Y what games of yours have card drops remaining? The easiest way to find them is to check your badge page.

And Steam will never drop a full set. Typically you get about half a set (e.g. 3 cards if the badge is 5 cards)

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete
