### ISSUE TITLE
[Browser / Login] Can't login into second account

### ISSUE THREAD

**Issue by Lucas-Di-Prinzio** [JonasNilson/idle_master_extended#231]
I have idle master connected to my main steam account but when i click on discconect and then on connect it automatically connects to my main steam account so basically i cant change the account connected to idle master

**Comment by Siberet333** [comment]
Idlemaster logs in using Internet Explorer, you can delete your Internet Explorer cookies and when you reopen idlemaster you'll be asked for a steam username/password, there you type the steam account you want to use.

**Comment by fleur200** [comment]
> Idlemaster logs in using Internet Explorer, you can delete your Internet Explorer cookies and when you reopen idlemaster you'll be asked for a steam username/password, there you type the steam account you want to use.

omg thanks so much

**Comment by JonasNilson** [comment]
If you still experience these issues you can give the latest release a try: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
