### ISSUE TITLE
Idlemaster no longer detecting steam and cant sign in

### ISSUE THREAD

**Issue by Scenal** [JonasNilson/idle_master_extended#232]
![image](https://user-images.githubusercontent.com/86877328/124353169-d7946400-dbfc-11eb-926b-0737e7e83424.png)

Idlemaster used to run fine and then  it just randomly stopped working,,,
I've tried reinstalling steam & checking for updates but the program still doesn't work.

If someone has any ideas on what I can do to resolve this issue it'd be greatly appreciated!

**Comment by int22** [comment]
It should work if you have "Steamworks.NET.dll" and "steam_api.dll" in the folder with the idle master program. Try downloading the latest release again?

If that doesn't fix your issue, I'm not sure what else to do..

**Comment by Lenmaer67** [comment]
Doesn't work for me anymore too

**Comment by CyberCreator** [comment]
+

**Comment by GrandJohnny** [comment]
fix :
https://www.youtube.com/watch?v=dQw4w9WgXcQ
