### ISSUE TITLE
[Processes] Games keep running even with steam being uninstalled and idle master extended deleted

### ISSUE THREAD

**Issue by Domiz15** [JonasNilson/idle_master_extended#233]
So basically i noticed that games won't stop running even when i deleted idle master extended (i had version 1.4 before), i then tried to switch to the last one (1.7), but it didn't help, then i tried to uninstall steam and delete all the files from my pc, but the games are still running... (i'm seeing that through the steam website on browser), can you help me please? I'm pretty desperate.

**Comment by JonasNilson** [comment]
> then i tried to uninstall steam and delete all the files from my pc, but the games are still running... (i'm seeing that through the steam website on browser), can you help me please? I'm pretty desperate.

I'm sorry for the late reply. Did you resolve this issue?

It sounds like the child processes of Idle Master Extended was still running for some reason. One way to find them is to use the Task Manager in Windows (`CTRL+SHIFT+ESC`) and kill them.
