### ISSUE TITLE
[Browser] Can't login bc of JavaScript 

### ISSUE THREAD

**Issue by Mayu225** [JonasNilson/idle_master_extended#238]
Hi,

I can't login since months bc browser says that Java is not activated. I checked it. It's activated in Chome and Internet Browser. Mozilla seems to don't support Java in general (no clue witch Browser opens). 
I originally worked with 1.5. Now I tried it with 1.6 and 1.7, but no difference.

Maybe I don't see something very easy with my less technology knowlege, so, would be happy to get help to run the program again.

And thanks for the chance to not collect everything manually :)

Kind regards
![Screenshot - 21 07 2021 , 19_16_25](https://user-images.githubusercontent.com/87776915/126535680-7ea9ac5d-006a-4af4-aa15-d47d8018c592.png)

**Comment by ravenor8787** [comment]
Hello, I have the same problem

**Comment by JonasNilson** [comment]
Looks related to the browser being Internet Explorer: https://github.com/JonasNilson/idle_master_extended/issues/128

**Comment by Mayu225** [comment]
Thanks for the answer. So if I translate it right, there was found no solution too. Sad. Hope the problem will be found some day and that it can be fixed.

**Comment by JonasNilson** [comment]
> Thanks for the answer. So if I translate it right, there was found no solution too. Sad. Hope the problem will be found some day and that it can be fixed.

You can use the cookie login method to skip the manual sign in within Idle Master Extended.

https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
