### ISSUE TITLE
[Application startup] Idle Master Extended Error

### ISSUE THREAD

**Issue by Wrollo042004** [JonasNilson/idle_master_extended#240]
So I woke up one morning to idle Team Fortress 2 and I realized that I was unable to idle. Not just that game but I wasn't able to idle anything. I noticed that a received a new part to the file named 'error'.  

![image](https://user-images.githubusercontent.com/88250890/127749995-39ac8ccd-1a47-4e57-8262-ed93b65ab893.png)

I reinstalled IME and it still kept having that error message pop up into the file after I launched it. Everytime I do launch it, I see this:

![image](https://user-images.githubusercontent.com/88250890/127750012-bb927f79-5d96-4643-a489-20f3b677f418.png)

As you can see, there is two 'sign in' parts. One covering the other. I stay signed in all the time so I don't know how this has happened. I can't seem to click anything aside from the 'Help' and the 'Latest Release' links. I already have the latest release so if there are any fixes for this, please let me know. If not, please could one be made (given that the creator sees this). Thank you!

**Comment by Tooloco** [comment]
Hey try launching as admin, that's what worked for me

**Comment by GoldenPooP** [comment]
Try deleting the %appdata% folder for idlemaster and idlemasterextended, then launching as admin.
that did the trick for me
![image](https://user-images.githubusercontent.com/19346307/134776324-4375bfa7-f98c-46ba-931d-69f10efdbbd2.png)

**Comment by JonasNilson** [comment]
Sorry for a very late reply.

> ![image](https://user-images.githubusercontent.com/88250890/127749995-39ac8ccd-1a47-4e57-8262-ed93b65ab893.png)

Looks like your error log is quite large. Can you provide some samples of what it contains?

> ![image](https://user-images.githubusercontent.com/88250890/127750012-bb927f79-5d96-4643-a489-20f3b677f418.png)

This is a common issue when the app does not start normally (for example when trying to run from within the original zip archive without extracting its contents)

**Comment by GoldenPooP** [comment]
Sorry but I don't have the details anymore, it's been some time and I
managed to fix it, I'll try to look for my solution tmw and let you know
what it was :)
