### ISSUE TITLE
[Login] Unable to sign in

### ISSUE THREAD

**Issue by slop-me** [JonasNilson/idle_master_extended#242]
Exactly as the title says I open up the page to sign in and after entering my credentials nothing happens. Tried with the script as well also results in nothing happening. Tried an older version also tried to clear the browser cache and history of internet explorer and microsoft edge... VER I tried 1.7, 1.3, 1.6 all of which has the exact same issue

**Comment by cheeft** [comment]
same shit :(

**Comment by LizardLicker** [comment]
Same issue... Login screen shows as normal, but clicking sign in does absolutely nothing.

**Comment by ncmeza** [comment]
Happens to me as well. I hope some workaround exists!

**Comment by JordanLapardin** [comment]
this guy fixes it https://www.youtube.com/watch?v=102LMsgVmto

**Comment by nachogalvan31** [comment]
> this guy fixes it https://www.youtube.com/watch?v=102LMsgVmto

Thanks!!

**Comment by hyoretsu** [comment]
> this guy fixes it https://www.youtube.com/watch?v=102LMsgVmto

Login in Chrome, Press F12, go to Application>Cookies. Then open Idle Master, go to File>Settings, click on the lock icon and fill the fields accordingly. Really annoying to do, especially if someone who isn't tech-savy is doing it, but it works.

No idea why it suddenly stopped working. (And apparently also happened back when v1.7 was released)

**Comment by ncmeza** [comment]
> 
> 
> > this guy fixes it https://www.youtube.com/watch?v=102LMsgVmto
> 
> Login in Chrome, Press F12, go to Application>Cookies. Then open Idle Master, go to File>Settings, click on the lock icon and fill the fields accordingly. Really annoying to do, especially if someone who isn't tech-savy is doing it, but it works.
> 
> No idea why it suddenly stopped working. (And apparently also happened back when v1.7 was released)

It works. Thank you.

pd: it seems steamparental attribute is not obligatory to fill on File>Settings. 
pd2: on Firefox you login, press F12 an go to Storage>Cookies

**Comment by GN022** [comment]
From what i used to do before is sign-in up manually like the F12 and copy paste of the values. It's interesting that we have to rely on this more instead of signing up directly.

**Comment by Cheesepile** [comment]
Same issue, and the temporary fix above works. Seems like Steam breaks this app every now and then. Guess we wait for the next update (hopefully)

**Comment by Rekuiemu** [comment]
Steam is now using edge backbone i believe dont quote me on this i personally have not looked into it just a rough guess and chrome and edge are both built off chromium so some voodoo magic can possible be done to get it working. with the announcement IE will finally be discontinued I'm pretty sure the last steam patch changed its browsing function to IE to edge.

**Comment by SkebbZ** [comment]
> 
> 
> Login didnt work for me either at first. But since a week login works again. Really awkward why it still does not work for some people. (But FYI, QuickLoginScript still doesnt work. Was talking about the normal Login)

True, seems it's letting me login again now.
This worked a few weeks back as well, but not the last time I tried it. 
QuickLogin seems to do nothing though, but at least I can login again manually.

**Comment by RELXIX-7DTD** [comment]
Same here.  Login option does not work when manually entering username/password and does not work when selecting to use the quick login for Steam client.

Forced to use the workaround of copying cookie manually into the idelmasterextended settings.

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
