### ISSUE TITLE
[Card drops] I start the program and it says "idling complete"

### ISSUE THREAD

**Issue by Kacsa26** [JonasNilson/idle_master_extended#243]
I can get cards and i've restarted it, i redownloaded it, i logded out and in, i restarted steam, and it doesnt work.
![bruhh](https://user-images.githubusercontent.com/89541270/130838138-2811348a-b5f2-4744-8f09-b936c2b28911.PNG)

**Comment by steamtruong** [comment]
Để nhận được thẻ từ một trò chơi, bạn cần có số thẻ còn

**Comment by JonasNilson** [comment]
> I can get cards and i've restarted it, i redownloaded it, i logded out and in, i restarted steam, and it doesnt work.


https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

What games do you own that have card drops remaining?
