### ISSUE TITLE
[Login / Logout] How to disable automatic login 

### ISSUE THREAD

**Issue by RatBath** [JonasNilson/idle_master_extended#247]
i have 2 accounts and i want to idle the other one but i cant bc of the quick login how do i change it?

**Comment by JonasNilson** [comment]
Sounds like there is an issue with the saved configuration. You can try delete the files here: https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files

Are you sure this is connected with the quick login: https://github.com/JonasNilson/idle_master_extended/wiki/Quick-login?

**Comment by JamParadox** [comment]
Doesn't work

**Comment by JonasNilson** [comment]
If you still experience these issues you can give the latest release a try: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
