### ISSUE TITLE
[Support] How Do i start the steam-idle.exe ?

### ISSUE THREAD

**Issue by rhanna471** [JonasNilson/idle_master_extended#248]
I watched a YouTube video telling me to put CD Then the file location then after that to put in the file name and my game id but it said batch file not found any fixes???

**Comment by JonasNilson** [comment]
Sounds like this could help: https://github.com/JonasNilson/idle_master_extended/issues/36#issuecomment-596105776

**Comment by 21mtd** [comment]
![image](https://user-images.githubusercontent.com/75530836/145027398-d04a7be8-b057-4e79-ab47-6b10f2b031f5.png)
create steam-idle.exe shortcut to desktop (you can paste multi shortcuts), search game IDs in your Badges site then put it at the end of the Target
