### ISSUE TITLE
[Linux] Can I run IME in Ubuntu?

### ISSUE THREAD

**Issue by arghanath007** [JonasNilson/idle_master_extended#249]
Can I use this on linux(ubuntu) with wine/proton?

**Comment by JonasNilson** [comment]
Sounds like it could be possible. I have not tried it myself, but Idle Master Extended is a portable application that just needs to run within its own directory.

**Comment by arghanath007** [comment]
Ok I will try it thank you.

**Comment by JonasNilson** [comment]
> Ok I will try it thank you.

Please report back your findings. After thinking about it again I think there could be some issues with having Wine run the process (depending how it is virtualized)

**Comment by arghanath007** [comment]
I dont know how to run it. You got any idea?

**Comment by alessio-ds** [comment]
nope, can't run it with wine (with mono and gecko installed)

**Comment by arvislacis** [comment]
Just an update if someone is still interested - I managed to successfully run IME from Steam with Proton 7.0-5 compatibility layer in Manjaro Linux.
