### ISSUE TITLE
Włącza się ale nie farmi (PL)

### ISSUE THREAD

**Issue by BloodyGoat** [JonasNilson/idle_master_extended#25]
![help](https://user-images.githubusercontent.com/59315705/71546646-85380e80-2999-11ea-8156-58d21017547a.PNG)

Czyściłem w appdata kombinowałem i nic dalej

**Comment by JonasNilson** [comment]
Is this still an issue?

**Comment by BloodyGoat** [comment]
zrobiłem wszystko co jest opisywaliście w innych tematach i myślę że nie działa to dla tego że już nie mogę więcej farmić 
![Przechwytywanie](https://user-images.githubusercontent.com/59315705/72972617-11d4c180-3dcc-11ea-8fb2-022b63a10bcd.PNG)

**Comment by JonasNilson** [comment]
> zrobiłem wszystko co jest opisywaliście w innych tematach i myślę że nie działa to dla tego że już nie mogę więcej farmić
> ![Przechwytywanie](https://user-images.githubusercontent.com/59315705/72972617-11d4c180-3dcc-11ea-8fb2-022b63a10bcd.PNG)

What version of Idle Master Extended are you running?

Are you getting an error log in the install directory?

**Comment by BloodyGoat** [comment]
idle_master_extended_v1.3
Dziennik się nie pokazuje może dla tego że jak na nowo pobrałem to się nie da już zalogować

**Comment by JonasNilson** [comment]
> idle_master_extended_v1.3
> Dziennik się nie pokazuje może dla tego że jak na nowo pobrałem to się nie da już zalogować
> google translator:
> The diary is not displayed now because I have downloaded it again but cannot log in

You could try posting your issue on the forum: https://steamcommunity.com/groups/idlemastery/discussions

**Comment by BloodyGoat** [comment]
Dziękuje już tam byłem będe dalej śledził dziękuje
