### ISSUE TITLE
[Login] I can´t change to another account

### ISSUE THREAD

**Issue by viciousvyper** [JonasNilson/idle_master_extended#253]
I tried to change from my main account to the secondary but it don´t leave me help me please

**Comment by JonasNilson** [comment]
Sounds like you could try and remove all configuration files: https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files

It might use some cached settings.

**Comment by Triberpunk** [comment]
This unfortunately does not resolve the issue for me
I have the same issue as the person who posted this problem

I finished idling on one account  
Logged out of that account - into a new account

Even with the configuration files deleted - when I close + reopen idlemaster - the embedded browser still remembers the creds of the account I previously used - and always keeps logging in with that account

**Comment by JonasNilson** [comment]
@Triberpunk You could try and open your Internet Explorer browser and clearing the cache and cookies.

**Comment by Triberpunk** [comment]
Thanks,
This worked for me

Note that typing a URL into the old internet explorer redirects it to edge now - I was first going to attempt to login to the desired account in the old IE

This may be an undesirable solution if people use other apps that rely on their Internet explorer settings (hopefully no-one ever has to use such a product)

**Comment by anassbenayed** [comment]
Thank you @JonasNilson I used Ccleaner to clear the internet cache and cookies of Microsoft Edge. It worked.

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.
