### ISSUE TITLE
the delay is long

### ISSUE THREAD

**Issue by gynbr** [JonasNilson/idle_master_extended#254]
it looks more like you are using your PC to mine crypto coins than to farm cards, for me it's very suspicious.

**Comment by JonasNilson** [comment]
The delay between card drops is controlled by Steam.

Having Idle Master Extended run crypto mining would damage the reputation pretty quickly and would not last long. Feel free to browse the code and build it yourself with Visual Studio: https://github.com/JonasNilson/idle_master_extended/wiki/Contribute#coding
