### ISSUE TITLE
How to Idle multiple games at once? 

### ISSUE THREAD

**Issue by Timanris** [JonasNilson/idle_master_extended#256]
I need to keep using version 1.5. That one idle 30 games at once. 1.6 and 1.7 are only idling one game. And yes of course I have set fast mode...

![image](https://user-images.githubusercontent.com/95024589/143421852-46ce696b-4f15-4b82-a79d-3286f4e25f99.png)

**Comment by AlexandroLuis** [comment]
It's not a forum, i'ts an issues management , Close it.

**Comment by Timanris** [comment]
Yeah, I see this as an issue...

**Comment by JonasNilson** [comment]
@Timanris Have you tried deleting old configuration files? https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files

It looks like the application reads from an old configuration.

**Comment by kbkk** [comment]
Looks like a bug in initial configuration. On a fresh install I had to switch to "Whitelist mode" and then back to "Fast mode" in order to get it working.

**Comment by Timanris** [comment]
> Looks like a bug in initial configuration. On a fresh install I had to switch to "Whitelist mode" and then back to "Fast mode" in order to get it working.

This one worked, thank you 👍
