### ISSUE TITLE
Idling stops after 6 minutes

### ISSUE THREAD

**Issue by gundogfan** [JonasNilson/idle_master_extended#257]
According to Help > Statistics it says

> This session:
> 6 minutes idled

And it gets stuck there. This happened lots of times, and the only solution I found was restarting Idle Master multiple times. The only time I know it worked is after 7 minutes have passed and it says "7 minutes idled". But this is really annoying since I have to restart up to 10 times for it to work.

Btw, according to main page, Steam is still running and Idle Master is indeed connected to Steam. 
Though this could be another bug, since sometimes it says "Steam is not running", which I don't get, cause I'm using Steam and it works perfectly.

**Comment by JonasNilson** [comment]
@gundogfan I believe the statistics have been bugged for a while. Do you get the correct play time on Steam?

On the subject of Steam not being seen by Idle Master it can be bypassed: https://github.com/JonasNilson/idle_master_extended/issues/45#issuecomment-611694923

The reason for the issue might be the applications running as different users (admin / non-admin)

**Comment by gundogfan** [comment]
> I believe the statistics have been bugged for a while.
Yes but the problem is not the statistic itself, what I mean is when that happens it doesn't idle, it could be "idling" for 2 hours but it won't drop any cards.

> Do you get the correct play time on Steam?
Yes. It does get the correct play time both on Steam and on Idle Master.

**Comment by gundogfan** [comment]
I took a picture of what happens. This time around is 5 minutes, but this happens both at 5 and 6 minutes.
It's stuck there, not idling at all, but time on Steam keeps running.

![image](https://user-images.githubusercontent.com/70611792/149623715-308af141-f933-4eb1-91b1-f5c7b595ed4f.png)

![image](https://user-images.githubusercontent.com/70611792/149623778-a31f0d2b-21a6-4672-b123-8f323a5e6f7d.png)
