### ISSUE TITLE
[Logout] How i logout? 

### ISSUE THREAD

**Issue by Sharpyku** [JonasNilson/idle_master_extended#261]
How i logout? i can't logout, everytime idle master join automatically...  i wanna switch acc..

**Comment by anassbenayed** [comment]
You could try to delete your configuration files, look here: https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files

Or try to clear the internet cache and cookies of Microsoft Edge (this worked for me).

Cheers!

**Comment by AinRuizDorado** [comment]
Already deleted local data and cache and cookies in edge but its not working, when I delete all the date on the browser and try to log in again it log in in my primary account.

**Comment by anassbenayed** [comment]
> Already deleted local data and cache and cookies in edge but its not working, when I delete all the date on the browser and try to log in again it log in in my primary account.

Hi, try this: click ```Windows key + R``` then type: ```%USERPROFILE%\AppData\Local\IdleMasterExtended\``` and press enter. Next delete all contents of this path. You should be able to use a different account now.

**Comment by AinRuizDorado** [comment]
> > Already deleted local data and cache and cookies in edge but its not working, when I delete all the date on the browser and try to log in again it log in in my primary account.
> 
> Hi, try this: click `Windows key + R` then type: `%USERPROFILE%\AppData\Local\IdleMasterExtended\` and press enter. Next delete all contents of this path. You should be able to use a different account now.

I said that I already did it lol, I fixed doing this https://www.youtube.com/watch?v=102LMsgVmto but I need to do this every time that I want to log In in my second account if not my primary account its loged.

**Comment by anassbenayed** [comment]
Gotcha. Not sure why it isn't working for you but I delete the configuration files that contains the session id and the info provided in the video you linked, every time I wish to switch accounts. Works like charm. Cheers.

**Comment by benjjamatteu** [comment]
tengo el mismo problema en este momento, quiero cerrar la cuenta que tengo para poder poner otra, pero cada vez q cierro session y quiero conectarme, me conecta con la misma cuenta. Espero me ayuden porfavor

**Comment by JonasNilson** [comment]
If you still experience these issues you can give the latest release a try: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA
