### ISSUE TITLE
[Browser / Login] i cant log in

### ISSUE THREAD

**Issue by number66621** [JonasNilson/idle_master_extended#262]
so when i am done with my account name password and characters i do everything i cant go down up. and i need to go down to see the rest of it. thats it and also sometimes steam is not running in the top of it is sometimes not working and im on v1.7

**Comment by JonasNilson** [comment]
Can you provide some screenshots of the issues? Potentially some more information.

**Comment by IDou888** [comment]
![image](https://user-images.githubusercontent.com/61679064/150684847-b51de58f-0343-4ef6-ac53-0b448da2fd59.png)
![image](https://user-images.githubusercontent.com/61679064/150685017-2e780a96-7d22-490e-912f-9a570b6ef059.png)
I have the same problem, it says "Please re-enter the characters in the verification code below to verify this is a manual operation."
But there are two problems here:
1. I can't scroll down the page to find the verification code;
2. Although I can scroll down the webpage by pressing the "TAB" key, there is no verification code below (and it is the result after multiple refreshes);

**Comment by di57inct** [comment]
I'm also having problems logging in. The page doesn't seem to work at all for me though. Not 100% sure. I'm on Windows 7 btw.
![image](https://user-images.githubusercontent.com/3608544/151208047-fb19a10d-264c-4905-b041-37493ad26de8.png)

**Comment by dimakempel** [comment]
![image](https://user-images.githubusercontent.com/101765159/158715473-c8834912-bb57-4ca8-9d0a-9e0267c52316.png)
2012 винда тоже не зайти не 1 способом не 2

**Comment by number66621** [comment]
okay i figured it out but on on windows 11

**Comment by JonasNilson** [comment]
@dimakempel This is **off topic** but you should really try to get rid of that `Chrone Browser` (it is a web browsing hijacker):
- https://answers.microsoft.com/en-us/protect/forum/all/a-program-use-to-access-users-pc/dbde017e-470a-4318-b74d-d2ad4cd8b134
- https://sensorstechforum.com/chrone-browser-virus-removal/

**Comment by JonasNilson** [comment]
@di57inct You should get yourself an updated Windows version. It is not safe to run on Windows 7 (support ended in 2020):
- https://www.microsoft.com/en-US/windows/windows-7-end-of-life-support-information

**Comment by JonasNilson** [comment]
> okay i figured it out but on on windows 11

@number66621 What did you have to do on Windows 11 to make it work? I haven't tried running Idle Master Extended on Windows 11 yet.

**Comment by JonasNilson** [comment]
If you still experience these issues you can give the latest release a try: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA

**Comment by JonasNilson** [comment]
The latest release removes the browser window: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

Closing.

**Comment by number66621** [comment]
i deleted the files for it but it was fast there's a youtube video
