### ISSUE TITLE
[Steam status] It says steam is not on when I know and I can see it is on plz can you help me!

### ISSUE THREAD

**Issue by cjdjmej** [JonasNilson/idle_master_extended#263]
Ill be very happy if you could

**Comment by JonasNilson** [comment]
There is a setting to ignore the Steam client status that should help you:

https://github.com/JonasNilson/idle_master_extended/issues/45#issuecomment-611694923

This issue is likely due to running Steam as an administrator and Idle Master Extended as a regular user.

**Comment by MARCK123462** [comment]
alguien sabe porque no me esta idleando lo deje toda la noche y me dio solo 3 cromos nada mas

**Comment by JonasNilson** [comment]
Stale issue. Closing.
