### ISSUE TITLE
Says I no longer have trading cards to take out, even though I recently bought a game with trading cards

### ISSUE THREAD

**Issue by Fancrak27** [JonasNilson/idle_master_extended#264]
As mentioned in the title Idle Master tells me the following
![imagen_2022-01-10_235522](https://user-images.githubusercontent.com/97491769/148873310-bd8797cb-54ea-4eb4-af6a-910e211522a6.png)
It does not make sense, I recently bought a game that had trading cards but I did not load it
![imagen_2022-01-10_235949](https://user-images.githubusercontent.com/97491769/148873733-5a8123f8-7ea1-48e4-a2d7-1b40f64511b2.png)

**Comment by JonasNilson** [comment]
What's the status on your badge page for that specific game?

For example:
* ![image](https://user-images.githubusercontent.com/5990550/148908450-217ae2c0-0bf7-401f-8cbb-aedec486fd8f.png)

More info: https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

**Comment by Fancrak27** [comment]
Oh, Thank you

**Comment by JonasNilson** [comment]
Duplicates:
* https://github.com/JonasNilson/idle_master_extended/issues/180
* https://github.com/JonasNilson/idle_master_extended/issues/177
* https://github.com/JonasNilson/idle_master_extended/issues/157
(and probably more further back in history)
