### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by paulomanrique** [JonasNilson/idle_master_extended#27]
After I put my password, the screen for putting the code doesn't appear and it backs to the main window.

**Comment by Cass18** [comment]
Same here! If you are able to fix it, pls tell me. TY!

**Comment by JonasNilson** [comment]
> After I put my password, the screen for putting the code doesn't appear and it backs to the main window.

> Same here! If you are able to fix it, pls tell me. TY!

I did a quick debugging session and it looks like Steam has changed the way the login redirects / opens the Authentication code window. I'm not sure how to handle it at the moment.'

This is where the code fails to handle the new way Steam logins:
* https://github.com/JonasNilson/idle_master_extended/blob/develop/Source/IdleMaster/frmBrowser.cs#L75
* https://github.com/JonasNilson/idle_master_extended/blob/develop/Source/IdleMaster/frmBrowser.cs#L112

---
One quick way to make it work without going through the login process is to extract the cookie data you have on the Steam webpage and paste it into Idle Master (steamParental is not needed):
![image](https://user-images.githubusercontent.com/5990550/72971767-8c9cdd00-3dca-11ea-80ba-00904920c4b1.png)

**Comment by ArcticFoxen** [comment]
how can i use these methots, i dont know anything about programming etc. i am just reguler user this program was the perfect one in the market for me and I would like to run it again

**Comment by JonasNilson** [comment]
@ArcticFoxen 

You can use this method: https://superuser.com/a/1114501

Or get a cookie inspection extension for your web browser:
- https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en

**Comment by ArcticFoxen** [comment]
even if i get cookie, how can i paste on the idle master, like i said I don't know anything :=)

**Comment by JonasNilson** [comment]
@ArcticFoxen 

I'm sorry. Basically you paste it in under Idle Master Settings > (press the lock symbol) > enter the two top cookies

Never post your cookies anywhere

**Comment by ArcticFoxen** [comment]
I understand very well what you mean right now, I'm at the last stage, I installed the chrome plugin, which one should I paste from here in to the idle master login window 

screen from the chrome plugin 
![image](https://user-images.githubusercontent.com/54692308/73080345-bba07500-3ed6-11ea-94d4-88e1dc3646c0.png)

**Comment by JonasNilson** [comment]
@ArcticFoxen 

sessionid 

and

steamLoginSecure

**Comment by ArcticFoxen** [comment]
@JonasNilson thank you to everyone who has worked here, idle master working again now

**Comment by wolfdizz** [comment]
@JonasNilson thanks dude a lot <3

**Comment by javelin5150** [comment]
> @ArcticFoxen
> 
> sessionid
> 
> and
> 
> steamLoginSecure

that doesn't work for me.

**Comment by ArcticFoxen** [comment]
> > @ArcticFoxen
> > sessionid
> > and
> > steamLoginSecure
> 
> that doesn't work for me.
> 
> EDIT: This time it says that "the data isn't valid" but shows me that I'm signed in, however, that didn't help me at all.

its says the data isn't valid yes but still working for me i dont know

**Comment by Fusl** [comment]
Using steamLoginSecure worked once, but after restarting IME, this no longer works and it just keeps telling me that the info isn't valid.

**Comment by javelin5150** [comment]
> Using steamLoginSecure worked once, but after restarting IME, this no longer works and it just keeps telling me that the info isn't valid.

We just have to wait for the dev to release a new build.

**Comment by JonasNilson** [comment]
@paulomanrique @Cass18 @ArcticFoxen @wolfdizz 

I have updated the login to go through the Steam JavaScript API that connects to the running Steam client, which avoid having you to enter credentials.

Can you check out the latest release and give it a test? https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.4

**Comment by javelin5150** [comment]
> @paulomanrique @Cass18 @ArcticFoxen @wolfdizz
> 
> I have updated the login to go through the Steam JavaScript API that connects to the running Steam client, which avoid having you to enter credentials.
> 
> Can you check out the latest release and give it a test? https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.4

Thanks for the quick fix. It worked fine for me (it didn't request for my username/password, it checked if I was logged in on my steam). However, I can't idle any of my games. How can I fix that?

**Comment by JonasNilson** [comment]
@javelin5150 

Do you get any indication on idle master reading your badge page?

**Comment by javelin5150** [comment]
> @javelin5150
> 
> Do you get any indication on idle master reading your badge page?

Wanted to screenshot idlemaster, but I can't login for some reason. I'll try again later.

**Comment by JonasNilson** [comment]
> > @javelin5150
> > Do you get any indication on idle master reading your badge page?
> 
> Wanted to screenshot idlemaster, but I can't login for some reason. I'll try again later.

Is logging in still an issue?

Also, make sure you have games that can give card drops by looking at your badge page: https://steamcommunity.com/id/<your-steam-id>/badges/

**Comment by blazeb** [comment]
I don't know if anyone else is having this issue, but every time I try to sign-in the window automatically closes in about 5 seconds.

**Comment by JonasNilson** [comment]
@blazeb 

Do you have quick login active in your settings?

**Comment by blazeb** [comment]
yes it was active and I just unchecked it and that seemed to work
Thank you! : )

**Comment by hydroculator** [comment]
I am having the disappearing login screen issue as well.   
I've looked for a "quick login" check, I found "allow web pages to auto login". If that's the right one, toggling back and forth didn't make a difference either way.
It also never seems to know if Steam is running, either. "Ignore client status" doesn't affect the login issue, either.  
I've looked in the log file, and all it has is a list of dll files.

**Comment by blazeb** [comment]
@hydroculator it should be in file>settings>and near the top-right corner say quick login

**Comment by pr0d1gx** [comment]
no me figura opcion de inicio de sesion rapido 
 y tampoco me deja iniciar sesion, la pantalla de inicio no carga mas

**Comment by veke12** [comment]
Removing quick login worked for me. ( u have to manually put ur password and user name in the thing)

**Comment by hydroculator** [comment]
@blazeb   
   
Thank you, this worked!

**Comment by javelin5150** [comment]
> > > @javelin5150
> > > Do you get any indication on idle master reading your badge page?
> > 
> > 
> > Wanted to screenshot idlemaster, but I can't login for some reason. I'll try again later.
> 
> Is logging in still an issue?
> 
> Also, make sure you have games that can give card drops by looking at your badge page: https://steamcommunity.com/id/your-steam-id/badges/

I am no longer facing login issues, however, I can't idle any games. It just says "idling complete".

**Comment by JonasNilson** [comment]
@javelin5150
> I am no longer facing login issues, however, I can't idle any games. It just says "idling complete".

Is this still an issue?

@hydroculator @veke12 @blazeb 

Can you try out the latest release, 1.4-final? I addressed an issue related to the closing window

**Comment by javelin5150** [comment]
> @javelin5150
> 
> > I am no longer facing login issues, however, I can't idle any games. It just says "idling complete".
> 
> Is this still an issue?
> 
> @hydroculator @veke12 @blazeb
> 
> Can you try out the latest release, 1.4-final? I addressed an issue related to the closing window

Couldn't idle games.

**Comment by JonasNilson** [comment]
@javelin5150 

How many games do you still have card drops available for?

Check under http://steamcommunity.com/my/badges

**Comment by javelin5150** [comment]
> @javelin5150
> 
> How many games do you still have card drops available for?
> 
> Check under http://steamcommunity.com/my/badges

3

**Comment by DumbJoe** [comment]
The 1.4 final version here: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.4-final doesn't show the window to enter in your steam guard code....

**Comment by Jules1816** [comment]
Same issue. Using credentials won't work, pressing the log in button does nothing, even tried a wrong password just to see if I got an error message, but didn't. Using cookies does not work either, whenever I save them I get an error saying they're not valid (I've read that's normal), but nothing happens; even tried modifying the configs file to manually save them there, but it's no use.
