### ISSUE TITLE
uygulama sadece saat kazandırıyor kart düşmüyor

### ISSUE THREAD

**Issue by zubahub** [JonasNilson/idle_master_extended#270]
uygulama sadece saat kazandırıyor kart düşmüyor

**Comment by zubahub** [comment]
the application only saves hours, the card does not drop

**Comment by zubahub** [comment]
![idle master](https://user-images.githubusercontent.com/98759790/151889006-e08375f4-e5b0-46fc-8e2e-f5d36fb7cdfb.PNG)

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/issues/274

Closing duplicate
