### ISSUE TITLE
[Settings] Can't change language

### ISSUE THREAD

**Issue by Der-Floh** [JonasNilson/idle_master_extended#272]
I can't change the language. As you see here english is selected but the language is still in german after I restarted.

![grafik](https://user-images.githubusercontent.com/65826571/151926204-45b6dbf8-12ad-4436-8d38-a0b98ffcd27a.png)

**Comment by DerrFloh** [comment]
Reason for that was cause I started the application through the windows start menu. Read [this](https://github.com/JonasNilson/idle_master_extended/issues/271) if you want more info
