### ISSUE TITLE
[Playtime / Cards] Not Farming

### ISSUE THREAD

**Issue by zubahub** [JonasNilson/idle_master_extended#274]
### [Bug] Not Farming:The app only gives the time. It doesn't earn cards
![idle](https://user-images.githubusercontent.com/98759790/152171243-6fc6912d-7e42-48b5-aae3-d09643c92335.PNG)
.

**Comment by DerrFloh** [comment]
If you look in steam are the games running?

**Comment by zubahub** [comment]
![stam](https://user-images.githubusercontent.com/98759790/152236348-0c108c86-2318-4212-9d87-732532c91cee.PNG)
I think I gave it too much time.

**Comment by benjjamatteu** [comment]
me esta pasando lo mismo bro

**Comment by HYBRID-BEING** [comment]
Just to cross off the possibility, this happened to me when i launched Steam client, and forgot to actually log in in it. Logged in, clicked "Update game status", and IME started idling.
Technically, Steam is running, so IME thinks there is no problem, but, if possible, this should be detected as well.

**Comment by JonasNilson** [comment]
> ![stam](https://user-images.githubusercontent.com/98759790/152236348-0c108c86-2318-4212-9d87-732532c91cee.PNG)
> I think I gave it too much time.

Are you still experiencing this issue?

The amount of hours registered on Steam seem way above normal. If you don't get the card drops you have available on your Steam Badge page you should probably get in contact with Steam Support.

**Comment by gundogfan** [comment]
This happens to me too. As I mentioned before, I don't know if it has something to do or not but most of the times (not always) when this happens it gets stuck at 5 or 6 minutes of idling (according to "statistics" tab). And, IDK if this has something to do with it but I notice that everytime I open a non-steam version of Half-Life (which is cracked from Steam version) it stops working. Could it have something to do with this or RegEdit perhaps?
