### ISSUE TITLE
[Question] is idle master still works? and is it safe?

### ISSUE THREAD

**Issue by Yousif-N3** [JonasNilson/idle_master_extended#278]
as the title says.

thanks in advance

**Comment by JonasNilson** [comment]
The application worked the last time I tried it. No updates have been published in some time though and there are some known issues.

The safety of the app is mainly depending on the user. The only remote connection will be made to the Steam website to find what games you still have cards to gain from.

For some reason unknown to me the zip archive has been marked as suspicious by a few anti-virus softwares: https://www.virustotal.com/gui/file/5c0c8cace246d8fc67fcc413da5d30e9e875a798e385552e8a46a0deb42badbc/detection

The Idle Master Extended project is fully open source so you can download / clone this repository and run or debug it in Visual Studio to verify the program safety.
