### ISSUE TITLE
Interface don't load correctly

### ISSUE THREAD

**Issue by PAJ4R0** [JonasNilson/idle_master_extended#280]
I can't log with my account becouse de Log In HUD is corrputed, any help?? I can leave an image here, sorry, is in spanish, im from Argentina.
![Screenshot_445](https://user-images.githubusercontent.com/73671050/159110362-b155c8ad-e80a-4706-ab7d-4f6cdbcbf2a3.png)

**Comment by Soumyadeep98O** [comment]
It seems like Internet connection issue…!

**Comment by JonasNilson** [comment]
Related: #128

**Comment by JonasNilson** [comment]
The browser window is no longer a part of Idle Master Extended: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

**Comment by PAJ4R0** [comment]
> The browser window is no longer a part of Idle Master Extended: https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8.0

It Works! Thank you men. Blessings.
