### ISSUE TITLE
[Idling] no farm

### ISSUE THREAD

**Issue by manu1634** [JonasNilson/idle_master_extended#284]
I've been farming for almost 1 day and it only counts as 3 hours and this prevents me from farming cards

**Comment by JonasNilson** [comment]
Are you able to provide more information regarding this issue?

1. Was Steam running during the idling process? It sounds like Steam stopped caring about the running game processes.
2. What Settings do you have enabled / disabled in Idle Master Extended? (Provide a screenshot if that makes it easier)
3. What games were you idling?
4. (Potentially some more info if you have it)
