### ISSUE TITLE
[Steam status] I am not getting any card drops.

### ISSUE THREAD

**Issue by Reto1n** [JonasNilson/idle_master_extended#286]
In my idle master it shows "Steam is not running" but my steam is open and I loaded games and it also doesn't shows how many card drops are available
![Screenshot (31)](https://user-images.githubusercontent.com/104818223/166410960-7691d2e6-411f-42b3-9342-47d8fb937f8a.png)

**Comment by JonasNilson** [comment]
This can happen if you run Steam and Idle Master Extended under different users (for example if you run Steam as Administrator and IME as your regular user). 

Solutions can be found here: https://github.com/JonasNilson/idle_master_extended/wiki/Steam-is-not-running
