### ISSUE TITLE
[Login/Logout] Autologin on steam

### ISSUE THREAD

**Issue by squckly** [JonasNilson/idle_master_extended#287]
I set autologin on steam to on and still as I click to log me out and log in again because I want to log in to another account, it automatically logs me in to the previous account where I clicked to automatically log me in, and now I do not want to change it?

**Comment by JonasNilson** [comment]
Sorry for the later reply. You could try the newly released v1.8-BETA (https://github.com/JonasNilson/idle_master_extended/releases/tag/v1.8-BETA) and see if that fixes your issue. 

It contains a fix that should be relevant: https://github.com/JonasNilson/idle_master_extended/pull/281
