### ISSUE TITLE
[Application] Interface broken

### ISSUE THREAD

**Issue by Muqa1** [JonasNilson/idle_master_extended#289]
i have used the v1.5 for a long time but it didnt work anymore so i downloaded the 1.7 but the interface is broken, i cant click anything

![image](https://user-images.githubusercontent.com/106272829/170338501-5a94e758-8163-4927-b540-7eae75e23b5b.png)

**Comment by JonDVstRm** [comment]
hmm, strange, I think somebody post a really quick solution for this , because I havent been using Idle Master for a long time, today, I downloaded latest version and everything runs fine (I only turn off quick login, dont know what does it do, but I can not login with this option enabled)

**Comment by JonasNilson** [comment]
It looks like you are running the executable in a state where it can't read the necessary files. For example, this could happen if you run the executable from within the ZIP-file. 

Please follow the steps required to extract the application properly: https://github.com/JonasNilson/idle_master_extended/wiki/Get-started

**Comment by Muqa1** [comment]
no i have everything in the folder, but still the program is broken. I have a error log too.
[error.log](https://github.com/JonasNilson/idle_master_extended/files/8837817/error.log)

**Comment by JonasNilson** [comment]
Looks like you can benefit from cleaning out your configurations: https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files

Based on this in your error log:
```log
25.05.2022 21:17:20   
System.Configuration.ConfigurationErrorsException: Configuration system failed to initialize 
---> System.Configuration.ConfigurationErrorsException: '.', hexadecimal value 0x00, is an invalid character. Line 14, position 1. 
(C:\Users\Admin\AppData\Local\IdleMasterExtended\IdleMasterExtended.exe_Url_aawybaaxvu5npuhkea0fmitmrp2drhnt\1.7.0.0\user.config line 14) 
---> System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 14, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
```
