### ISSUE TITLE
[Browser / Login] Login tab gets stuck.

### ISSUE THREAD

**Issue by HandBurgerb** [JonasNilson/idle_master_extended#290]
When trying to login, I enter my information, however this tab gets stuck on this message:
**_'Idle Master is saving your information'_**

Eventually that tab closes but it still says that **_'Idle Master is not connected to Steam'_**

## To Reproduce ##
1. Open the program
2. Enter login credentials for Steam
3. Program gets stuck on _**'Idle Master is saving your information'**_

## Expected behavior ##
For it to login.

## Screenshots ##
![image](https://user-images.githubusercontent.com/72711945/170876665-90d91a3c-44d6-49ad-ab43-0b7dc584029d.png)

## Comments ##
Thank you in advance!

**Comment by peraperkan** [comment]
Same here. I cleared cash from Microsoft edge since I don't have explorer on my pc, I restarted my pc and deleted and downloaded again the app and still the issue is present. I thin its a steam problem since I used the app this afternoon and it was fine but when I tried to login into my second account I got this problem.

**Comment by bertek41** [comment]
This happened to a friend of mine. It was fixed after activating Mobile Steam Guard.

**Comment by TheWind32** [comment]
I am encountering the same issue, and I cannot activate mobile auth due to circumstances, nor can I revert to 1.7 since issue #287 takes place on that version. Is there anything I can do?

**Comment by boybrushdred** [comment]
same issue here. I can use 1.7 but it auto logs in a different user whenever I click "sign in", and seems there is no way to log them out.

**Comment by ciufix** [comment]
Run as administrator and it will not get stuck anymore

**Comment by boybrushdred** [comment]
Looks like it doesn't work for accounts without mobile authenticator. My account without mobile authenticator gets stuck. But other user account with mobile authenticator enabled can log in no problem.

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/releases
