### ISSUE TITLE
[BUG] <internet Explorer >

### ISSUE THREAD

**Issue by incesamet27** [JonasNilson/idle_master_extended#292]
## Describe the bug ##

internet explorer, no longer able to login to steam, please I want you to solve this issue

**Comment by KillerSage-tech** [comment]
it keeps looping saying "idle master is saving your information"

**Comment by JonasNilson** [comment]
Is this issue the same as : https://github.com/JonasNilson/idle_master_extended/issues/290 ?

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/releases - the browser is no longer a part of Idle Master Extended
