### ISSUE TITLE
Why doesn't the program farm cards in free card games?

### ISSUE THREAD

**Issue by SuperAtom777** [JonasNilson/idle_master_extended#294]

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

Free games typically don't give you any cards unless you spend money in-game.

There are two exceptions I know of: Grimm and The Descendants https://github.com/JonasNilson/idle_master_extended/wiki/Tips-and-tricks
