### ISSUE TITLE
Trojan!

### ISSUE THREAD

**Issue by naabdi** [JonasNilson/idle_master_extended#295]
Hi
when I downloaded and try to extract it, the windows defender identifies  it as a severe trojan!

**Comment by JonasNilson** [comment]
Can you provide more information about what version you are using and where you downloaded the executable?

**Comment by naabdi** [comment]
> 
The last beta 1.8v this link
https://github.com/JonasNilson/idle_master_extended/releases/download/v1.8-BETA/idle_master_extended_v1.8-BETA.zip

**Comment by JonasNilson** [comment]
Interesting. Do you have a screenshot of the warning message?

I have not experienced or seen that warning myself.

**Comment by naabdi** [comment]
> 

![image](https://user-images.githubusercontent.com/29688405/172120268-33ae9016-ea1b-41dd-8214-f93aa2db509a.png)

**Comment by JonasNilson** [comment]
From the looks of it this is a false positive. I will have to investigate further if I can change the behavior of the executable to avoid being flagged.

I suspect It's either the way it creates extra executables (`steam-idle.exe`) or the dll (`steam_api.dll`) that I omitted from the beta release ZIP-file.

Thank you for reporting 👍🏻

**Comment by gOOvER** [comment]
Virus Total also show a Trojan:

https://www.virustotal.com/gui/file/5206ce18261b513dd1d8221183f8f875e1006cffbc5e9325b9874243a637387a

Eset give no Warning
