### ISSUE TITLE
games not avaliable to idle

### ISSUE THREAD

**Issue by azzerzzzeqwe** [JonasNilson/idle_master_extended#297]
i have over 20 games that have cards available to earn. but its only recognizing one game. i have earned dozens of cards on my own from different games, but its saying that only 1 is available to get cards from

**Comment by JonasNilson** [comment]
Make sure you are eligible for more card drops: https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete#make-sure-you-are-eligible-for-card-drops

The application scans your badge page, and if there are no more cards to be gained the game will be ignored
