### ISSUE TITLE
Linux Arch steam idle_master_extended

### ISSUE THREAD

**Issue by marekkloc1** [JonasNilson/idle_master_extended#298]
Hello, does anyone know how to setup this idle_master_extended in linux Arch? I know there's tutorial on Youtube with Linux but that is for ubuntu and i am on now currently linux Arch, I want to know how to setup because in this video there's command to **_sudo apt-get install python-bs4 python-requests python-pil.imagetk python-colorama -y && sudo apt-get update_** this command is from ubuntu and i need to convert it into the Arch command and i don't how, i was trying it but terminal says it doesn't exist the package. In the instructions what is in the ZIP file is quite inaccurate although there is a command for Arch but it is not at all complete and there are only package names, although I found the packages, but only through pamac. And when I downloaded them through the pamac, idle_master_extended doesn't want to start, it just wants the original files from the command I wrote here and it's only for ubuntu.

Also wanted to ask if it is possible to idle for just one game? I know there's a blacklist so I'll try that one out later.
Maybe it would be better if there could be a new tutorial on how to install it but only through the Arch.

**Comment by franchioping** [comment]
usually u can just search "<package name in ubuntu> arch" on google and it will show up
for you the command is: **sudo pacman -S python-beautifulsoup4 python-requests python-pillow python-colorama**
you can also search for packages from here: https://archlinux.org/packages/

**Comment by franchioping** [comment]
nvm, the packages are **python2-beautifulsoup4 python2-requests python2-pillow tk python2-coloram**
btw, the linux version is depracated (no longer maintained) and is here: https://github.com/jshackles/idle_master_py/

**Comment by franchioping** [comment]
I am once again wrong. arch has depracated python2, so those packages are no longer available

**Comment by marekkloc1** [comment]
> usually u can just search " arch" on google and it will show up for you the command is: **sudo pacman -S python-beautifulsoup4 python-requests python-pillow python-colorama** you can also search for packages from here: https://archlinux.org/packages/

This one commands works fine.

**Comment by marekkloc1** [comment]
> nvm, the packages are **python2-beautifulsoup4 python2-requests python2-pillow tk python2-coloram** btw, the linux version is depracated (no longer maintained) and is here: https://github.com/jshackles/idle_master_py/

Sadly, they don't work, terminal says that not found.
Is there Idle master extended with executable file that i can run throught the xTerm?
