### ISSUE TITLE
[BUG] Games are not being detected 

### ISSUE THREAD

**Issue by Matespi90** [JonasNilson/idle_master_extended#303]
I have 16 games that i want to idle but the app only detect 2 of them, the only solution ive found is putting them on the whitelist but whitelist isnt the most efficent option, i want to idle with the fast mode. And i tried to use the version 1.8 but it doesnt connect with steam.

**Comment by R4m0n74** [comment]
Hello, were you able to solve it somehow? I have the same error

**Comment by JonasNilson** [comment]
Sounds like you have received the cards you eligible for: https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete#make-sure-you-are-eligible-for-card-drops
