### ISSUE TITLE
[Badges] idle master dont detecting games

### ISSUE THREAD

**Issue by Emincanklc** [JonasNilson/idle_master_extended#304]
![image](https://user-images.githubusercontent.com/108239387/175832992-e8361e86-e6eb-4651-9d0d-972c9e93de60.png)
i have games to get trading card but im dont detecting help

**Comment by R4m0n74** [comment]
Hello, were you able to solve it somehow? I have the same error

**Comment by JonasNilson** [comment]
Looks like you are not eligible for more card drops on certain games: https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

That is not an Idle Master Extended issue.
