### ISSUE TITLE
[Idling] idle master next check not showing

### ISSUE THREAD

**Issue by parsifen** [JonasNilson/idle_master_extended#305]
guys can u help me please?
idle master next check not showing. After 5 minutes in fast mode, idle master freezes and nothing happens. It stays like this:
when i did folder>settings>whitelist mode and again when i did fast mode, card dropping. please help this issue.
![image](https://user-images.githubusercontent.com/108241855/175836085-a29c5ae8-5b08-4270-8aef-f563555409fd.png)

**Comment by parsifen** [comment]
![image](https://user-images.githubusercontent.com/108241855/175836155-23084de9-10e6-41c1-82bd-b7c052b35919.png)
and my settings like this.

**Comment by alirezaskyfall** [comment]
same here, it stops idling game after 3min then the timer will be stuck after that
tried v 1.7 and 1.8 both have the same problem

**Comment by sparkydot123** [comment]
same here but I figured a way i guess 
you could try idle games with more than 2 games individually, then simultaneously option 
![image](https://user-images.githubusercontent.com/108324009/176110659-a806042a-ccac-4e50-a9f6-303ecded5688.png)
its not the best but it seems working now

**Comment by JonasNilson** [comment]
Is this still an issue? I have not managed to reproduce it myself.
