### ISSUE TITLE
[BUG] I didnt get any cards after a few hours

### ISSUE THREAD

**Issue by Alfianakml** [JonasNilson/idle_master_extended#306]
I was using IME since a week ago everything was fine until now its not drop any cards anymore but it still says 26 cards drop remaining

![image](https://user-images.githubusercontent.com/91175540/175941076-901ca3b9-afb8-4832-83cd-1b0e8b86a8d1.png)

any solutions?

**Comment by Flaire2k** [comment]
Man its not a bug, its normal, cards dropping after 2+ hours, i got all cards from games after 6 hours so yeah, its not a bug
![image](https://user-images.githubusercontent.com/108733468/177316736-3d36282b-641c-4db7-894d-8d046ee67fda.png)
