### ISSUE TITLE
[BUG] Sign in button doesn't work

### ISSUE THREAD

**Issue by Siimuke5** [JonasNilson/idle_master_extended#307]
![Screenshot_1](https://user-images.githubusercontent.com/87310470/176385303-124b230a-dc45-41a3-ac96-c64485078a86.png)

---

ALTERNATIVE SOLUTION (cookie login): https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#cookies

**Comment by freurat** [comment]
same problem

**Comment by b1naryTR** [comment]
Here is the error file I got:

29.06.2022 13:22:20   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/x
System.Exception: Response is null or empty. Added (+1) to RetryCount
   konum: IdleMasterExtended.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   konum: IdleMasterExtended.frmMain.<GetBadgePageAsync>d__25.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: IdleMasterExtended.frmMain.<LoadBadgesAsync>d__24.MoveNext()

**Comment by FlentinViolet** [comment]
Yeah my sign in button doesn't works too.

**Comment by AcerLejyoner** [comment]
Login button not working.

**Comment by kirill0ermakov** [comment]
Same problem too

**Comment by bertek41** [comment]
For those who are experiencing this issue you can login with cookies:
https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#cookies

**Comment by DanGamingBlue** [comment]
> For those who are experiencing this issue you can login with cookies: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#cookies

tysm

**Comment by FlentinViolet** [comment]
I tried cookie way and it worked. Thanks so much for informations.

**Comment by amidstacy** [comment]
> For those who are experiencing this issue you can login with cookies: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#cookies

Thank you. It worked. Still needs to fix the sign in issue though.

**Comment by Romz24** [comment]
Doesn't work for me either

**Comment by ShizouOrihasi** [comment]
FIX 100% Functional     https://www.youtube.com/watch?v=Qn60ACpzDR8

**Comment by FLUFIK12** [comment]
It doesn't work for me either

**Comment by AnzhiZhang** [comment]
Log in with cookie works for me, please remember to use `store.steampowered.com` instad of `steamcommunity.com`.

**Comment by JonasNilson** [comment]
@AnzhiZhang I don't think that's necessary. I just tried with `steamcommunity.com` cookies:
- ![image](https://user-images.githubusercontent.com/5990550/177044062-0e4034b9-bb0f-4649-83c8-d47721d387e9.png)
- ![image](https://user-images.githubusercontent.com/5990550/177044089-4e6a4df9-39c9-45df-a18c-11c753e4607a.png)

**Comment by JonasNilson** [comment]
From what I've managed to research myself Valve has dropped support for Internet Explorer based browsers (reasonable).

The built in web browser in C# with .NET Framework 4.8 uses the same browser components as IE (probably just starts IE embedded in a Form).

Browsing with Microsoft Edge to the Steam Community login page and trying to activate Internet Explorer mode is not enabled:
- ![image](https://user-images.githubusercontent.com/5990550/177044295-49ff70c0-3919-4924-8190-79259d9b696f.png)

**Comment by AnzhiZhang** [comment]
> @AnzhiZhang I don't think that's necessary. I just tried with `steamcommunity.com` cookies:

They both work bot `steamcommunity `does not workds for me might caused by my cookies on `steamcommunity` was expired. 

Anyway, login with cookie is works.

**Comment by gumutb** [comment]
I am not expert but I guess if the program lets us to go factory setting it would be new software like first day that we just install. I don't know where it keeps the login settings but it thought  it is already logged in and cant try more.

**Comment by Dragontown6** [comment]
Cookie method doesn't work for me still, says data you've entered isn't valid.

**Comment by JonasNilson** [comment]
> Cookie method doesn't work for me still, says data you've entered isn't valid.

@Dragontown6  - This might help: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#troubleshooting-cookies

**Comment by JonasNilson** [comment]
> I am not expert but I guess if the program let us to go factory setting it will be new software like first day that we just install. I don't know where it keeps the login settings but it thought it is already logged in and cant try more.

@gumutb - This might help: https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files

**Comment by JonasNilson** [comment]
In the latest release (v1.8.0) the browser window have been replaced by the cookie settings window to avoid confusion where the browser login button does not work.

https://github.com/JonasNilson/idle_master_extended/releases
