### ISSUE TITLE
[BUG] Sign in button 100% FIX PT BR 

### ISSUE THREAD

**Issue by ShizouOrihasi** [JonasNilson/idle_master_extended#309]
FIX 100% Functional     https://www.youtube.com/watch?v=Qn60ACpzDR8 

Video 2020 (2022) 100% FIX

**Comment by etson32** [comment]
Obrigado muito fácil.

**Comment by FLUFIK12** [comment]
doesn't work

**Comment by JonasNilson** [comment]
Basically a duplicate of: https://github.com/JonasNilson/idle_master_extended/issues/310
