### ISSUE TITLE
Nothing happens after autmatic login?

### ISSUE THREAD

**Issue by Entharia** [JonasNilson/idle_master_extended#31]
i rly dont know why its like that, the other day it worked fine now it looks like this and seems like it does nothing?
![Unbenannt](https://user-images.githubusercontent.com/59421695/73752392-34b68c80-4761-11ea-942d-b047a435a5dd.PNG)

**Comment by JonasNilson** [comment]
@Entharia I'll give it a go later tonight to see if I can reproduce it.

**Comment by JonasNilson** [comment]
@Entharia 

Are you still experiencing this?

It seems to work fine on my end.

![image](https://user-images.githubusercontent.com/5990550/73877468-fdc3a200-4858-11ea-91fd-ee46cdd4d399.png)

**Comment by JonasNilson** [comment]
> i rly dont know why its like that, the other day it worked fine now it looks like this and seems like it does nothing?

Is this still an issue?

**Comment by Entharia** [comment]
Sorry for the late reply.
Yes, I still have that issue.
I deleted the folder and redownloaded it just now, it didn't help.
But I just found something in the error.log 
`21.02.2020 15:34:24   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/"MyNumber"
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmMain.ProcessBadgesOnPage(HtmlDocument document)
   at IdleMaster.frmMain.<LoadBadgesAsync>d__36.MoveNext()
`

**Comment by JonasNilson** [comment]
@Entharia

I haven't found the cause of this yet. 

How many games have you got available for card drops?

**Comment by DumbJoe** [comment]
28/03/2020 6:36:09 PM   
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Member 'System.DBNull.Value' cannot be accessed with an instance reference; qualify it with a type name instead
   at CallSite.Target(Closure , CallSite , Object , String )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at CallSite.Target(Closure , CallSite , Object , String )
   at IdleMaster.frmBrowser.setLoginButtonText(Object htmldoc, String text)
   at IdleMaster.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by tduarte21** [comment]
I'm also having the same problem!

**Comment by julian28300** [comment]
I also have this problem where the quick login does nothing

**Comment by zomodo97** [comment]
Im also having a problem where the quick login does nothing. It worked before but it only tracked one game when I had many other games that has trading cards

**Comment by JonasNilson** [comment]
@zomodo97 @julian28300 @tduarte21 @DumbJoe @Entharia 

If you are still experiencing this issue, please try the latest release and get back to me in a separate issue if it is still something that's broken:
* https://github.com/JonasNilson/idle_master_extended/releases

**Comment by Legend-117** [comment]
I have the same issue even in the latest release i don't know what to do if anybody can help.

**Comment by DumbJoe** [comment]
Thanks JonasNilson, I've come back to this issue and I see you've updated to 1.5. The quick login is optional(well actually it was enforced by default preventing me from being able to login as it would keep refreshing and my typing speed was too slow to type in both password and username before quicklogin does its thing in under a second), which is nice - however it doesn't seem to ask for steamguard code which is why it's not logging me in. Can you fix this please?
