### ISSUE TITLE
[BUG] [Sign in button 100% FIX] - Steam idle master oturum açma sorunu (ÇÖZÜM)

### ISSUE THREAD

**Issue by Markol5** [JonasNilson/idle_master_extended#310]
# Idle Master Extended Wiki: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#cookies

---

FIX 100% Video : https://www.youtube.com/watch?v=DcBtXXAfm6Q

Video 2020 (2022)

---

**Comment by Markol5** [comment]
Herhangi bir sorun yaşayan arkadaş varsa discordan ulaşabilir
Markol#0946

**Comment by hamnett** [comment]
> 

work thx

**Comment by Mystro69** [comment]
@Markol5 bu attığın video bir fix değil başka bir giriş yapma yöntemi zaten bu yöntem readme'de gösteriliyor lütfen issues kısmını düzgün kullan

**Comment by DryreL** [comment]
Teşekkürler ama attığın video pek açıklayıcı değildi.
Videoyu izleyip yapamayan arkadaşlar [buradan](https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#cookies) çözüme daha net bakabilir.
