### ISSUE TITLE
[BUG] <Not finding my games>

### ISSUE THREAD

**Issue by HappierAsh96** [JonasNilson/idle_master_extended#313]
I have a lot of games on steam such as Terraria,CS GO,PayDay2,Human Fall Flat,Zup Z,Brawlhalla but Idle Master Extended only recognizes Human Fall Flat and Zup Z,any help?

**Comment by hamnett** [comment]
You already drop all the card from those game ?

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

You probably have received the card drops you are eligible for
