### ISSUE TITLE
Almost no keys are working

### ISSUE THREAD

**Issue by poownn** [JonasNilson/idle_master_extended#318]
Almost no keys are working(sign in, settings etc.).
![image](https://user-images.githubusercontent.com/101294622/177578021-97723cfe-1d2d-4edf-aadb-ec8bc2554346.png)
So i cant solve it via cookie way.

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Get-started

Looks like you haven't extracted the ZIP archive properly

**Comment by poownn** [comment]
I extracted dozens of times.

**Comment by poownn** [comment]
How can't i extracted properly, it's very simple.

**Comment by JonasNilson** [comment]
Can you provide a screenshot of the directory you are running the Idle Master Extended executable from? 

It looks like it's not starting properly for some reason.

Do you get an error log?

**Comment by poownn** [comment]
C:\Users\demir\Downloads\idle_master_extended_v1.7
[error.log](https://github.com/JonasNilson/idle_master_extended/files/9056048/error.log)

**Comment by JonasNilson** [comment]
Looks like something is up with the configuration file:

`C:\Users\demir\AppData\Local\Temp\Rar$EXa19052.26218\idle_master_extended_v1.7\IdleMasterExtended.exe.config` line 108

**Comment by poownn** [comment]
What should i do?

**Comment by JonasNilson** [comment]
I have never seen this issue before so I can't tell right now.

**Comment by poownn** [comment]
- [ ]

**Comment by poownn** [comment]
I did a system restore and fixed the problem. I don't know why but i guess there was a virus or something or some windows files were corrupted.
