### ISSUE TITLE
Shutdown after complete turns off entire computer?

### ISSUE THREAD

**Issue by DrWhoCares** [JonasNilson/idle_master_extended#32]
Am I right in understanding this feature? Because my entire computer just shutdown after giving me a warning saying it was going to shut down in less than a minute, coinciding with the time that Idle Master was completing.
I've never seen a message like this, nor was it anything related to Windows Update or any scheduled task.

Why would it shut down my entire computer? Why would I ever want that?

**Comment by JonasNilson** [comment]
It's supposed to shut down your computer when idling is done.

It was requested and added in #8

**Comment by DrWhoCares** [comment]
It should be made clear what it does then.
A warning pop-up after clicking it, asking to confirm that you want to shutdown your entire computer when it's done, or at the very least, change the label to "shutdown computer" instead of just "shutdown".

**Comment by JonasNilson** [comment]
> It should be made clear what it does then.

I completely agree. I will address this in an upcoming release.

**Comment by JonasNilson** [comment]
Has been taken care of in the latest release:
* https://github.com/JonasNilson/idle_master_extended/releases
