### ISSUE TITLE
[BUG] <Steam login doesn't work>

### ISSUE THREAD

**Issue by supremehera** [JonasNilson/idle_master_extended#321]
when i try to login my steam account it just doesn't work, steam guard verification not appears.

Example:
1. Go to 'sign in'
2. try to log in to your steam account and click ok

not: i have same issiue for 1.7 and 1.8 beta

**Comment by JonasNilson** [comment]
https://github.com/JonasNilson/idle_master_extended/issues/307

**Comment by JonasNilson** [comment]
Closing as duplicate: https://github.com/JonasNilson/idle_master_extended/issues/307
