### ISSUE TITLE
[BUG] Badge page didn't load, will retry in 10 seconds loop

### ISSUE THREAD

**Issue by LolekLiam** [JonasNilson/idle_master_extended#323]
## Describe the bug ##
(A clear and concise description of what the bug is)

it loops on Badge page didn't load, will retry in 10 seconds. so every 10 seconds it loops, then later signs me off

## To Reproduce ##
(Steps to reproduce the behavior)

login, save and go to main menu

## Expected behavior ##
(A clear and concise description of what you expected to happen)

should load badge page and stay logged on

## Error logs ##
(Look in the `Idle Master Extended` directory for `error.log`)

(link to pastebin cuz long) [https://pastebin.com/raw/1pD9VuEr](https://pastebin.com/raw/1pD9VuEr)

## Screenshots ##
(If applicable, add screenshots to help explain your problem. **TIP**: Use Windows `Snipping Tool` and paste here)

## Additional context ##
(Add any other context about the problem here)

**Comment by JonasNilson** [comment]
I've seen the error message before but I can't put my finger on what can cause it...


```
11/07/2022 03:39:39   CookieClient -> GetHttpAsync, for url = https://steamcommunity.com/profiles/76561199077577633/badges/?p=1
```

**Comment by JonasNilson** [comment]
Do you still have this issue?

**Comment by HS-HAMER** [comment]
do you know how to fix it?

**Comment by JonasNilson** [comment]
> do you know how to fix it?

Do you experience the same issue? Can you provide more info and possibly information from the error log?

**Comment by JonasNilson** [comment]
> do you know how to fix it?

Do you experience the same issue? Can you provide more info and possibly information from the error log?

**Comment by HS-HAMER** [comment]
nvm it's all good now, but the issue is not giving good informations, basicly i thouth that to log in you have to give your steam id and password ( like all of these programs need) but no, just have to look trouth cookies (cookies and information of the site) then look for steam, and yeah, thank god this one youtube guide explain it

**Comment by HS-HAMER** [comment]
just cpoy them and paste into the program ... am kinda embareesd but ye
