### ISSUE TITLE
[BUG] Idle master wont log in

### ISSUE THREAD

**Issue by olej12** [JonasNilson/idle_master_extended#325]
Hello,i today,my idle master extended client stopped working. I have 1.8 beta,it logged me out and when i try to press the log in button,it shows animation of the button being pressed but nothing else. I tried every other version of client all the way to 1.0,but with same result. I Tried to disable the steam guard,restarting my pc,logging in with session id and stuff,even logging in to my second account but nothing changed. Well,with the cookie file stuff it shows that im logged in but it loads my badges for ages. Is it steam problem or idle master problem,and how can i fix it?

**Comment by V01DZ3R0** [comment]
Same issue, log-in doesn't work on 1.8 beta & 1.7, my OS - Win 10 21H2

**Comment by gr3y5had0w** [comment]
Same issue, using 1.7 and also 1.8 beta on Win 11 Version 21H2

**Comment by raichuu-bat** [comment]
I got the same problem, Win 10 21h2

**Comment by Akrista** [comment]
Same here, Version 1.7 Win 11 21H2

**Comment by faucetsoftware** [comment]
> 

worked for me thanks!

**Comment by faucetsoftware** [comment]
> Same here, Version 1.7 Win 11 21H2.
> 
> Edit: meanwhile, i manage to login with second method (cookies) found hete: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

Worked for me thanks!

**Comment by 1001golos** [comment]
> То же самое здесь, версия 1.7 Win 11 21H2.
> 
> Редактировать: тем временем мне удается войти в систему с помощью второго метода (файлы cookie), найденного здесь: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

OMG Thanks you man <3

**Comment by Xiiterr** [comment]
Cant log in either is there any other fix than cookie login?

**Comment by berkkrkc09** [comment]
Cookie method works. Thanks.

**Comment by Jules1816** [comment]
Same issue. Using credentials won't work, pressing the log in button does nothing, even tried a wrong password just to see if I got an error message, but didn't. Using cookies does not work either, whenever I save them I get an error saying they're not valid (I've read that's normal), but nothing happens; even tried modifying the configs file to manually save them there, but it's no use.

**Comment by modeular** [comment]
> Same here, Version 1.7 Win 11 21H2.
> 
> Edit: meanwhile, i manage to login with second method (cookies) found here: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

This worked for me. Thanks!

**Comment by woctezuma** [comment]
> Same here, Version 1.7 Win 11 21H2.
> 
> Edit: meanwhile, i manage to login with second method (cookies) found here: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

Thanks, this works!
1. Click the padlock,
2. Fill-in `sessionid`,
3. Fill-in `steamLoginSecure`.

**Comment by JonasNilson** [comment]
You can bypass the issue using the cookie login method described in the Wiki: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

See other issue: https://github.com/JonasNilson/idle_master_extended/issues/307
