### ISSUE TITLE
Doesn´t log in

### ISSUE THREAD

**Issue by Ezequiel2342** [JonasNilson/idle_master_extended#326]

**Comment by Akrista** [comment]
Hey man, check #325 , try to login via cookies for now...
https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

**Comment by ceriaz** [comment]
Found this page and used the cookie method as a workaround as standard login wasn't currently working like it has in the past. thanks for linking to the wiki. @Akrista

**Comment by Lowallyn** [comment]
same I can't login normally using the cookie method

**Comment by Kudretizade** [comment]
same, I can't login :/

**Comment by Akrista** [comment]
Update: I've been able to log in still with the cookies method. Tho, none of the games goes to farming mode, i would say that this tool is abandoned for now...

**Comment by JonasNilson** [comment]
You can bypass the issue using the cookie login method described in the Wiki: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

See other issue: https://github.com/JonasNilson/idle_master_extended/issues/307
