### ISSUE TITLE
[BUG] <Put a descriptive title here>

### ISSUE THREAD

**Issue by Mark17092000** [JonasNilson/idle_master_extended#327]
## Describe the bug ##
(A clear and concise description of what the bug is)

## To Reproduce ##
(Steps to reproduce the behavior)

Example:
1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior ##
(A clear and concise description of what you expected to happen)

## Error logs ##
(Look in the `Idle Master Extended` directory for `error.log`)

## Screenshots ##
(If applicable, add screenshots to help explain your problem. **TIP**: Use Windows `Snipping Tool` and paste here)

## Additional context ##
(Add any other context about the problem here)

**Comment by Mark17092000** [comment]
I don't have a login button. I click and nothing happens. Also tried on different accounts and different computers. Also through cookies.

**Comment by fikret0** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods#cookies

**Comment by JonasNilson** [comment]
You can bypass the issue using the cookie login method described in the Wiki: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

See other issue: https://github.com/JonasNilson/idle_master_extended/issues/307
