### ISSUE TITLE
FIX for NoLogin Bug

### ISSUE THREAD

**Issue by Oplikk** [JonasNilson/idle_master_extended#329]
# https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

---

For 1.7 and 1.8Beta

**1. Get all cookies ready** (refer to Cookie Login method in Wiki)
Use store.steampowered.com, not steamcommunity!
- sessionid
- steamparental (same as machineauth if missing)
- steamloginsecure
- steamrememberlogin
- steammachineauth
Also have your steam profile url ready.

**2. Open the folder where you have idlemaster files**
Open the "IdleMasterExtended.exe.config"
Paste all cookies prepared from step no. 1 into the correct fields and add </value> after, and paste also the Steam profile url

The line with the cookie should look like this:
`<value>CookieData</value>`
Do not forget to add the `</value>` at the end, as it is missing by default!
!SAVE! the changes made, do not open the app yet otherwise you risk invalidating the cookies(steam wtf!?!?)

**3. Go to the configuration shortcut inside the folder with Idle master,** 
if missing go to AppData -> Local ->IdleMasterExtended

Remove Everything inside the folder (folders idlemasterextended.exe_url_XXXXXXXX)

**4. Run IdleMasterExtended.exe**

You should be logged in.

If the interface of the app looks buggy/offset/all over the place - close idlemaster, launch again a few times. If does not help repeat step 3.
If you are not logged in - Repeat all from step 1 (generate new cookies by signing out of steam, and signing in again). 
If the app cannot load badges (repeats in 10s intervals) - Wrong profile url in the config, update and repeat step 3

**Comment by mrcabbar** [comment]
It is not working on me. When I start the IdleMasterExtended.exe I am not logged in and the interface of the app is buggy.

**Comment by Oplikk** [comment]
> Start the idlemaster once more and if fail repeat no. 3
