### ISSUE TITLE
SteamGuard compatibility

### ISSUE THREAD

**Issue by axelnieves2012** [JonasNilson/idle_master_extended#33]
My account has email and Mobile Steam Guard.
When I try to login in, application neverask me for my Steam Guard code.
Disabling it is NOT an option because my market will be disabled for 15 day if so.

Thanks.

**Comment by JonasNilson** [comment]
> My account has email and Mobile Steam Guard.
> When I try to login in, application neverask me for my Steam Guard code.

What version are you using?

The Steam Guard window should pop up when you try to log in manually.

![image](https://user-images.githubusercontent.com/5990550/74608378-c5398900-50e0-11ea-8e20-522dd42a82d9.png)

**Comment by axelnieves2012** [comment]
> > My account has email and Mobile Steam Guard.
> > When I try to login in, application neverask me for my Steam Guard code.
> 
> What version are you using?
> 
> The Steam Guard window should pop up when you try to log in manually.
> 
> ![image](https://user-images.githubusercontent.com/5990550/74608378-c5398900-50e0-11ea-8e20-522dd42a82d9.png)

I don't know. I don't understand github. It would be easy a Mega or Mediafire link. How do I get the latest version?? That steamguard window was never shown to me :(

**Comment by JonasNilson** [comment]
@axelnieves2012 

https://github.com/JonasNilson/idle_master_extended/releases

There's a direct download link available for the latest release

**Comment by axelnieves2012** [comment]
Hello, I was using version 1.4 final, but I've never seen authenticator popup :'(

**Comment by JonasNilson** [comment]
@axelnieves2012

Can you provide a screenshot of the idle master window?

**Comment by JonasNilson** [comment]
> Hello, I was using version 1.4 final, but I've never seen authenticator popup :'(
@axelnieves2012

Is this still an issue? If so, please provide a screenshot showing the issue

**Comment by axelnieves2012** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/35415189/77259982-b2781e00-6c63-11ea-84f6-b24131e1d27c.png)
Hello, Am sorry, I completelly forgot about it. I still have this issue.
Screenshot uploaded. After entering my login details, SteamGuard popup never is show

**Comment by JonasNilson** [comment]
@axelnieves2012 

Can you try disabling the QuickLogin property under File > Settings?

**Comment by axelnieves2012** [comment]
> @axelnieves2012
> 
> Can you try disabling the QuickLogin property under File > Settings?

Done, brother. Still not working. I got back to this screen 
![Screenshot_1](https://user-images.githubusercontent.com/35415189/77489555-345c7880-6e17-11ea-9c44-47e864701524.png)

**Comment by axelnieves2012** [comment]
After several testing, I noticed that it doesn't even check if password is correct or not. It keeps returning the same, no matter if wrong password, inexistent account, etc.

**Comment by JonasNilson** [comment]
That's odd... I am not able to reproduce the issue:

![image](https://user-images.githubusercontent.com/5990550/77581342-d5ae0200-6edd-11ea-9598-0d1e55f7dc25.png) ![image](https://user-images.githubusercontent.com/5990550/77581516-21f94200-6ede-11ea-8968-c3d12627cdec.png)

**Comment by axelnieves2012** [comment]
The only idea I have is TeamViewer. I would let you in my PC, so you can see it by yourself.
If you interested, add me to steam as a friend, if you see me online you can PM me and I will let you in. Thanks

**Comment by DouglasGiovanella** [comment]
@JonasNilson Maybe It is his Internet Explorer version?

**Comment by axelnieves2012** [comment]
> @JonasNilson Maybe It is his Internet Explorer version?

Interesting. I'll try

**Comment by axelnieves2012** [comment]
> @JonasNilson Maybe It is his Internet Explorer version?

SOLVED. Hello, I updated to IE11 and  problem was solved. Thanks, that was the definitive solution.

**Comment by JonasNilson** [comment]
@axelnieves2012 

Awesome. I'll add this as a potential issue :sparkles:
