### ISSUE TITLE
Games randomly stop idling

### ISSUE THREAD

**Issue by ChristianMods** [JonasNilson/idle_master_extended#330]
Hello there.

Over the past few days, I've been idling 2 games, and have noticed that steam stops recognizing that it's running, even when the program is still on with the game card open.

I've been using this program for a long while now, and I've never seen it happen until the past couple days. 

EDIT: I've got an actual picture of it now

![Capture](https://user-images.githubusercontent.com/68878422/179865746-fa00a18a-1c1c-4c3d-b670-ecb1ea9aedc3.PNG)

SECOND EDIT: Just wanted to clarify that this happens on both v1.7 and v1.8

**Comment by JonasNilson** [comment]
Thanks for your report. Do you know how long you had been running before it stopped recognizing the game running?

**Comment by ChristianMods** [comment]
> Thanks for your report. Do you know how long you had been running before it stopped recognizing the game running?

I couldn't really give you a spot-on estimate. Maybe 30 minutes - to an hour.
