### ISSUE TITLE
[BUG] <tengo un problema, no me inicia sesión la app y nose porque me pasa esto, uso la versión (1.7)  >

### ISSUE THREAD

**Issue by elpaty** [JonasNilson/idle_master_extended#331]
## Describe the bug ##
(A clear and concise description of what the bug is)

## To Reproduce ##
(Steps to reproduce the behavior)

Example:
1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior ##
(A clear and concise description of what you expected to happen)

## Error logs ##
(Look in the `Idle Master Extended` directory for `error.log`)

## Screenshots ##
(If applicable, add screenshots to help explain your problem. **TIP**: Use Windows `Snipping Tool` and paste here)

## Additional context ##
(Add any other context about the problem here)

**Comment by Akrista** [comment]
Hola elpaty, por favor trata de usar el segundo metodo explicado en este sitio: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

Donde con las cookies podras logearte al idle_master, si tienes otras dudas puedes contactarme. Te recomiendo en proximas oportunidades llenar los formularios de Issues, de esta forma otras personas puede beneficiarse de tu post.

**Comment by JonasNilson** [comment]
No information provided
