### ISSUE TITLE
I can't login :(

### ISSUE THREAD

**Issue by taarrr** [JonasNilson/idle_master_extended#332]
Well, i put my Steam account's password and username, i click to login and  can't. No matter how many times I click the button, it doesn't work... But when i click on the "Steam button" then the window closes and says: "Idle Master is saving your informations", but that button on the smaller window "login" still saying that i have not logged in. But if you click on the login button and wait 300 hours (irony lol) the window closes, and still saying i have not logged in! Is that an issue? Or is the progam itsel?

**Comment by JonasNilson** [comment]
Related: https://github.com/JonasNilson/idle_master_extended/issues/307

**Comment by Sharpyku** [comment]
same :(
