### ISSUE TITLE
[FIX] <Idle master not login bugfix>

### ISSUE THREAD

**Issue by notDeadShogun** [JonasNilson/idle_master_extended#333]
# https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

---

1. Open the browser, go to its settings

go to browser settings
Scroll down and click "additional"
go to additional
We find there "content settings"
find content settings
Next, click "cookies"
go to cookie
"All cookies and site data"
all cookies
Type "steam" into the search bar and click delete everything
clear cookies
In a browser, go to steamcommunity.com and log in to your account.

2. We go to your account on the steam website
When you are logged into your account, go back to the settings. We update the tab, drive it into steam again and among the files that appear, click on steamcommunity.com.

go to settings again
Here we are interested in 2 points:
sessionid
steamLoginSecure
find sessionid
Open the sessionid, find the "content" tab and highlight the numbers written there.
copy the numbers
Now open the idle master program, go to file -> settings

3. Go to idle master settings
We open additional settings (lock icon) and see the very fields "sessionid" and "steamLogin" (in the browser this is steamLoginSecure). Paste the copied numbers into the "sessionid" field
fill in the fields
Now the same procedure must be done with the "steamLoginSecure" field:

Let's go to the browser
find "steamLoginSecure"
find "content"
copy the numbers
back to idle master settings
Paste the copied code into the "steamLogin" field
paste the code
As inserted, click "update".

5. Click update
You will see “the entered data is incorrect”, but this is normal (I did not have this error on version 1.8, but the author had it in the original article. So keep in mind).
don't be afraid of mistakes
We close everything and see that the idle master is connected to the steam and the cards are farmed (I checked it personally)

The original article in Russian with screenshots is here: https://csgo-gg-wp.ru/problems/idle-master-neavtorizuetsy/

**Comment by verone0001** [comment]
Confirmed that this is working for v.1.7 as well as 1.8. In my case, in none of them I got the error said in point 5.

Thank you!

**Comment by chelse1778** [comment]
im bad in english. where is sessionid find?? can someone help??

**Comment by dontobeythelaw** [comment]
Thank you so much.

**Comment by wefalltomorrow** [comment]
Can use this to save a bunch of time :) https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/

**Comment by JonasNilson** [comment]
> Can use this to save a bunch of time :) https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/

I have added more details on browser addons here: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

**Comment by Maghelor** [comment]
hey guys i need help with steamloginsecure thing when i went to cookie settings sessionid is there but steamloginsecure isnt what should i do
