### ISSUE TITLE
[BUG] <can't login>

### ISSUE THREAD

**Issue by Sharpyku** [JonasNilson/idle_master_extended#334]
I can't login, i delete all cookies from all browsers, chrome, internet explorer, internet edge, when i pres button "login" nohting happen...

**Comment by verone0001** [comment]
Check: #307

**Comment by chelse1778** [comment]
I cant login too. I just enter my log&password and click LOGIN.. nothing heppens. Solve this pls..

**Comment by FowlizM** [comment]
i get the same problem as well. even the quick login button doesnt works. ive tried 1.7 and 1.8 dont works on both

**Comment by 1imestone** [comment]
Can't login with cookie method since yesterday evening EU time. Versions 1.7 , 1.8beta. Chrome & Firefox
![Screenshot_13_valid0](https://user-images.githubusercontent.com/99689191/183908564-3bfcca00-fb37-4a55-8841-c05f6f715444.png)
.

**Comment by alirezaskyfall** [comment]
> Can't login with cookie method since yesterday evening EU time. Versions 1.7 , 1.8beta. Chrome & Firefox ![Screenshot_13_valid0](https://user-images.githubusercontent.com/99689191/183908564-3bfcca00-fb37-4a55-8841-c05f6f715444.png) .

i have the same problem with this method as well

**Comment by Clown-0914** [comment]
I can't  login after entering username and password.

**Comment by Darthanos** [comment]
Having the same problem, with both 1.7 and 1.8; I enter my user ID and password, click login, and nothing happens at all.

Glad it's not just me - I thought it was something with my account that was messed up.  Guess I'll have to physically launch the games for a while, or just wait for a fix.

**Comment by JonasNilson** [comment]
@1imestone https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods - Try to change your input in the field `steamparental` to the value of `steamMachineAuth`

**Comment by JonasNilson** [comment]
Duplicate issue: https://github.com/JonasNilson/idle_master_extended/issues/307
