### ISSUE TITLE
[BUG] Steam-idle.exe instantly closing

### ISSUE THREAD

**Issue by 2Dimitri** [JonasNilson/idle_master_extended#336]
Steam-idle.exe instantly closing if the game has no logo (not on the steam servers).
it can be idled for 5 seconds but it closes instantly.
my profile shows that im in the game.

**Comment by JonasNilson** [comment]
> Steam-idle.exe instantly closing if the game has no logo

Interesting. Do you have a Steam game ID that I can use to try this on my own machine?
