### ISSUE TITLE
How to install a game opened by Idle Master?

### ISSUE THREAD

**Issue by PlainOlSoapBar** [JonasNilson/idle_master_extended#337]
I accidently idled two games that I OWN but I haven't installed. Steam now thinks I have the game installed so I can't install the game anymore. Any solutions? Thanks.

**Comment by PlainOlSoapBar** [comment]
Ah, I seem to have found a solution in no time. I simply went to Steam > Settings > Downloads, and cleared my download cache.

**Comment by JonasNilson** [comment]
Interesting scenario that I haven't seen or heard of before. Thank you for sharing 👌🏻
