### ISSUE TITLE
[BUG] It won't login.

### ISSUE THREAD

**Issue by locodesert-2** [JonasNilson/idle_master_extended#338]
The thing just won't login to my steam no matter what.

**Comment by darklinkpower** [comment]
Experiencing the same issue. Nothing happens when clicking the login button. I have 2fa in case that helps pinpoint the issue 
![image](https://user-images.githubusercontent.com/1389286/185028062-46ecab8a-6406-4877-a76f-d563536ee007.png)

**Comment by tahazus** [comment]
same problem

**Comment by Troyjan20072001** [comment]
have had the same issue for weeks now.

**Comment by JonasNilson** [comment]
You can bypass the issue using the cookie login method described in the Wiki: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

See other issue: https://github.com/JonasNilson/idle_master_extended/issues/307
