### ISSUE TITLE
[BUG] <not working>

### ISSUE THREAD

**Issue by SobhanMirzaei** [JonasNilson/idle_master_extended#339]
It didn't work in the latest version 1.8 and a previous version which was the most recent didn't work either. **This problem is almost a month old**. Where is the problem, should I look for alternative software? 
Please solve the problem as soon as possible. Thanks .

**Comment by SobhanMirzaei** [comment]
![Screenshot 2022-08-17 095823](https://user-images.githubusercontent.com/50620530/185042211-4bb334fb-55fb-417e-9dbf-e1019174fc79.jpg)

**Comment by KilianOne** [comment]
Hello my friend. I will explain the steps for you to log in your account. 
Open the program then go to the File section (top right) then click on Settings.
Click on the padlock (bottom left).
In your preferred browser. Go to the Steam page and press F12 then in the two tabs that are in the code terminal that came out when you press F12, click on application then in the storage section click in cookies and then click on the section that comes out in cookies. in the part where it says name look for your sessionid and copy it into the program (in the padlock on the bottom left when you open configuration) the same thing you do with your SteamLoginSecure. I hope I have explained well. If not you can ask for my discord and I will explain you.

**Comment by JonasNilson** [comment]
@SobhanMirzaei: You can bypass the issue using the cookie login method described in the Wiki: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

See other issue: https://github.com/JonasNilson/idle_master_extended/issues/307
