### ISSUE TITLE
Can't signin due to family view

### ISSUE THREAD

**Issue by Cabola** [JonasNilson/idle_master_extended#34]
I get the login screen, then get the steamguard screen and after that, because I use family view, I need to enter my code for to that too, but the window just closes before you get a chance to enter the code.
All the above is with quick login checked.

However without quick login checked it doesn't do anything after submitting the family view pin, except closing down the window after a short while..

Using the latest release 1.4 (fixed)

**Comment by Cabola** [comment]
just wanted to add that I did manage to enter my pin for the family view by having it copied to just paste it into the input field and then hit return but 2 sec after the window was closed down.

**Comment by Cabola** [comment]
I've managed to get logged in by using the feature in settings and pasting in the sessionID, the steamLoginSecure and the steamparental from the steam page in my browser! It did give an error, which I didn't pay attention to, since Idle Master started gathering info and load up in remaining card drops/games...

**Comment by JonasNilson** [comment]
@Cabola 

I'm glad you figured out a way 🤘🏻I didn't think of that myself.

**Comment by h0wardch3ng** [comment]
LOGIN INFINITE LOOP, PLEASE TURN OFF THE AUTO LOGIN SETTING AND AUTO CLEAN LOGIN CACHE

**Comment by JonasNilson** [comment]
> LOGIN INFINITE LOOP, PLEASE TURN OFF THE AUTO LOGIN SETTING AND AUTO CLEAN LOGIN CACHE

If you are experiencing any login issues, please open a separate issue with details on what goes wrong.
