### ISSUE TITLE
[BUG] -Error logging in to steam- "Solusion "

### ISSUE THREAD

**Issue by KilianOne** [JonasNilson/idle_master_extended#340]
I will explain the steps for you to log in your account. 
Open the program then go to the File section (top right) then click on Settings.
Click on the padlock (bottom left).
In your preferred browser. Go to the Steam page and press F12 then in the two tabs that are in the code terminal that came out when you press F12, click on application then in the storage section click in cookies and then click on the section that comes out in cookies. in the part where it says name look for your sessionid and copy it into the program (in the padlock on the bottom left when you open configuration) the same thing you do with your SteamLoginSecure. I hope I have explained well. If not you can ask for my discord and I will explain you.

Translated with www.DeepL.com/Translator (free version)

**Comment by JonasNilson** [comment]
Thank you for your submission. 

This information is available in the Wiki page: 
- https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods (see Cookie method)
