### ISSUE TITLE
[LOGIN] Is there any way login without cookies?

### ISSUE THREAD

**Issue by tahazus** [JonasNilson/idle_master_extended#341]
Is there any way login without cookies?

**Comment by esmith13** [comment]
Looking for a solution to normal login as well. Cookie login works, but a more traditional method would be most appreciated.

**Comment by JonasNilson** [comment]
> Is there any way login without cookies?

Not at this moment. I am working on a potential fix for the login without a browser but it is in early development - and I haven't been able to spend more than an hour here and there over the past years.

Are there any issues with the cookie login method that needs to be addressed?

**Comment by tahazus** [comment]
no not

**Comment by gundogfan** [comment]
![image](https://user-images.githubusercontent.com/70611792/187036097-92b4d231-6f4a-413c-99c9-eccd0988d59e.png)

Actually, I don't have neither steamMachineAuth nor steamParental. What do I do? Normal login doesn't work.

**Comment by esmith13** [comment]
You only need 'sessionid' and 'steamLoginSecure'. I have never filled the third box and it always works fine.

**Comment by gundogfan** [comment]
I should have tried that lmao, thanks!
