### ISSUE TITLE
[BUG] <I cant login to the steam account>

### ISSUE THREAD

**Issue by SuntAle1** [JonasNilson/idle_master_extended#344]
So i clicked on idleMasterExtended.exe, ran it with admin, and i clicked on connect with steam and it just wont connect

**Comment by vinirockman** [comment]
Try this:
https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

**Comment by JonasNilson** [comment]
> Try this: https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods

Closing as duplicate.
https://github.com/JonasNilson/idle_master_extended/issues/307
