### ISSUE TITLE
Games aren't idling

### ISSUE THREAD

**Issue by MKNick10** [JonasNilson/idle_master_extended#345]
Games won't idle, no matter what settings I may change, they're simply not working. Apparently, the apps sees the game running for a minute or two, and then when clicking on  "** card drops remaining" to check immediately, it'll show that 0 games are idling, Steam in no moment shows any game running either.

First screenshot shows the game apparently idling, second screenshot shows after the Drop Check, which also shows how there are no games idling at the moment, yet appears to have the game open, I'm really confused
## Error logs ##
There are no errors.

## Screenshots ##
![image](https://user-images.githubusercontent.com/111958709/186354005-d1f5d372-6c0a-48f1-ba8a-6032ff277a8e.png)
![image](https://user-images.githubusercontent.com/111958709/186354009-0dc03132-6119-4972-8a2b-480e7f10f2d0.png)

**Comment by JonasNilson** [comment]
> when clicking on "** card drops remaining" to check immediately, it'll show that 0 games are idling

Might be an interface bug. Do you still get your hours for the game?

I'm a bit confused about how you have 30+ hours on the game and still 5 card drops remaining. Do you know the reason behind that?
