### ISSUE TITLE
Invise mode

### ISSUE THREAD

**Issue by Marcelzocker999** [JonasNilson/idle_master_extended#346]
It would be great if idling could be done without showing pop-ups that you are playing games for friends. For example, by auto-enabling steam invisibility state for account.

**Comment by JonasNilson** [comment]
Currently there are no integrations in Idle Master Extended that allows changing the status or settings for your account. 

You can however change privacy settings on your profile to stay online without your friends knowing which games you are playing:

- ![image](https://user-images.githubusercontent.com/5990550/186978501-3497dfcb-680a-4858-95ec-ec1d1fa1dcf0.png)
  - ![image](https://user-images.githubusercontent.com/5990550/186978281-9bb63502-ce9a-4379-9f95-b6ba286049b1.png)
