### ISSUE TITLE
[Enhancement] Browser in WebView2

### ISSUE THREAD

**Issue by DiogoABDias** [JonasNilson/idle_master_extended#347]
I'm a fan, thanks @JonasNilson for keeping up with this app and not letting it die.
The old browser control started giving problems for everyone as you are very aware of it.

Check my repos maybe, I have an implementation of steam login in a WebView2 winforms working.
It's in .net core however, not sure what could break when changing the project target framework, but could be good a solution for now.

**Comment by JonasNilson** [comment]
Thank you for your comment. I will have to take a look when I get the time.

This app probably have to be ported to .NET Core some time in the future if it's going to live on.

**Comment by JonasNilson** [comment]
I decided to remove the browser window in the latest release. I might go back to this issue in the future to include a browser window based on `WebView2`.
