### ISSUE TITLE
[BUG] extra 24 hours of downtime

### ISSUE THREAD

**Issue by wollframium** [JonasNilson/idle_master_extended#350]
you probably broke the algorithm of farm, because 92 games I farmed for 50 hours, after I woke up yesterday there were 40 games left, everything stopped only in idle time in games, I decided to change the mode and it began to show that there were no games left (although they remained) I restarted the program, reinstalled cookies and there are 10 games left. tested on 4 different computers with 4 different accounts, everywhere a bad indicator of farm.

**Comment by JonasNilson** [comment]
> 92 games I farmed for 50 hours, after I woke up yesterday there were 40 games left

If I understand correctly you successfully idled 52 games and got your cards for them - but there are 40 games that you still have card drops from?

> I decided to change the mode 

What mode did you originally use and what mode did you change to?

> there are 10 games left

In Idle Master Extended or on Steam? And are you expecting this number to be 40?

Also make sure to look on your badge page for the games that still have card drops remaining: https://steamcommunity.com/my/badges

**Comment by wollframium** [comment]
I left for the night, 40 games were ready in the morning, and the next day the remaining 50 games lasted, I went to bed again and there were still 50 games in the morning, I suspected something was wrong and overloaded the cookies and the program (when I changed the modes, it called that everything was ready) after overloading the cookies, 8 games remained, I checked those games which were farmed idle in some games there were 16 hours (although they were farmed clearly more than 16 and the cards in them have long since fallen out)

**Comment by miltoz** [comment]
got the same problem :(

**Comment by miltoz** [comment]
imma try 1.7 now

**Comment by miltoz** [comment]
FIX: go to thispc and serch for "idlemaster", delte them all and re-install
