### ISSUE TITLE
[BUG] Controller stops working in game, when idling cards

### ISSUE THREAD

**Issue by taras28ua** [JonasNilson/idle_master_extended#354]
## To Reproduce ##
(Steps to reproduce the behavior)

1. Open game and connect controller.
2. Open Steam idle .
3. If already opened, wait for another game to start idling (don't know if it needs to support gamepads or no, because i can't skip to test). 

## Expected behavior ##
If opened after some game, controller will stop working in game, but works fine in steam big picture or in overlay controller setting, only in game it needs to be reconnected.

## Error logs ##
14.09.2022 0:51:47   Badge -> CanCardDrops, for id = 457210
System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMasterExtended.Badge.<CanCardDrops>d__28.MoveNext()

did not seem to be related.

## Screenshots ##
(If applicable, add screenshots to help explain your problem. **TIP**: Use Windows `Snipping Tool` and paste here)

## Additional context ##
(Add any other context about the problem here)
It may be some problem with steam triggering controller switch to an idling game, presuming it now runs as main game idk. But it never happens on earlier versions of Steam Idle and Steam client.

**Comment by JonasNilson** [comment]
Thank you for your bug report. 

I believe I've seen another issue like this so if I get my hands on a controller I can hopefully reproduce it. 

What controller are you using?

**Comment by taras28ua** [comment]
> Thank you for your bug report.
> 
> I believe I've seen another issue like this so if I get my hands on a controller I can hopefully reproduce it.
> 
> What controller are you using?

I'm using Gulikit kingkong 2 pro in xinput mode, so it's behave like standart Xbox 360 gamepad, and also Steam controller
