### ISSUE TITLE
[Not Idling] Not idling any games it says it is.

### ISSUE THREAD

**Issue by BedHead797** [JonasNilson/idle_master_extended#355]
It says that steam is running and is connected to steam and that it has card drops remaining and games left to idle, but none are currently idling. I've tried looking over the internet, the help logs, and tutorials, but nothing seems to help and everything I tried either did nothing or made it worse and I had to start over. I don't know if I missed a step or if I can't find the one video helping this problem, but if anyone here could help, that would be amazing.

<img width="239" alt="broken idle" src="https://user-images.githubusercontent.com/113873124/190950074-b108edc0-30b2-42f6-8a70-56d1d70be859.png">

(if the picture doesn't work it says
steam is running
idle master is connected to steam
13 card drops remaining
4 games left to idle, 0 idle now.
currently in-game Game Name)

**Comment by JonasNilson** [comment]
I've seen it happen before if you don't fully extract the zip file. And your screenshot has a window behind the app that says something about extracting.

https://github.com/JonasNilson/idle_master_extended/wiki/Get-started
