### ISSUE TITLE
Datos introducidos invalidos aunque son correctos

### ISSUE THREAD

**Issue by 2442-pixeles** [JonasNilson/idle_master_extended#356]
Actualmente tengo 2 cuentas de steam en mi pc, la principal con varios años, y la secundaria esta activa hace un mes aproximadamente, sin limitación ni nada, ya hice la compra de mas de 5 dólares, tengo el mercado desbloqueado y puedo agregar amigos.
Cuando quiero iniciar idle master con mi principal no hay ningun problema, inicio sesión en steam web y desktop , obtengo los datos de las cookies, completo los campos e inicia normalmente, obtengo los cromos y todo normal.
El problema ocurre con la cuenta secundaria, cierro la sesion principal en todos lados e inicio con la secundaria, obtengo las cookies, completo en idle master y presiono actualizar, procede a mostrame un mensaje diciendo que los datos introducidos son inválidos, pero lo raro es que se conecta igual a la cuenta, me reconoce la cantidad de cromos y los juegos pero no me dropea ningun cromo 
Trate de obtener los cromos dejando los juegos abiertos y tampoco me dropea ninguno, que puede estar pasando?
La cuenta esta deslimitada, tengo el mercado habilitado, todas las cookies activadas, y mis datos de juego y demás en publico.

**Comment by herrera-ignacio** [comment]
You might want to ask your questions in English if you want to get help faster.

**Comment by blumeDOU** [comment]
pudiste solucinarlo?

**Comment by juansebastian028** [comment]
lo solucionaste?
