### ISSUE TITLE
Idle Master always says Idling complete

### ISSUE THREAD

**Issue by Baromette** [JonasNilson/idle_master_extended#357]
I bought 3 games yesterday, all with cards available, still Idle Master says Idling complete. Until a few days ago it was working perfectly. I didn't change any settings in the Idle program, the games have dropable cards and are correctly installed.

**Comment by JonasNilson** [comment]
Sounds related to: https://github.com/JonasNilson/idle_master_extended/issues/353

At this moment the workaround I guess is to logout in Idle Maste Extended and enter your cookies again.

**Comment by Marcelzocker999** [comment]
> Sounds related to: #353
> 
> At this moment the workaround I guess is to logout in Idle Maste Extended and enter your cookies again.

Its works but is there any plans to fix it?

**Comment by Baromette** [comment]
Work, thank you so much <3

**Comment by jonas-med-ett-s** [comment]
Fixed in the latest release: https://github.com/JonasNilson/idle_master_extended/releases
