### ISSUE TITLE
[BUG] COOKIE METHOD NOT WORKING

### ISSUE THREAD

**Issue by Jealousy2** [JonasNilson/idle_master_extended#358]
Logging in with SESSIONID STEAMLOGINSECURE AND STEAMPARENTAL/STEAMMACHINEAUTH isnt working. missed when it was a simple user and pass ive tried 3 methods for it i have obviously done the cookie method and it says invalid data as well. im also getting another error where it says stam is not running. this program is becoming worse why?

**Comment by Artetika** [comment]
none of those did solve the problem, it still says unvalid data.

**Comment by jonas-med-ett-s** [comment]
More active thread: https://github.com/JonasNilson/idle_master_extended/issues/378
