### ISSUE TITLE
Add different gameids to list?

### ISSUE THREAD

**Issue by CristenPerret** [JonasNilson/idle_master_extended#36]
I really am not that interested in cards, although thats what this is purposed for.
Got it running fine and smooth.
Theres a blacklist, but not a 'whitelist', or a way to append more to the list.
Having trouble finding where the list of games are stored.
How could I add in other games that aren't included? (Dota/CS:GO/Warframe/PathofExile)

**Comment by JonasNilson** [comment]
There is currently no in-application support in Idle Master to do that, but you can use the steam-idle.exe bundled with Idle Master.

* You need the game application ID, which can be found by looking at the [Steam Store](https://store.steampowered.com/) page URL, or by searching [SteamDB](https://steamdb.info/):
![image](https://user-images.githubusercontent.com/5990550/76147139-7193dd00-6099-11ea-9948-f7498135a65f.png)
![image](https://user-images.githubusercontent.com/5990550/76147051-dac72080-6098-11ea-829e-f03ae0c9591f.png)

* Then insert that ID to steam-idle.exe, for example using the Windows Command Prompt which should open a separate window that tells you you're in-game:
![image](https://user-images.githubusercontent.com/5990550/76147125-5b861c80-6099-11ea-8ea5-d66ae849e8a4.png)
