### ISSUE TITLE
[BUG] the games still have more drops in them and idle master doesn't seem to work even with new games it hasn't farmed cards on

### ISSUE THREAD

**Issue by locodesert-2** [JonasNilson/idle_master_extended#361]
I have been using idle master for a while but it seems recently every time I use it it doesn't really work right where it won't log me in or just won't farm games with cards that clearly still have drops in them and the issues have been going on for a while and I have no idea why.

**Comment by onsamyj** [comment]
Same. Says that there are no games to idle, despite the opposite.

I’m switching to [an alternative](https://alternativeto.net/software/idle-master/) for now.

**Comment by verone0001** [comment]
This is related to #353, in which it is adviced to logout then re-enter the `sessionid` and the `steamLoginSecure`

**Comment by Drakogol** [comment]
> This is related to #353, in which it is adviced to logout then re-enter the `sessionid` and the `steamLoginSecure`

yeah done that already like 4 times. it stays the same problem. THere are like 18 "newer" games and it doesnt work.

**Comment by verone0001** [comment]
You probably want to refresh your login then get new info. I tested it and it's working.

**Comment by Drakogol** [comment]
> You probably want to refresh your login then get new info. I tested it and it's working.

is there some trick i dont know? i even did a relog on the steam app. then logout IME and closed it. restart IME. login on steam webpage and copied cookies

**Comment by verone0001** [comment]
I reproduced the steps from [here](https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods) like the exact same. Probably your cookies aren't refreshing correctly from the API.

**Comment by faucetsoftware** [comment]
reentering my login information fixed this for me, thank you :)
