### ISSUE TITLE
[BUG] Program installs all games to be idled

### ISSUE THREAD

**Issue by 3sunsgaming** [JonasNilson/idle_master_extended#362]
## Describe the bug ##
(A clear and concise description of what the bug is)
As per title. I have used this program my fair share of times but, this is the first timer I can remember it installing the games that needed to be idled. I was kinda shocked when after the idle 22 games appeared to be installed. Is this a new feature or did something go screwy?

## To Reproduce ##
(Steps to reproduce the behavior)

Example:
1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior ##
(A clear and concise description of what you expected to happen)

## Error logs ##
(Look in the `Idle Master Extended` directory for `error.log`)

## Screenshots ##
(If applicable, add screenshots to help explain your problem. **TIP**: Use Windows `Snipping Tool` and paste here)

## Additional context ##
(Add any other context about the problem here)

**Comment by juxant** [comment]
The application doesn't install games. Just restart steam and they will disappear.

**Comment by 3sunsgaming** [comment]
You are right, that is exactly what happen and made my way back here to comment on it. Thanks for your input tho much appreciated. Closing now
