### ISSUE TITLE
[BUG] Always says "Reading badge page, please wait..." and never starts idling

### ISSUE THREAD

**Issue by MarinaniYT** [JonasNilson/idle_master_extended#365]
## Describe the bug ##
The games don't show up for me to idle, it just says that it's reading the badge page and not doing anything

## To Reproduce ##
Sign in, go to main, look under "Idle master connected to steam"

## Expected behavior ##
(A clear and concise description of what you expected to happen)

## Error logs ##
[error.log](https://github.com/JonasNilson/idle_master_extended/files/9997144/error.log)

## Screenshots ##
![image](https://user-images.githubusercontent.com/78842654/201521058-a1f6d34b-91ad-4fae-bf1d-e518639c4f05.png)

## Additional context ##
none

**Comment by rakantoh** [comment]
same to me, steam is running, idle master is connected to steam and my user, and the program stucks in "reading badge page, please wait..." adittionally, when i tried to "login" in idle master, i put the correct data (sessionid and steamloginsecure) and the program says "the data you've entered isn't valid, please try again.", but the program connects with steam and user successly.
![imagen_2022-11-13_230554559](https://user-images.githubusercontent.com/59809634/201573004-51f01ff4-bed8-4806-80f5-f62a201303ad.png)

**Comment by Kuyashi** [comment]
turning family view **off** solved this for me.

**Comment by MarinaniYT** [comment]
I don’t have family view on, I had to use steamMachineAuth to sign in

**Comment by fjose1987** [comment]
For me the same is happening, It gets stuck on that...

**Comment by kortul** [comment]
Same with 1.9. Did not have steamMachineAuth or Steamparental cookie. Reinstalled 1.8 and it worked right away!

**Comment by TBlazeWarriorT** [comment]
Can confirm it happens, but mine was fixed by just reopening v1.9

**Comment by shiraikoocha** [comment]
I can't see the 'steamMachineAuth' cookie on my device and I can't log in on other versions either. There is no family profile on my account. How can I manually find the 'steamMachineAuth' cookie?

**Comment by jonas-med-ett-s** [comment]
Fixed in the latest release: https://github.com/JonasNilson/idle_master_extended/releases
