### ISSUE TITLE
[QUESTION] Does this have a flag to launch minimized? 

### ISSUE THREAD

**Issue by Ayandaftary** [JonasNilson/idle_master_extended#366]
I would like to have it launch at startup (easily done with task scheduler) and launch as minimized while respecting `minimize to tray` option (not sure how)

**Comment by owolo** [comment]
Well you have already done startup, now you simply choose (in options) 
![image](https://user-images.githubusercontent.com/56605931/209337844-3881ab93-98e0-4bf5-96a7-1b324c776b9b.png)
and that's it, it should launch minimized to system tray at startup.
