### ISSUE TITLE
Problems with login

### ISSUE THREAD

**Issue by ChillingggJ** [JonasNilson/idle_master_extended#367]
I´ve been trying to login into idle but it asks me for this credentials
![problem](https://user-images.githubusercontent.com/119161254/204129930-3ca21dfb-5cdd-4520-9944-243c39bc16fc.png)
pls help

**Comment by vmarchesin** [comment]
Answer is in the [wiki](https://github.com/JonasNilson/idle_master_extended/wiki/Login-methods).

**Comment by JonasNilson** [comment]
I guess I could add a link to the wiki in an upcoming release to avoid having this question in the future. 

I will mark this thread as a suggested enhancement.
