### ISSUE TITLE
Not idling all games at once

### ISSUE THREAD

**Issue by Rias1337** [JonasNilson/idle_master_extended#368]
When I select fast mode or idle games for 2h... it just idles 31 games but there are 63 left

**Comment by BinSin01** [comment]
I want it to do more than 31 games can you do it?

**Comment by owolo** [comment]
> When I select fast mode or idle games for 2h... it just idles 31 games but there are 63 left

I suppose 31 game limit is a steam limit of how many steam instances at once you can run.
