### ISSUE TITLE
[BUG] The program does not work. 

### ISSUE THREAD

**Issue by asywuo** [JonasNilson/idle_master_extended#370]
Hi. I have successfully connected my steam information to the program. It says there are 15 games to run but it doesn't run any of them. I couldn't get it to work no matter what I did. I have successfully uninstalled and reinstalled the program many times, but it didn't work.
I left 2 screenshots from within the application. I hope you can help.
![Ekran görüntüsü 2022-12-23 004004](https://user-images.githubusercontent.com/88153344/209231517-467bdfd0-0a79-4552-8b5c-e239023ecce0.png)
![Ekran görüntüsü 2022-12-23 004021](https://user-images.githubusercontent.com/88153344/209231536-4dc14a12-655f-484b-bcaa-f1d88030bf3e.png)

**Comment by owolo** [comment]
Could the problem be with turkish language? Basically try putting english and it should show version 1.9, which it doesnt for some reason and do you launch the exe from folder?

**Comment by asywuo** [comment]
I don't know how it happened but it fixed itself. If the problem persists, I will upload the error document you mentioned here. Thank you for your interest and for trying to help.
![ekran 2](https://user-images.githubusercontent.com/88153344/209357951-ba0abafc-7a52-4114-85bc-1c0111399786.png)

**Comment by owolo** [comment]
Glad to hear ^^

**Comment by JonasNilson** [comment]
The issue looks related to running the application from within the ZIP resulting in the configuration and dependencies not being available. 

https://github.com/JonasNilson/idle_master_extended/wiki/Get-started
