### ISSUE TITLE
My games do not appear

### ISSUE THREAD

**Issue by koko2141** [JonasNilson/idle_master_extended#373]
My games do not appear despite having several, it only recognizes 2 or 3 of all the ones I have

![image](https://user-images.githubusercontent.com/121415622/209500299-e9969cda-17fb-4cde-a6bf-9f4a1da84bad.png)

![image](https://user-images.githubusercontent.com/121415622/209500332-5303e9cb-7591-4001-8db2-a38a794e127b.png)

**Comment by JonasNilson** [comment]
Looks like you don't have any card drops remaining for those games:

https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

Please look carefully if you are eligible for card drops for each game.

Otherwise, try to log in again in Idle Master Extended.
