### ISSUE TITLE
[BUG] <The application don't idling >

### ISSUE THREAD

**Issue by JuanDeLuca123** [JonasNilson/idle_master_extended#374]
Hi the program recognizes steam and all the games but when it comes to farming them it stays at 0 idle now and not get hours  in  the games its not a visual bug
![Captura de pantalla 2022-12-26 103529](https://user-images.githubusercontent.com/44267215/209554536-d11176ef-24e5-4337-98e0-45e8f29511d2.png)
[error.log](https://github.com/JonasNilson/idle_master_extended/files/10303672/error.log)

I don't know how to solve it, i try a lot of things and not working
Try to: install again the program, delete the files of the program, switch languajes and try to execute the program in other windows (windows xp - windows7), try to launch as a administrator and not, disable windows defender

**Comment by jonas-med-ett-s** [comment]
Looking at the `error.log` it seems like the Idle Master Extended application is not able to start the `steam-idle.exe` process:

```
26/12/2022 10:31:10   
System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xfffffffe)
   en System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   en System.Diagnostics.Process.Start()
   en System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   en IdleMasterExtended.Badge.Idle()
   en IdleMasterExtended.frmMain.StartSoloIdle(Badge badge)
   en IdleMasterExtended.frmMain.StartIdle()
   en IdleMasterExtended.frmMain.<tmrReadyToGo_Tick>d__82.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
26/12/2022 10:31:30   
System.ComponentModel.Win32Exception (0x80004005): Unknown error (0xfffffffe)
   en System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   en System.Diagnostics.Process.Start()
   en System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   en IdleMasterExtended.Badge.Idle()
   en IdleMasterExtended.frmMain.UpdateIdleProcesses()
   en IdleMasterExtended.frmMain.StartMultipleIdle()
   en IdleMasterExtended.frmMain.StartIdle()
   en IdleMasterExtended.frmMain.<tmrReadyToGo_Tick>d__82.MoveNext()
--- Fin del seguimiento de la pila de la ubicación anterior donde se produjo la excepción ---
   en System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
```

https://github.com/JonasNilson/idle_master_extended/blob/d60d920012fbeccdc54c2c0ce4b585984c6dec98/Source/IdleMasterExtended/Badge.cs#L34-L41


Can you provide more details of how you are starting your Idle Master Extended application? And please follow: https://github.com/JonasNilson/idle_master_extended/wiki/Get-started
