### ISSUE TITLE
idiling error (idel master 1.4 final).

### ISSUE THREAD

**Issue by Fraixv** [JonasNilson/idle_master_extended#38]
Hi there, I have been testing this application for about 2 hours and it worked correctly, but now I do not know what is happening that does not recognize any game, it only tells me idiling, if you know how to solve it I will be very grateful.

If my English is strange it is because it is not my language and I am using the translator to communicate with you.

PS: thanks for sharing this great application with the community.

![Sin título](https://user-images.githubusercontent.com/62419195/77144310-4f6c6880-6a64-11ea-8ff8-95034bb116f5.png)

**Comment by JonasNilson** [comment]
@Fraixv 

I tried looking into this yesterday but I didn't manage to reproduce the issue.

How many games do you have card drops available for?

**Comment by plopingo** [comment]
I have the same issue but I think it's with games I got for free. I think collecting is disable for them.
I got this message on the last one I added "GOAT OF DUTY" "No card drops remaining"
I don't remember it was like that in the past tho....

**Comment by JonasNilson** [comment]
> I have the same issue but I think it's with games I got for free. I think collecting is disable for them.
> I got this message on the last one I added "GOAT OF DUTY" "No card drops remaining"
> I don't remember it was like that in the past tho....

@plopingo 

As free games don't have card drops they won't get considered "idleable" by Idle Master

You can however use the steam-idle application bundled with Idle Master: https://github.com/JonasNilson/idle_master_extended/issues/36#issuecomment-596105776

**Comment by plopingo** [comment]
> > I have the same issue but I think it's with games I got for free. I think collecting is disable for them.
> > I got this message on the last one I added "GOAT OF DUTY" "No card drops remaining"
> > I don't remember it was like that in the past tho....
> 
> @plopingo
> 
> As free games don't have card drops they won't get considered "idleable" by Idle Master
> 
> You can however use the steam-idle application bundled with Idle Master: [#36 (comment)](https://github.com/JonasNilson/idle_master_extended/issues/36#issuecomment-596105776)

Goat for duty is a paid game. it was given for free for a limited amount of time.

**Comment by JonasNilson** [comment]
@plopingo

My bad. I didn't look into it before replying.

So you have card drops available, but it isn't recognized by Idle Master?

**Comment by plopingo** [comment]
> @plopingo
> 
> My bad. I didn't look into it before replying.
> 
> So you have card drops available, but it isn't recognized by Idle Master?

"No card drops remaining" for that game" it's why idle master don't reconize it but I don't know why this "No card drops remaining"

**Comment by JonasNilson** [comment]
@plopingo 

Goat of Duty doesn't have card drops as far as I can tell: https://store.steampowered.com/app/555000/GOAT_OF_DUTY/

**Comment by plopingo** [comment]
> @plopingo
> 
> Goat of Duty doesn't have card drops as far as I can tell: https://store.steampowered.com/app/555000/GOAT_OF_DUTY/

![image](https://user-images.githubusercontent.com/2069957/77363220-9ef7b080-6d52-11ea-8e2f-6109c630b4dd.png)

wtf xD

**Comment by plopingo** [comment]
same issue with https://store.steampowered.com/app/203160/Tomb_Raider/ free rn too
card drops in description for this one

**Comment by JonasNilson** [comment]
> same issue with https://store.steampowered.com/app/203160/Tomb_Raider/ free rn too
> card drops in description for this one

Please look under your own profile. I believe that if you receive the game for free you're not eligible for card drops:
![image](https://user-images.githubusercontent.com/5990550/77580818-ed38bb00-6edc-11ea-8085-acc196a6c32e.png)

**Comment by CrafterKolyan** [comment]
Games that were received for free on Steam (just by clicking add to Account button and not by Steam Key activating) do not have any card drops. This is not the issue of Idle Master, that's Steam Game Cards policy.
