### ISSUE TITLE
[FEATURE] Allow idle master to change your steam status

### ISSUE THREAD

**Issue by S-Flavius** [JonasNilson/idle_master_extended#380]
One of the biggest complaints I always had with idle master, was that when you start a new idle session, most of the time your status message will change from "playing x" to "playing y" to "playing z" ~5 times per second, every few minutes. One can see how it can be annoying to their friends, when they suddenly start playing 15 different games at once. Another huge problem is also, that most of the time I'll idle, I just leave my PC for a while, because I need multiple days to finish off getting all of my cards.

One easy way to fix this, would be to make idle master change the steam status to anything but online, meaning the status updates between games don't show anymore.

Considering the app already "signs in" using one's steam account, this should not be too hard to implement

**Comment by JonasNilson** [comment]
As of now there are no way for Idle Master Extended to change your Steam status.

The quickest solution is mentioned here: [How can I stop spamming my friends with games Idle Master Extended starts?](https://github.com/JonasNilson/idle_master_extended/wiki/FAQ#how-can-i-stop-spamming-my-friends-with-games-idle-master-extended-starts)
 - https://github.com/JonasNilson/idle_master_extended/issues/346
