### ISSUE TITLE
Uninstalled idling games show up as installed in the library

### ISSUE THREAD

**Issue by mnanofh** [JonasNilson/idle_master_extended#382]
I didn't have Yakuza 0 installed in my drive, and after IdleMaster idled that game it now shows up as installed in my library in Steam. And I cannot uninstall it, there is no appmanifest file either. This is also true for all other uninstalled games that have been idled.

**Comment by 25hz** [comment]
this is an error, reboot steam

**Comment by jonas-med-ett-s** [comment]
Closing as this is not an issue with Idle Master Extended, but rather an issue on Steam
