### ISSUE TITLE
[Feature] Limit Game/Badge list to games already played.

### ISSUE THREAD

**Issue by n00b42** [JonasNilson/idle_master_extended#384]
For now I would like to only gain cards for the games I already played at least once.
(Should be an option)

Rough idea for implementation: https://github.com/JonasNilson/idle_master_extended/pull/383

**Comment by n00b42** [comment]
tested, works as expected.
Thank you

**Comment by jonas-med-ett-s** [comment]
Thanks for the suggestion and feedback 🤝
