### ISSUE TITLE
Free Game  card drop

### ISSUE THREAD

**Issue by murhpy1** [JonasNilson/idle_master_extended#387]
steam Despotism 3k gave the game for free and there is a trading card, but when I open the idle master, the game does not appear (the game is paid on steam now)
I entered the whitelist code and ran it like that, the game appears to be played on steam, but the time is not visible, should I continue to run?
![Ekran görüntüsü 2023-01-13 025535](https://user-images.githubusercontent.com/122577984/212205917-8336a209-d91b-4583-a462-8ddd9d68fe1a.png)

**Comment by n00b42** [comment]
- When you are on the Store page of the game, is it marked as "already in your Steam Library"
- If not: If you did not add the game to your library when it was free, then you do not "own" the game, and will not get trading cards

(Please correct me if I am wrong in my assumptions)

**Comment by murhpy1** [comment]
the game appears in my library it says 5 cards left to collect
![Ekran Alıntısı](https://user-images.githubusercontent.com/122577984/212327053-5b336836-fa4c-479f-afa3-112e89aa479e.PNG)

**Comment by jonas-med-ett-s** [comment]
Your game page may say you have 5 cards remaining to collect (which is true)
- ![image](https://user-images.githubusercontent.com/5990550/214121278-13613418-6785-4aaf-a829-5ef8aa475de9.png)

But that does not mean that you are entitled for more card drops for that game (free games typically don't give you any card drops - you will have to purchase them or spend money in-game):
- ![image](https://user-images.githubusercontent.com/5990550/214121409-aa46752c-ceea-4b4c-a777-880fcdb44e4e.png)

More info: https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete
