### ISSUE TITLE
The Idler keeps unsigning me

### ISSUE THREAD

**Issue by BeamWreck** [JonasNilson/idle_master_extended#388]
I put my cookies in the Idler and after 1 day or 2 when I try to open it again, it unlogs me, and it is kinda annoying by now, it happened about 5 times already

**Comment by seriousfreezing** [comment]
The same thing happens to me, I put in the correct data and Idle says it's wrong

**Comment by jonas-med-ett-s** [comment]
At this moment the application cannot refresh your login cookie.

It is performed by your browser if you visit: 
- https://login.steampowered.com/jwt/refresh?redir=https://steamcommunity.com/ (requires you to be logged in with a valid cookie)
  - Requires the header: `Cookie`: `steamRefresh_steam=<jwt>`
