### ISSUE TITLE
[BUG] <No games in the list at all>

### ISSUE THREAD

**Issue by LucaMacTavish2502** [JonasNilson/idle_master_extended#390]
It already used all of the games the idle master chose by itself, and when I try to add a game through the Whitelist, it remains loading endlessly. And it didn't complete any of the games either. Help, please!!!!!!

**Comment by jonas-med-ett-s** [comment]
The whitelist mode will ignore the check for card drops and idle all the games you have added to the whitelist. [Read more in the Wiki on Whitelist mode](https://github.com/JonasNilson/idle_master_extended/wiki/Whitelist-mode).

You have probably received all the card drops you are eligible for on those games. Check under your badge page ([read more in the FAQ](https://github.com/JonasNilson/idle_master_extended/wiki/FAQ#why-dont-i-get-all-the-cards-for-a-badge)): 
![image](https://user-images.githubusercontent.com/5990550/214111542-17c1492f-1e7b-4383-8ff6-a7e3a36cad33.png)

Related: https://github.com/JonasNilson/idle_master_extended/issues/391
