### ISSUE TITLE
[BUG] <Idle Master not working>

### ISSUE THREAD

**Issue by MuhammetY** [JonasNilson/idle_master_extended#393]
## Describe the bug ##
  When I opened it a few days ago, the program's interface appeared to be faulty and it did not see that Steam was running. I couldn't enter the settings and log in with my information. I tried deleting and reinstalling but I still have the same problem, I've left a screenshot of the situation below.

## Error logs ##
3.02.2023 13:30:23   
System.Configuration.ConfigurationErrorsException: Yapılandırma sistemi başlatılamadı ---> System.Configuration.ConfigurationErrorsException: '.' (onaltılık değeri 0x00), geçersiz bir karakter. Satır 14, konum 1. (C:\Users\yigit\AppData\Local\IdleMasterExtended\IdleMasterExtended.exe_Url_am3uvqmbphff33uglnmuef0fkjmbdjt3\1.9.0.0\user.config line 14) ---> System.Xml.XmlException: '.' (onaltılık değeri 0x00), geçersiz bir karakter. Satır 14, konum 1.
   konum: System.Xml.XmlTextReaderImpl.Throw(Exception e)
   konum: System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   konum: System.Xml.XmlTextReaderImpl.ParseText(Int32& startPos, Int32& endPos, Int32& outOrChars)
   konum: System.Xml.XmlTextReaderImpl.ParseText()
   konum: System.Xml.XmlTextReaderImpl.ParseElementContent()
   konum: System.Xml.XmlTextReaderImpl.Read()
   konum: System.Xml.XmlTextReader.Read()
   konum: System.Xml.XmlTextReaderImpl.Skip()
   konum: System.Xml.XmlTextReader.Skip()
   konum: System.Configuration.XmlUtil.StrictSkipToNextElement(ExceptionAction action)
   konum: System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   konum: System.Configuration.BaseConfigurationRecord.ScanSectionsRecursive(XmlUtil xmlUtil, String parentConfigKey, Boolean inLocation, String locationSubPath, OverrideModeSetting overrideMode, Boolean skipInChildApps)
   konum: System.Configuration.BaseConfigurationRecord.ScanSections(XmlUtil xmlUtil)
   konum: System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- İç özel durum yığını izlemesinin sonu ---
   konum: System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   konum: System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   konum: System.Configuration.BaseConfigurationRecord.ThrowIfInitErrors()
   konum: System.Configuration.ClientConfigurationSystem.OnConfigRemoved(Object sender, InternalConfigEventArgs e)
   --- İç özel durum yığını izlemesinin sonu ---
   konum: System.Configuration.ConfigurationManager.PrepareConfigSystem()
   konum: System.Configuration.ConfigurationManager.RefreshSection(String sectionName)
   konum: System.Configuration.ClientSettingsStore.ReadSettings(String sectionName, Boolean isUserScoped)
   konum: System.Configuration.LocalFileSettingsProvider.GetPropertyValues(SettingsContext context, SettingsPropertyCollection properties)
   konum: System.Configuration.SettingsBase.GetPropertiesFromProvider(SettingsProvider provider)
   konum: System.Configuration.SettingsBase.GetPropertyValueByName(String propertyName)
   konum: System.Configuration.SettingsBase.get_Item(String propertyName)
   konum: System.Configuration.ApplicationSettingsBase.GetPropertyValue(String propertyName)
   konum: System.Configuration.ApplicationSettingsBase.get_Item(String propertyName)
   konum: IdleMasterExtended.Properties.Settings.get_whiteIcons()
   konum: IdleMasterExtended.frmMain.tmrCheckCookieData_Tick(Object sender, EventArgs e)
   konum: System.Windows.Forms.Timer.OnTick(EventArgs e)
   konum: System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   konum: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

## Screenshots ##
![image](https://user-images.githubusercontent.com/68477550/216577831-27932de7-ff5a-4a69-bc00-039b1bedab70.png)

**Comment by jonas-med-ett-s** [comment]
Looks related to this issue, caused by running the application from within the ZIP archive or running the application from a directory where the required files are not available:
- https://github.com/JonasNilson/idle_master_extended/issues/203

**Comment by Cheesepile** [comment]
Same thing is happening to me. Windows 11 22H2 22621.1413. Latest stable Steam build. Same graphical glitches, and it doesn't recognize Steam is running. Happened with a previously working version of 1.9.0, upgrading didn't fix the issue.

**Comment by Cheesepile** [comment]
> Same thing is happening to me. Windows 11 22H2 22621.1413. Latest stable Steam build. Same graphical glitches, and it doesn't recognize Steam is running. Happened with a previously working version of 1.9.0, upgrading didn't fix the issue.

Restarting my computer seemed to fix it.
