### ISSUE TITLE
I cant acces with the cookie method because I dont have data

### ISSUE THREAD

**Issue by Tangueiros** [JonasNilson/idle_master_extended#394]
I'm trying to access but just with the sessionid and the steamLoginSecure but it's says it's not valid.
I'm searching on the cookie display and I dont find neither the steamparental (I dont have that enabled) or the steamMachineAuth.
![image](https://user-images.githubusercontent.com/124473329/216794374-374d4d07-62ee-4756-bb58-fe06fa826252.png)
Here is an imagen of what I see on the cookie menu, as you can see, no steamMachineAuth or steamparental.
Can anyone help me?
After I click "Update" and close the window, the Idle Master is waiting and it says "Reading badge page.... Please, wait...." indefinitely.
![image](https://user-images.githubusercontent.com/124473329/216794612-4b7af6cd-14c0-42f5-8d2e-e151623c6196.png)

**Comment by jonas-med-ett-s** [comment]
Now this is a shot in the dark, but can you try to delete your Idle Master configurations?
- https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files

It seems like the application is either using some old config or there is an issue loading your badge page.

How many games do you own and do you know how many of them still have card drops remaining for you?
