### ISSUE TITLE
[BUG] Hours not counting up on idled game

### ISSUE THREAD

**Issue by 1Poseidon3** [JonasNilson/idle_master_extended#395]
## Describe the bug ##
I have a game I would like to idle not for cards but just because I want to. I have added it in the whitelist and set Idle Master Extended to whitelist mode. It claims to be idling the game and Steam says it is running but when I close the game, the games hours did not increase at all, no matter how long I ran it.

## Steps to Reproduce ##
1. Add only one game to whitelist (in my case, Phasmophobia).
2. Set Idle Master Extended to whitelist mode.
3. Begin idling.
4. At some point, stop idling and check hours.

## Expected behavior ##
The hours in the game increase.

## Error logs ##
No error log as an error did not occur.

## Screenshots ##
No screenshots necessary.

## Additional context ##
None.

**Comment by LucaMacTavish2502** [comment]
I still have almost the same problem: When I first tried Idle Master, it only chose Killing Floor 1 and Vector from my library. When it finished, it said no more card drop available, when I still haven't gotten all the cards yet. And in Whitelist mode, it only stays loading for eternity. I said I'd give up on this but I just can't ignore it. Please, anyone, tell me a way to fix this or why does this happen.

**Comment by 1Poseidon3** [comment]
One other piece of information I can add to this is when I was looking at my Steam Library and closing Idle Master Extended, I watched the hours played total actually go DOWN in real time.

> I still have almost the same problem: When I first tried Idle Master, it only chose Killing Floor 1 and Vector from my library. When it finished, it said no more card drop available, when I still haven't gotten all the cards yet. And in Whitelist mode, it only stays loading for eternity. I said I'd give up on this but I just can't ignore it. Please, anyone, tell me a way to fix this or why does this happen.

I personally have not experienced this issue as Idle Master Extended got through my entire 2.5k+ game library with no issues when it came to card drops (other than the occasional need to restart it and relog back in). However, it does sound like your issue might be related to mine in some way.

**Comment by LucaMacTavish2502** [comment]
Maybe. I don't know for cetain. All I know is that it seems I'm the ONLY ONE who has the problem I explained, and there're no explanations at all about it.
![Captura de pantalla 2023-02-08 202107](https://user-images.githubusercontent.com/123219461/217682715-d20519d6-d466-48bb-80a2-cf071dbfa5a0.png)
Here's my example. It remains stuck like this forever and ever.

**Comment by jonas-med-ett-s** [comment]
> It claims to be idling the game and Steam says it is running but when I close the game, the games hours did not increase at all, no matter how long I ran it.

@1Poseidon3 
I'm not sure what is causing this - but my guess at this moment is that Steam has some way of confirming the hours for that game (and possibly other games), e.g. making sure the real application is running.

**Comment by jonas-med-ett-s** [comment]
> it said no more card drop available, when I still haven't gotten all the cards yet. And in Whitelist mode, it only stays loading for eternity.

@LucaMacTavish2502 
Sounds like you have earned the cards you are eligible for (check your badge page and check the status of the games): 
- https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete
