### ISSUE TITLE
[BUG] Crashes While Running The App Out of Visual Studio

### ISSUE THREAD

**Issue by arlight1** [JonasNilson/idle_master_extended#396]
## Describe the bug ##
I cloned the repo locally and ran app through Visual Studio. It started with >300 card drops. After it got through 150 or so games, it crashed at the end. The Exception Thrown context in VS states that notificationCount.InnerHtml is a "NullReferenceException: Object reference not set to an instance of an object." The line it highlights is line 75 of CookieClient.cs file under the "IsLogined()" method. I still have the call stack and details windows open if further info is needed.

## To Reproduce ##
(Steps to reproduce the behavior)

1. Clone Repo
2. Run in VS with a multitude of games idling in 31-batch increments.
3. After some time (perhaps cookie expires) it crashes and throws the exception.

## Expected behavior ##
Expected to stop idling or display prompt that it was complete, i.e. not crash.

## Error logs ##
I have "Call Stack" and "View Details" logs if needed.

## Screenshots ##
![image](https://user-images.githubusercontent.com/30439252/217419081-84dcd000-aed5-42b0-8eb4-19561ecd73bc.png)

## Additional context ##
Operation performed in Visual Studio so maybe not applicable compared to executable binary format.

**Comment by arlight1** [comment]
Wanted to add that I'm a novice at C#, but could a 'try-except' be used here for instances where that object is null. Or even a check above the line in question for a null reference.

**Comment by jonas-med-ett-s** [comment]
@arlight1 
You will have to forgive me. I recently pushed a change that is causing this bug you found. The commit:
- https://github.com/JonasNilson/idle_master_extended/commit/387cd970df32568f51a19b071337444a2a50da6c

I was satisfied by the functionality but it seems like I didn't test it enough to catch that scenario. So thank you for reporting it.

If you want you can create a pull request with the fix.
