### ISSUE TITLE
Fast mode The mode is useless, and after the game is turned on, it will stop after a while。 Please help me

### ISSUE THREAD

**Issue by LSDGQ** [JonasNilson/idle_master_extended#397]
## Describe the bug ##
(A clear and concise description of what the bug is)
Fast mode模式没用游戏运行一会就会停止
Fast mode is useless, and the game stops after running for a while

游戏会集体运行10秒左右，但是过一会就全部停止运行了
The game will run collectively for about 10 seconds, but after a while it all stops running

抱歉，我好像是所有的模式都没效果，所有模式开启一会以后就会停止游戏的运行
Sorry, I don't seem to have any effect on all modes, and all modes will stop running after a while

![~2`%2}NXE2 SRZJY JU PJQ](https://user-images.githubusercontent.com/106037312/218305303-95e5cfc1-9db9-4338-bcbe-121da92b7c02.png)
![1K@U$C6@{%U2QUYA 1)_8Q](https://user-images.githubusercontent.com/106037312/218305325-48df41ac-d16d-4f5f-87ca-96fccb2a7607.png)

**Comment by jonas-med-ett-s** [comment]
I might be misunderstanding you, and if I do please provide some more information about what you are expecting from the application.

Based on the information you provided it seems like Idle Master Extended is working as intended.

Fast mode will alternate between simultaneous idling and individual idling to have you receive your trading cards as fast as possible: 
- https://github.com/JonasNilson/idle_master_extended/wiki/Fast-mode
