### ISSUE TITLE
Just says idling complete

### ISSUE THREAD

**Issue by TheMuscialGamer** [JonasNilson/idle_master_extended#40]
I just downloaded it and did all the steps and all it says is idling complete

**Comment by JonasNilson** [comment]
And how many games do you have card drops available for? Look under your Badges page.

**Comment by pngacc** [comment]
I have same problem. Badges page doesnt show all games. I did grab free games for a limited time like Nephise Begins, Mobile Astro EX Pack, HELLION, Barro and more. (Still free btw.) These games has a steam cards. I never played this games and idle still says iddling complete. @JonasNilson

**Comment by JonasNilson** [comment]
@pngacc 

If the game is not in your badge page Idle Master won't idle it automatically.

Also free games don't make your eligeable for card drops: https://github.com/JonasNilson/idle_master_extended/issues/38#issuecomment-604059701
