### ISSUE TITLE
Idling is always complete, and I haven't gotten any cards (1.9)

### ISSUE THREAD

**Issue by CrackSniffer27** [JonasNilson/idle_master_extended#401]
I'm not exactly sure how this happens, but whenever I try to use idlemaster, I can't seem to get any cards
I've done all the necessary steps, I've logged in with the correct info and left steam open
But I can't seem to get anything

**Comment by CrackSniffer27** [comment]
SOLVED

**Comment by jonas-med-ett-s** [comment]
> SOLVED

@CrackSniffer27 Can you provide more information about what solved your issue? It can be valuable for future referencing.
