### ISSUE TITLE
[BUG] Taking 10+hr for a single card

### ISSUE THREAD

**Issue by stratzilla** [JonasNilson/idle_master_extended#403]
## Describe the bug ##
I noticed this first happened with the Sakura Humble Bundle on Feb 10th, I bought the bundle, redeemed, and began idling with Idle Master Extended v1.9 using these settings:

![image](https://user-images.githubusercontent.com/12878452/225760893-8064863d-d54c-4c2c-b9fe-1d80b712265d.png)

It took about 6 hours for the first card to drop, but one of the titles was 17 hours before the first card dropped for it. It ended up taking 22 hours of idling.

A few bundles inbetween then and now have always been super delayed. I'm idling right now and it's on hour three over 13 games and not one has dropped yet. Previously I'd get the first few cards within 15-30min, and be completely done idling every game around 3.5-6 hours. Now I'm noticing those are the minimum...

Any ideas?

**Comment by jonas-med-ett-s** [comment]
Sorry for the late reply. In short the Steam servers handle all card drops so Idle Master Extended cannot speed them up beyond `Fast Mode`.

Some information is available in the FAQ: [Why are the card drops so slow? I have waited hours!](https://github.com/JonasNilson/idle_master_extended/wiki/FAQ#why-are-the-card-drops-so-slow-i-have-waited-hours)

My guess is that the game developer have requested the card drops to be slow from Steam. But if this affecting more than these particular games I would get in contact with the Steam support.
