### ISSUE TITLE
[BUG] I haven't gotten any trading cards since I downloaded the application

### ISSUE THREAD

**Issue by n0tsagg** [JonasNilson/idle_master_extended#404]
I have games with more than 3 hours of idling and it didn´t give me any cards.

![Screenshot (419)](https://user-images.githubusercontent.com/128245850/226120767-74c8b708-5f4a-45c7-ac50-a69230c1f25a.png)

I have the same quantity of card drops all the time. but the hours of the games are increasing.

![Screenshot (420)](https://user-images.githubusercontent.com/128245850/226120777-a6fbb93f-21ee-4c31-ac22-32c794955838.png)

**Comment by n0tsagg** [comment]
SOLVED:

Only the games with more than 3 hours started to give me trading cards.

**Comment by xlh11** [comment]
why some of the games dont  idling?

**Comment by jonas-med-ett-s** [comment]
> SOLVED:
> 
> Only the games with more than 3 hours started to give me trading cards.

Glad to hear you sorted it out. The required hours for cards to drop are fully controlled by Steam.
