### ISSUE TITLE
[BUG] Steam Library issues

### ISSUE THREAD

**Issue by TheUmuRR** [JonasNilson/idle_master_extended#408]
I had some games on steam that did not find cards in the idle master, I took their cards out and sold them, but when I entered the current library, the games seem to be installed even though I installed them and they are not deleted, but I did not install any of them, what should I do, they just stand there and this is annoying. Sorry for my bad english

**Comment by jonas-med-ett-s** [comment]
Can you provide some screenshots of the issue you are experiencing?

> when I entered the current library, the games seem to be installed even though I installed them

It sounds like Steam thinks you have them installed - what happens if you restart Steam?

**Comment by TheUmuRR** [comment]
> Can you provide some screenshots of the issue you are experiencing?
> 
> > when I entered the current library, the games seem to be installed even though I installed them
> 
> It sounds like Steam thinks you have them installed - what happens if you restart Steam?

 Thanks for your idea. i cleared the download cache and restarted steam i solved my problem i think steam thought it was seriously downloaded as you said but when i cleared the cache from the settings and restarted it was completely fixed. Thanks for your idea
