### ISSUE TITLE
Idle only choosen games

### ISSUE THREAD

**Issue by namivan89** [JonasNilson/idle_master_extended#410]
I use IdleMaster for a long time and I trust it, so maybe... Will be there any future options that the IdleMaster could only idle those games what I've choosen from my steam library?

(yeah, for boost hours)

**Comment by jonas-med-ett-s** [comment]
Sounds like you could use Whitelist mode: https://github.com/JonasNilson/idle_master_extended/wiki/Whitelist-mode
