### ISSUE TITLE
[BUG] <THANKS FOR STEAL ALL MY CS:GO ITENS>

### ISSUE THREAD

**Issue by Dayvd24** [JonasNilson/idle_master_extended#411]

**Comment by jonas-med-ett-s** [comment]
You need to provide some more information regarding this issue. Idle Master Extended has nothing to so with CS:GO skins.

1. How is this related to Idle Master Extended?
2. What account received all your skins? Do you have a screenshot of the trade made? If it is an account called JonasNilson or similar I suspect it's a fake account.

You should probably change your account password and add SteamGuard to your account.
