### ISSUE TITLE
What is Trojan.Malware.300983.susgen?

### ISSUE THREAD

**Issue by Charlesjara** [JonasNilson/idle_master_extended#416]
I just want to know that idle master is safe because I checked on virus total and it says that it zip folder has a virus.
Again, I only want to know if it's safe to use.

**Comment by jonas-med-ett-s** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/FAQ#why-is-idle-master-extended-marked-as-malware

**Comment by Charlesjara** [comment]
Thanks, I guess that I should believe it.
