### ISSUE TITLE
[BUG] Metro: Last Light Complete Edition idle master does not detect the game

### ISSUE THREAD

**Issue by miguelroigtv** [JonasNilson/idle_master_extended#417]
Good morning, I have this problem. I have obtained the game Metro: Last Light Complete Edition, and idle master does not detect the game for me to obtain the trading cards [https://imgur.com/a/xVBCpHf](url)

**Comment by Gardemi14** [comment]
This is not a bug. Metro is a free game and free games there is no way to get cards. 

https://twitter.com/SteamDB/status/1106605724078084096

**Comment by miguelroigtv** [comment]
> This is not a bug. Metro is a free game and free games there is no way to get cards.
> 
> https://twitter.com/SteamDB/status/1106605724078084096

Thank you very much for the information, it had not occurred to me that this was the reason.
Have a good day when you read this message.
