### ISSUE TITLE
Whitelist

### ISSUE THREAD

**Issue by zieluu1** [JonasNilson/idle_master_extended#418]
card farm through whitelist mode and it is impossible to mine in turn, only 10 games are launched at once, I will not get any restrictions for this?

**Comment by jonas-med-ett-s** [comment]
I'm not sure if I understand your question, so please elaborate if I understand it incorrectly.

You can farm cards through the Whitelist mode, the games are controlled by the list in the application under `File > Whitelist`. The number of games you can add to the Whitelist is not actually limited but idling the games are limited to 30 games.
