### ISSUE TITLE
[Feature Request] Whitelist mode + custom idle time

### ISSUE THREAD

**Issue by cybersteel8** [JonasNilson/idle_master_extended#42]
I don't know if Idle Master is the right app to do this, but I want to idle in a game for a certain amount of time without having it physically running. I have over a thousand games so it's impractical to blacklist all of them except one, plus I expect that I won't be able to idle in a game after all my card drops are obtained as well.

This could be resolved with a whitelist mode, and a field to input a number of hours to idle. I could whitelist the game I want to idle, and set the custom idle time to x hours, or 0 for unlimited.

Is this feasible? Is this within scope of this tool or is there a better tool that already does this?

**Comment by JonasNilson** [comment]
@cybersteel8

It's a feasible idea. I won't be able to implement it any time soon though.

For now you can try using steam-idle bundled with Idle Master: https://github.com/JonasNilson/idle_master_extended/issues/36#issuecomment-596105776

**Comment by routerabfrage** [comment]
There are different Programms like 
https://github.com/Ezzpify/HourBoostr
they have Fearures like that but if Idle-Master would had that it would be better!

**Comment by JonasNilson** [comment]
A whitelist mode was added in the latest release:
* https://github.com/JonasNilson/idle_master_extended/releases
