### ISSUE TITLE
[BUG] Not Loading Games, Tried all methods.

### ISSUE THREAD

**Issue by BrentanRath** [JonasNilson/idle_master_extended#420]
## Describe the bug ##
I have started using this for a day now. When I came back from turning my PC off for the night, it said Steam was not connected. Me being confused I went to the Wiki, and I made sure it was not running as an administrator, then I tried the ignore client status method. I thought that worked, but when I started it up, it was not running the game.

![furry_shot_00043422](https://github.com/JonasNilson/idle_master_extended/assets/68347504/822224f8-d149-496f-aeff-747b06ed41fb)

**Comment by jonas-med-ett-s** [comment]
Hello, it looks like that Idle Master Extended is unable to start `steam-idle.exe` to run the game process on your system (you can see that the application prints `... 0 idle now` as the status). 

1. Do you have any output in a `error.log` file right next to `IdleMasterExtended.exe` that you are running?
1. Does it help to clear your application data for Idle Master Extended? Read more on it here: [Delete configuration fiels](https://github.com/JonasNilson/idle_master_extended/wiki/Delete-configuration-files)
1. Do you see any subprocesses under `IdleMasterExtended` for `steam-idle` when looking under Windows Task Manager? (see image below)

I have not been able to reproduce the issue myself yet:
- ![image](https://github.com/JonasNilson/idle_master_extended/assets/5990550/e68b28ee-b107-4da0-ae13-9f522551f3e4)

**Comment by schdie** [comment]
Same issue here.
1. Nothing on the log.
2. No changes after clearing the config data.
3. No subprocesses.

It was working fine like always and I didn't do any changes to the setup.

edit: it fixed itself some days later. I didn't change anything, it just worked.

**Comment by Badstormer** [comment]
Same issue here, been trying on and off for weeks to tinker with settings and nothing seems to trigger the idling.

This is all the window tells me:

![image](https://github.com/JonasNilson/idle_master_extended/assets/61914412/37a5b19b-9e17-4d42-a9a3-bc17eb5641c6)

The cutoff on the bottom of the image is actually where the window ends.

This error log is present in the installation directory.

[error.log](https://github.com/JonasNilson/idle_master_extended/files/13288705/error.log)

**Comment by SteamDeckEnjoyer** [comment]
had same issue openning 2 idlemasterextended.exe and some spam on steam-idle.exe worked for me
![Ekran Alıntısı](https://github.com/JonasNilson/idle_master_extended/assets/100497775/cf9c44be-243c-4a6e-b1dc-a474e07bd6eb)

**Comment by Badstormer** [comment]
Despite the official instructions specifying that idlemaster shouldn't run elevated, running the program as an administrator seems to have fixed the issue in my case.

I noted the following line in the error.log:

> System.UnauthorizedAccessException: Access to the path 'C:\WINDOWS\system32\steam_api.dll' is denied.

I figured this was an access rights issue, and, sure enough, running idlemaster elevated fixed it.

I'm not running Steam as an administrator (as far as I can tell, anyway, as it isn't asking for elevation on launch), so I'm not sure what else could be causing this.
