### ISSUE TITLE
Question about idling modes

### ISSUE THREAD

**Issue by awddawawd** [JonasNilson/idle_master_extended#425]
Hello,

I was wondering about all those idling options, I saw that it's possible to run all the games at once beside run one at a time.
How is this not faster ? I mean we are really tasking 100 times more if we have a 100 games to idle.

What does the fast mode different than the other options ?

And in my case where I have 100 games left to idle, which one is the best for me : 
- fast mode
- up to 2 hours then individually
- all simultaneously

Thanks for reading.

**Comment by jonas-med-ett-s** [comment]
Fast mode was developed to try and get the card drops as fast as possible, but how fast it is depends on your account status at Steam and the requirements the game developers have set for their game to drop cards. For some games you can get cards within 15 minutes, while others will require an hour or two, possibly three.

Previously you could not get card drops before reaching the limit of refundability at 2 hours of gameplay.

So in short,

- Fast mode: idle games simultaneously for 15 minutes, start each game individually for 5 seconds, and repeat until all cards have dropped. [Read more on the wiki page](https://github.com/JonasNilson/idle_master_extended/wiki/Fast-mode)
- If your account require 2+ hours of gameplay (most likely if you have refunded games previously) it is best to run them simultaneously until that limit is reached and then switch to fast mode
- Running games individually is mainly to avoid spamming game started notifications to your friends
