### ISSUE TITLE
IDLE MASTER EXTENTED ONLINE? 

### ISSUE THREAD

**Issue by Sharpyku** [JonasNilson/idle_master_extended#428]
Any idea if there is a site that is has something like "IDLE MASTEREXTENDED" FARMING, I mean I don't have to keep my computer on 24/7 anymore but there should be a service that you pay for and log in and make cards .. like*freehourboosting*

**Comment by jonas-med-ett-s** [comment]
I have seen some services that offer hour boosting, but I have no idea if they are legit since I haven't tried them myself.
