### ISSUE TITLE
[BUG] <Put a descriptive title here>

### ISSUE THREAD

**Issue by Dinorexagus** [JonasNilson/idle_master_extended#429]
STEAM IS NOT RUNNING 
Idk how can i fix it
![image](https://github.com/JonasNilson/idle_master_extended/assets/141681753/5d378614-7454-40b6-a403-54f0521228b6)

**Comment by jonas-med-ett-s** [comment]
It looks like you are running the executable from a location where the dependencies are not available.

You should unzip the release at a location of your choice and run the executable from there: https://github.com/JonasNilson/idle_master_extended/wiki/Get-started
