### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by ch3cky** [JonasNilson/idle_master_extended#43]
I simply cannot login into my steam account, it opens the window and after auto-login nothing happens.

**Comment by JonasNilson** [comment]
@ch3cky: Can you provide a screenshot of the issue?

You can likely bypass the issue by using this method:
* https://github.com/JonasNilson/idle_master_extended/issues/27#issuecomment-577597720

But also look here:
* https://github.com/JonasNilson/idle_master_extended#troubleshooting-and-common-solutions

**Comment by ch3cky** [comment]
There is nothing to screenshot tbh, but the cookie editor method fixed it.

**Comment by JonasNilson** [comment]
@ch3cky

You said "after auto-login nothing happens", so I was wondering if the browser window was still open or if Idle Master didn't manage to get the badge page.

**Comment by ch3cky** [comment]
the login window appears, it will QuickLogin to my account, then close the window, but IM won´t actually connect with my account.

**Comment by JonasNilson** [comment]
@ch3cky

Do you get any output in the `error.log`?

**Comment by jurcimat** [comment]
I have same problem as @ch3cky. The output of error.log is this:

System.NullReferenceException: Object reference not set to an instance of an object.
   at IdleMaster.frmBrowser.tmrCheck_Tick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by JonasNilson** [comment]
@jurcimat

Interesting. I wish the error could show the line of code that contained null..

**Comment by lancelotnick** [comment]
i hv the same situation it just pop out 'idle master is saving your information and nothing happen.

**Comment by JonasNilson** [comment]
@ch3cky @jurcimat @lancelotnick Are you still experiencing this issue of not being able to log in?

You could try and use this method by extracting existing Steam cookies: https://github.com/JonasNilson/idle_master_extended/issues/27#issuecomment-577597720

**Comment by lancelotnick** [comment]
I can use it now after using the methods,thx a lot

「Jonas Nilson <notifications@github.com>」在 2020年4月22日 週三，01:10 寫道：

**Comment by JonasNilson** [comment]
Get back to me in a separate issue if the latest release is not working:
* https://github.com/JonasNilson/idle_master_extended/releases
