### ISSUE TITLE
[BUG] <no reconoce que tengo mas juegos> me dice que tengo 1 un juego pero en realidad tengo muchos mas y no se porque pasa esto aunque farmeo el juego en si, pero no dectecta los demas tengo aproximadamente 23 juegos con cromos porfavor una solucion rapida gracias... me pueden escribi por mi gmail.

### ISSUE THREAD

**Issue by isamaik403** [JonasNilson/idle_master_extended#430]
## Describe the bug ##
(A clear and concise description of what the bug is)

## To Reproduce ##
(Steps to reproduce the behavior)

Example:
1. Click on '....'
1. Scroll down to '....'
1. See error

## Expected behavior ##
(A clear and concise description of what you expected to happen)

## Error logs ##
(Look in the `Idle Master Extended` directory for `error.log`)

## Screenshots ##
(If applicable, add screenshots to help explain your problem. **TIP**: Use Windows `Snipping Tool` and paste here)

## Additional context ##
(Add any other context about the problem here)

**Comment by jonas-med-ett-s** [comment]
Make sure you are eligible for card drops: https://github.com/JonasNilson/idle_master_extended/wiki/Idling-complete

**Comment by isamaik403** [comment]
Gracias pero ya solucioné el problema pero igual gracias por contestarme

**Comment by Ramdomwxdx** [comment]
tengo el mismo problema tengo vaarios juegos con cromos pero me dice que solo tengo un juego si alguien me puede ayudar aquie esta m correo (amongusxddgamer@gmail.com).
