### ISSUE TITLE
Idling Complete.

### ISSUE THREAD

**Issue by Tufan-19** [JonasNilson/idle_master_extended#44]
![{9F621CA3-102A-4CAC-BE3B-97E9DE6A0438} png](https://user-images.githubusercontent.com/63352599/78786177-31a46c00-795d-11ea-81e2-750246553dd9.jpg)

When i Open Idle Master it says Idling Complete and I have Cards.

**Comment by JonasNilson** [comment]
How many games do you have with available card drops? Please check under your badge page (https://steamcommunity.com/id/<steamid>/badges/)

**Comment by Tufan-19** [comment]
> How many games do you have with available card drops? Please check under your badge page (https://steamcommunity.com/id/<--steamid-->/badges/)
> 
> Free games will not give your card drops: [#38 (comment)](https://github.com/JonasNilson/idle_master_extended/issues/38#issuecomment-604059701)

![Capturekos](https://user-images.githubusercontent.com/63352599/78892977-36c9ef80-7a1f-11ea-98b0-3e376ac25fa0.PNG)

These are the games.

**Comment by Tufan-19** [comment]
Blood and Bacon And Garrysmod isn't free.

**Comment by JonasNilson** [comment]
> Blood and Bacon And Garrysmod isn't free.
> 

I'm not sure why you don't have card drops available, but that is not something Idle Master can help with

**Comment by Tufan-19** [comment]
@JonasNilson They are available it just says that.

**Comment by Tufan-19** [comment]
there might be something wrong with the idle master.

**Comment by JonasNilson** [comment]
@Tufan-19

Based on your screenshot there are no cards available and you already have hours played in those games. Maybe you've already received them?

**Comment by Tufan-19** [comment]
@JonasNilson i just bought these games recently like a month or so. And i haven't received not one card drop.

**Comment by JonasNilson** [comment]
@Tufan-19 

I would recommend contacting Steam support to get a better grasp of the issue.

**Comment by Tufan-19** [comment]
@JonasNilson i contacted them they said to me that u didn't earn a card drop because you haven't even earned them yet so there isn't a problem in my account they said.
