### ISSUE TITLE
[SUGGESTION] Make it possible to idle games just to get more hours even if there are no more card drops

### ISSUE THREAD

**Issue by mrlolua19** [JonasNilson/idle_master_extended#440]
Please make it is possible to just select a game and then it will idle it even if there are no more drops for it. I just want to get more hours in some game and dont want to spend too much electricity for keeping it running. I will really appreciate it

**Comment by LazyDevv** [comment]
+1

**Comment by DocPaint** [comment]
+1

**Comment by Badstormer** [comment]
Sounds fitting for a program called "idle master".

**Comment by ghost** [comment]
it's already a thing, use the whitelist feature

**Comment by jonas-med-ett-s** [comment]
https://github.com/JonasNilson/idle_master_extended/wiki/Whitelist-mode
