### ISSUE TITLE
[SOLVED] Can't longer login into IDM

### ISSUE THREAD

**Issue by dxdpxl** [JonasNilson/idle_master_extended#449]
Since today I can't longer login into IDM "The data you've entered isn't valid". Two days ago, everything worked fine and I did not change anything. I've deleted all cookies, made multiple restarts but nothing. I also see only sessionid and steamLoginSecure and all the others, but theres no steamParental cookie field nor a steamMachineAuth and there never was, because it always worked with these two. Did steam changed something to block IDM in any way?

❗ For now there is a » [workaround](https://github.com/JonasNilson/idle_master_extended/issues/449#issuecomment-1900094578) « so I'm closing this. Renamed the title be more clear.

**Comment by pederbe** [comment]
I today have the same issue, with the same error message. 

I also don't have steamParental nor a steamMachineAuth cookie.

**Comment by Nazar1ky** [comment]
Steam have updated. The session cookie is now different per domain. Not sure, if it regarded to that issue.

**Comment by dxdpxl** [comment]
> Steam have updated. The session cookie is now different per domain. Not sure, if it regarded to that issue.

Could be. Can't find any information about that. Could you pls post a source? There's no mention of this in the last two Steam client update posts from January.

**Comment by Nazar1ky** [comment]
> > Steam have updated. The session cookie is now different per domain. Not sure, if it regarded to that issue.
> 
> Could be. Can't find any information about that. Could you pls post a source? There's no mention of this in the last two Steam client update posts from January.

I founded that on ArchiSteamFarm Discord server.

**Comment by dxdpxl** [comment]
> I founded that on ArchiSteamFarm Discord server.

Ok. Never heard about that 🤷🏻‍♂️

**Comment by Nazar1ky** [comment]
> > > Steam have updated. The session cookie is now different per domain. Not sure, if it regarded to that issue.
> > 
> > 
> > Could be. Can't find any information about that. Could you pls post a source? There's no mention of this in the last two Steam client update posts from January.
> 
> I founded that on ArchiSteamFarm Discord server.

Try get Session_id here: https://steamcommunity.com/ 
The Session_Id is different now on Store and on Community

**Comment by dxdpxl** [comment]
> Try get Session_id here: https://steamcommunity.com/ The Session_Id is different now on Store and on Community

Great, that worked! Big thanks to you!

**Comment by Werloz** [comment]
> > > > Steam have updated. The session cookie is now different per domain. Not sure, if it regarded to that issue.
> > > 
> > > 
> > > Could be. Can't find any information about that. Could you pls post a source? There's no mention of this in the last two Steam client update posts from January.
> > 
> > 
> > I founded that on ArchiSteamFarm Discord server.
> 
> Try get Session_id here: https://steamcommunity.com/ The Session_Id is different now on Store and on Community

Thx! 💗
