### ISSUE TITLE
Steam is not running

### ISSUE THREAD

**Issue by JUN10R62** [JonasNilson/idle_master_extended#45]
It is running but the system says it isnt

**Comment by JonasNilson** [comment]
@JUN10R62

Can you provide a screenshot of the issue?

**Comment by JUN10R62** [comment]
![image](https://user-images.githubusercontent.com/63371915/78898711-8981c680-7a74-11ea-803b-d71563676527.png)

**Comment by JonasNilson** [comment]
@JUN10R62 

What version are you using? The latest version is available here: https://github.com/JonasNilson/idle_master_extended/releases/latest

* I am not able to reproduce the issue at the moment.
![image](https://user-images.githubusercontent.com/5990550/78929787-47bc4480-7aa3-11ea-97e1-93fc94396378.png)

* One quick-fix is to go to `File > Settings > Ignore Steam client status`
![image](https://user-images.githubusercontent.com/5990550/78930016-a97cae80-7aa3-11ea-93ec-e738b919df45.png)

* Or you could try and look into the common fixes here: https://steamcommunity.com/groups/idlemastery/discussions/0/133257636766989675/

**Comment by Tufan-19** [comment]
@JonasNilson u didn't reply on my issue

**Comment by Beridok** [comment]
The issue is when you launch Steam with Admin priviledges and Idle Master Extended without them.

Run both apps without or with Admin priviledges.

**Comment by False-Steel** [comment]
olá, meu idle está com problema, quando eu entro, além de dizer que a steam não está funcionando quando ela está, nem o botão de login na steam nem o de abrir configurações funciona, eu clico e eles não respondem, alguém poderia me ajudar? já tentei desinstalar e instalar novamente, e também procurei no youtube, mas não achei a solução em lugar nenhum
![image](https://user-images.githubusercontent.com/86327517/123004867-9cd43580-d38b-11eb-8b54-5c4604dcab15.png)
