### ISSUE TITLE
[BUG] Manual Login Method not wotking anymore

### ISSUE THREAD

**Issue by 0lm** [JonasNilson/idle_master_extended#450]
## Describe the bug ##
As always, copied sessionid and steamLoginSecure, but it says "The data you have entered isn't valid. Please try again"

## To Reproduce ##
copy and paste sessionid and steamloginsecure (for example use Cookie-Editor on Firefox)

## Expected behavior ##
Logs in normally, as for days ago.

## Error logs ##
Error Message
"The data you have entered isn't valid. Please try again"

**Comment by Nazar1ky** [comment]
Duplicate issue. https://github.com/JonasNilson/idle_master_extended/issues/449

**Comment by 0lm** [comment]
Ah sorry, not sure how I didn't see that closed issue. Thank you for informing me! Gonna close this now.
