### ISSUE TITLE
Steam Login Loop

### ISSUE THREAD

**Issue by aerCreativity** [JonasNilson/idle_master_extended#46]
[Disclaimer] I have been unable to replicate this issue.

A friend has had a random issue where the account would finish the quick-login or normal Steam login, and then return back to the Steam login page.
(It's also not particularly urgent, as this issue has only occurred on one computer and has resolved itself magically after a fresh reboot. Strange.)

This issue is similar to the other ["cannot log in" issue](https://github.com/JonasNilson/idle_master_extended/issues/43#issuecomment-606816815), but has a different error log, as shown below.
https://pastebin.com/rpJzQDwm

**Comment by JonasNilson** [comment]
Thanks for the error log.

Definitely looks like an issue while accessing the HTML elements, based on:
```
Member 'System.DBNull.Value' cannot be accessed with an instance reference; qualify it with a type name instead
   at CallSite.Target(Closure , CallSite , Object , String )
   at IdleMaster.frmBrowser.setLoginButtonText(Object htmldoc, String text)
```

I'll add a bug label to this issue.

**Comment by JonasNilson** [comment]
This has been handled in the latest release:
* https://github.com/JonasNilson/idle_master_extended/releases
