### ISSUE TITLE
I put the correct sessionid and steamloginsecure and it appears idle master isnt working

### ISSUE THREAD

**Issue by Ghostly-Vessel** [JonasNilson/idle_master_extended#461]
So when i was trying to idle games after a while to be able to get some extra money on steam i did everything acordingly and its just not working for some reason
it says data isnt correct but it is
also i dont have steam parental or steammachineauth so i dont know what to do

**Comment by m1s3ry** [comment]
Same problem here. Yesterday all worked fine. Opened idle_master today and found it logged me out. Re-entered my sessionid and steamLoginSecure cookies but it says the data entered isn't valid

**Comment by Ghostly-Vessel** [comment]
oh i found the issue already
turns out the cookies from store.steampowered.com dont work
you have to use the cookies from steamcommunity.com

**Comment by triangleXIV** [comment]
> oh i found the issue already turns out the cookies from store.steampowered.com dont work you have to use the cookies from steamcommunity.com

Thank you for your method! I successfully logged in using cookies from steamcommunity.com
