### ISSUE TITLE
[BUG] cant sign in because steammachineauth doesnt exist

### ISSUE THREAD

**Issue by hhoneeyy** [JonasNilson/idle_master_extended#462]
it doesnt appear in the cookies tab

**Comment by TakashiHafuza** [comment]
same

**Comment by davinidae** [comment]
open the DevTools from https://steamcommunity.com/ instead of https://store.steampowered.com or any domain related to steampowered.com

**Comment by TakashiHafuza** [comment]
works on me tysm

**Comment by hhoneeyy** [comment]
> open the DevTools from https://steamcommunity.com/ instead of https://store.steampowered.com or any domain related to steampowered.com

still doesn't exist, tried on both firefox and chrome

**Comment by davinidae** [comment]
> > open the DevTools from https://steamcommunity.com/ instead of https://store.steampowered.com or any domain related to steampowered.com
> 
> still doesn't exist, tried on both firefox and chrome

You don't need steamMachineAuth, it's optional. Just use the credential from https://steamcommunity.com/ and it will work.

**Comment by hhoneeyy** [comment]
it works now, thanks.
