### ISSUE TITLE
Be able to run games from Family Library Sharing

### ISSUE THREAD

**Issue by Trol0lvl** [JonasNilson/idle_master_extended#472]
Don't know is there an issue, but since steam Family Library Sharing policy was changed, people can run games on other steam accounts, and it is counts as if you were bought this game. 

As you see on screenshoot cards are available.

![1](https://github.com/JonasNilson/idle_master_extended/assets/129762486/6e54a01d-3549-44f7-8ea0-1afa5b5e27dc)

Hope you'll figure it out.
Regards.

**Comment by Yurkhun** [comment]
as far as I know you can't drop cards from other people library in steam family library sharing, that's just showing how many cards you need to make the badge not that you will get drops from playing the game

**Comment by Trol0lvl** [comment]
looks like you are right, that's shame... so as I inspect, you cannot obtain any card

![2](https://github.com/user-attachments/assets/79c88b2e-04d8-4b77-afe0-e6e0d6fed078)

It should be like this instead

![3](https://github.com/user-attachments/assets/472e6f99-3034-4915-8389-d8613f147ff9)
