### ISSUE TITLE
[BUG] Idle Master Extended is broken

### ISSUE THREAD

**Issue by SonixFanx** [JonasNilson/idle_master_extended#475]
Just see the image and you'll see how it looks.
Idk why this happened, but i want a fix :(

![image](https://github.com/JonasNilson/idle_master_extended/assets/55793483/e9f3252d-26b2-46f1-a45c-420cd2e67142)

**Comment by Trol0lvl** [comment]
try to restart or re-download/re-unpack

**Comment by SonixFanx** [comment]
> try to restart or re-download/re-unpack

already tried, didn't work :/
anyways, thanks!

**Comment by SonixFanx** [comment]
Ok, after reading the error logs, i just got to the folder that was doing the error
C:\Users\Usuario\AppData\Local\IdleMasterExtended\IdleMasterExtended.exe_Url(for the 1.10.0 ver.)
and deleted the folder related to the 1.10.0 version, now it's working
I have now uploaded the image just so anyone who has the problem knows the directories

![image](https://github.com/user-attachments/assets/ea54a0a7-8dc5-4eb2-aa8c-8ec61c7f9c62)
