### ISSUE TITLE
> I just experienced this issue myself. And it seems you can put in the `steamMachineAuth` cookie in place of the `steamParental` cookie:

### ISSUE THREAD

**Issue by ErtasmisOlcay** [JonasNilson/idle_master_extended#477]
> I just experienced this issue myself. And it seems you can put in the `steamMachineAuth` cookie in place of the `steamParental` cookie:
> 
> * ![image](https://user-images.githubusercontent.com/5990550/178150404-2a55d8b5-574e-4f02-92ab-17c7ae5614cd.png)
> * ![image](https://user-images.githubusercontent.com/5990550/178150520-1e089595-b1b0-4936-b949-deb1f0455909.png)
> 
> @adminerest Do you have a source for that information? I would love to read up more on it

I have not been able to log in for a long time. I am getting the error "The data you entered is invalid, please try again". I tried again today with hope and the same error. Then I tried again with hope, turning on family protection and trying steamparental, but I still get the same error. No matter what I do, I can't find a solution.

![image](https://github.com/user-attachments/assets/de12c1c7-7025-40ad-b7aa-ae3d8b464f87)

_Originally posted by @ErtasmisOlcay in https://github.com/JonasNilson/idle_master_extended/issues/314#issuecomment-2230538828_

**Comment by AsukajustAsuka** [comment]
NOTE: Steam Store cookies does not work,you need to move to the other sections of the page, such as “Community”.

**Comment by kyle1046** [comment]
i was able to get mine to work with some tickery i had to go back to "Idle Master Extended v1.8-BETA" click settings then the lock and enter the cookies and it was able to login i then went and closed the "V1.8-beta" and opened "V1.10" for a few seconds to generate the config file for it then if you go to "AppData\Local\IdleMasterExtended" you will see folders labled "IdleMasterExtended.exe_Url_******************" if you open those folders you will find one of the folders labled "1.8.0.0" inside that folder is the config file you need to copy that file and then find the folder labled "1.10.0.0" and replace the exising config file with the one you copyed at which point you can reopen "Idle Master Extended v1.10" and you will be logged in
