### ISSUE TITLE
Just wanted to ask which Games we should add to Black List!

### ISSUE THREAD

**Issue by DeePSleeP44** [JonasNilson/idle_master_extended#51]
I just afraid to get VAC ban because of that, which games we should add to black list ? Anyone have anything to say about it ?

**Comment by dyroski** [comment]
I don't think you can get vac banned using this, so I would say go ahead and use it on any game you want.

**Comment by DeePSleeP44** [comment]
I just heard something about it, they just told don't use VAC protection games in any case. Just wanna be sure from everything is okey with it.

**Comment by DeePSleeP44** [comment]
https://steamcommunity.com/groups/idlemastery/discussions/0/152392786912268315/
![ID](https://user-images.githubusercontent.com/64228701/80249268-33b73c00-867a-11ea-8fca-0149ab3ac11b.PNG)
