### ISSUE TITLE
Attempting to quick login and not asking for steam guard code

### ISSUE THREAD

**Issue by sa3d3** [JonasNilson/idle_master_extended#52]
I tried clearing cookies but the issue persists. It doesn't ask for code and simply proceeds to log in (but fails obviously)

**Comment by JonasNilson** [comment]
What part of the login process fails? Do you have a screenshot of the issue?

**Comment by GrimmReaperXD** [comment]
@sa3d3 Go to setting and turn off quick login option. I had the same issue as you and it solved after I turned it off
