### ISSUE TITLE
Не работает

### ISSUE THREAD

**Issue by Grinvichon** [JonasNilson/idle_master_extended#53]
При входе в программу пишет что идёт процесс но нечего не происходит
![image](https://user-images.githubusercontent.com/37119856/80287836-5c076f00-873c-11ea-8414-a740b877adda.png)

**Comment by JonasNilson** [comment]
Can you provide more information? For example:
* How many cards do you have left to receive from idling? Best is to check under your badge page: http://steamcommunity.com/my/badges
