### ISSUE TITLE
in the newest release i click sign in and then it brings me to my profile, shortly after it force quits and on the bottom right it says not in game

### ISSUE THREAD

**Issue by Chillidog36** [JonasNilson/idle_master_extended#56]
add me in discord to show you @ PPP_Chilli dog36#0862

**Comment by JonasNilson** [comment]
Can you provide a screenshot of the issue?

Also look under: https://github.com/JonasNilson/idle_master_extended#troubleshooting-and-common-solutions

**Comment by SliderKP** [comment]
after login correctly i see this again:
http://puu.sh/FNVms/8bea8b9f71.png

for first i need to disable "quick login" option.

**Comment by JonasNilson** [comment]
@SliderKP 

You can probably get past the issue by pasting your Steam cookies: https://github.com/JonasNilson/idle_master_extended/issues/27#issuecomment-577597720 (never post that cookie online though)

**Comment by JonasNilson** [comment]
@Chillidog36 

How many games do you have with card drops remaining?

You can check under: http://steamcommunity.com/my/badges

**Comment by Chillidog36** [comment]
![Uploading E9F4DD04-1903-458B-BC8C-C2C6EB046B70.png…]()

**Comment by Chillidog36** [comment]
![AFD83979-72D0-45F6-AB56-58DB829EF429](https://user-images.githubusercontent.com/65378645/82763685-1091c080-9dcf-11ea-8f8c-9edd7799bad3.png)
![2EBB3D6A-F659-4283-AB8F-D39C985EC5A4](https://user-images.githubusercontent.com/65378645/82763686-112a5700-9dcf-11ea-9b90-ed4a04ac5160.png)

**Comment by JonasNilson** [comment]
Based on that information you can't get card drops from those games. Either you have received them for free, or you have already achieved the cards from them:
* https://steamcommunity.com/tradingcards/faq/
