### ISSUE TITLE
Steam client status

### ISSUE THREAD

**Issue by Chaython** [JonasNilson/idle_master_extended#59]
Says steam is not running when it is.
Does steam have to be installed in a certain directory or something?
If I ignore steam status, it starts runnin games... but they don't actually run if I look at steam

**Comment by JonasNilson** [comment]
> Does steam have to be installed in a certain directory or something?

That should not be necessary, as far as I know.

> If I ignore steam status, it starts runnin games... but they don't actually run if I look at steam

Can you provide a screenshot of the issue? Make sure you are running the latest version: https://github.com/JonasNilson/idle_master_extended/releases

Also, do you have an `error.log` with recent output? It should be in your Idle Master Extended directory:
![image](https://user-images.githubusercontent.com/5990550/82763279-c9bfbd00-9e06-11ea-9401-c01eaf427deb.png)
