### ISSUE TITLE
[Feature Request] Idle any game for a custom amount of time

### ISSUE THREAD

**Issue by jaypordy** [JonasNilson/idle_master_extended#61]
Whether there are  available card drops or not, allow the user to select a game and idle/play it for a given time w/o downloading it.

This is mainly for badges. I have to re-download huge games in order to get these silly badges. Feature like this might come in handy. 

Note: The event ends tomorrow, would be cool if you could mash something out before that.

**Comment by JonasNilson** [comment]
@jaypordy 

It's actually something I've been working on in a separate branch, but it's not ready for release yet.

You can try and use this method to idle any game: https://github.com/JonasNilson/idle_master_extended/issues/36#issuecomment-596105776

**Comment by jaypordy** [comment]
Thanks, you are the man!

**Comment by JonasNilson** [comment]
Some information about this feature is available here: https://github.com/JonasNilson/idle_master_extended/pull/60

Basically you can checkout that branch and build it yourself, but there will be some potential bugs as it's not fully tested yet

**Comment by jaypordy** [comment]
Thanks. Will check it out. Shall I close this issue since it is being tracked on #42 ?

**Comment by JonasNilson** [comment]
@jaypordy Leave it open for a little while. I'll write here once it's done and ready for release

**Comment by jaypordy** [comment]
Roger

**Comment by JonasNilson** [comment]
@jaypordy 

A whitelist mode has been added in the latest release:
* https://github.com/JonasNilson/idle_master_extended/releases
