### ISSUE TITLE
THE FAST MODE DONT WORK FOR ME

### ISSUE THREAD

**Issue by Shadow0104** [JonasNilson/idle_master_extended#65]
The fast mode don't work for my me . I must use Whitelist and after 10h idling i have nothing and then say i idle 3 minutes

**Comment by JonasNilson** [comment]
@Shadow0104 
Can you provide a screenshot of the issue?

And what games do you have in your whitelist?

**Comment by JonasNilson** [comment]
> The fast mode don't work for my me . I must use Whitelist and after 10h idling i have nothing and then say i idle 3 minutes

I need some additional information to work on this.

Do you have any output in `error.log` in your Idle Master Extended directory?

**Comment by Shadow0104** [comment]
hello , here is the screen of the problem .
Pls i love idle master and i want use it help me .
That say reading the badge page and idling complete.
[image: htdthcgf.png]
[image: hydtgbrvsf.png]


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Garanti
sans virus. www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Le lun. 15 juin 2020 à 17:20, Jonas Nilson <notifications@github.com> a
écrit :

**Comment by Shadow0104** [comment]
15/06/2020 21:33:01   CookieClient -> GetHttpAsync, for url =
https://steamcommunity.com/profiles/76561199052272519/badges/?p=1
System.Net.WebException: An exception occurred during a WebClient request.
---> System.NullReferenceException: Object reference not set to an instance
of an object.
   at System.Net.WebClient.DownloadBitsState.SetResponse(WebResponse
response)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
task)
   at
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task
task)
   at IdleMaster.CookieClient.<GetHttpAsync>d__6.MoveNext()

Le lun. 15 juin 2020 à 17:20, Jonas Nilson <notifications@github.com> a
écrit :

**Comment by JonasNilson** [comment]
@Shadow0104 The screenshots does not show up on my end. Can you send them again, preferably through your browser on GitHub instead of mail?
