### ISSUE TITLE
I can't sign in

### ISSUE THREAD

**Issue by dulexezz** [JonasNilson/idle_master_extended#67]
https://drive.google.com/file/d/1nO25i_bQ69iS_AxUEpST-6qiw4tFKGci/view?usp=sharing
Like this

**Comment by eddrdgz** [comment]
I have the same problem, it is updated every moment and does not allow me to log in

**Comment by JonasNilson** [comment]
@dulexezz 

Go to File > Settings and disable quick login

Also, look under the Idle Master Extended directory and look for the `error.log` and provide me with the file content

**Comment by dulexezz** [comment]
@JonasNilson   Oh that work !!  thank you so much <3
