### ISSUE TITLE
It doesn't work for me

### ISSUE THREAD

**Issue by Nerdo-exe** [JonasNilson/idle_master_extended#68]
Hi, For a few days idle master stopped working for me. It does not show me any list of games when before, I use the fast mode and default. I get the following error

![image](https://user-images.githubusercontent.com/67180052/85192103-b124b480-b297-11ea-947d-30ab55267fec.png)

**Comment by JonasNilson** [comment]
@Nerdo-exe 

That error is related to the blacklist and shouldn't affect the list of games.

How many games do you have with cards remaining?

**Comment by Nerdo-exe** [comment]
I have 8 games to get cards yet, which never marked me in the list of games.

**Comment by JonasNilson** [comment]
> I have 8 games to get cards yet, which never marked me in the list of games.

Can you provide a screenshot of the games on your badge page? https://steamcommunity.com/my/badges

**Comment by 20Joseph03** [comment]
Hello, it has not been working for me either, an error appears, and although it is the first time that I download it, it sends me the error 
![01](https://user-images.githubusercontent.com/67622766/86087809-17b58980-ba73-11ea-9db4-c6873f35a856.JPG)

**Comment by JonasNilson** [comment]
> Hello, it has not been working for me either, an error appears, and although it is the first time that I download it, it sends me the error

@20Joseph03 That looks like to be related to the sorting of the badges. Try to change it to the Default sorting:

![image](https://user-images.githubusercontent.com/5990550/86104902-ef537c80-babe-11ea-90b8-891d358ba72a.png)

**Comment by 20Joseph03** [comment]
I found the error, I'm from Chile, so I changed the language to Spanish, so I wanted to check if it was the language that caused the problem. Delete the Language folder and then it won't send me an error, even changing the options that you recommended.

**Comment by 20Joseph03** [comment]
But there is one more thing, how do I know that a game is farming trading cards if nothing appears in the user startup section?

**Comment by 20Joseph03** [comment]
check if you not understant
https://youtu.be/m-hTo5jZ_wQ

**Comment by JonasNilson** [comment]
@20Joseph03

Based on that you don't have any card drops remaining for your games
