### ISSUE TITLE
Latest release gets blocked by windows defender

### ISSUE THREAD

**Issue by Thymue** [JonasNilson/idle_master_extended#69]
![image](https://user-images.githubusercontent.com/26690825/85208427-bb46c180-b330-11ea-8638-6470f55cf7ad.png)

**Comment by JonasNilson** [comment]
@Thymue 

I have not seen this before. Where did you download the zip-file from?

**Comment by Thymue** [comment]
From the releases but it doesn't do that anymore for some reason idk
