### ISSUE TITLE
strange bug

### ISSUE THREAD

**Issue by Lazare-C** [JonasNilson/idle_master_extended#70]
I have strange bug and idle stay blocked

https://i.imgur.com/sgS48cv.png

`23/06/2020 18:43:31   Badge -> LoadBadgesAsync, for profile = https://steamcommunity.com/profiles/*******************
System.Exception: Response is null or empty. Added (+1) to RetryCount
   à IdleMaster.frmMain.CheckIfResponseIsNullWithRetryCount(String response)
   à IdleMaster.frmMain.<GetBadgePageAsync>d__33.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()
23/06/2020 18:45:04   
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à IdleMaster.frmMain.blacklistCurrentGameToolStripMenuItem_Click(Object sender, EventArgs e)
   à System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   à System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   à System.Windows.Forms.ToolStripItem.FireEventInteractive(EventArgs e, ToolStripItemEventType met)
   à System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   à System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   à System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   à System.Windows.Forms.ToolStrip.WndProc(Message& m)
   à System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   à System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

**Comment by JonasNilson** [comment]
@Lazare-C

I have to look more into this. 

How many games do you have card drops remaining for?

**Comment by Lazare-C** [comment]
I still have about 50 badges left to drop.

**Comment by JonasNilson** [comment]
@Lazare-C Did you find a workaround?
