### ISSUE TITLE
Login not working: Javascript must be enabled to use this site

### ISSUE THREAD

**Issue by olivervbk** [JonasNilson/idle_master_extended#73]
When opening Idle Master for the first time, trying to log in, the message appears on the steam login prompt:
Javascript must be enabled to use this site

Then it refreshes and I can't log in.

**Comment by olivervbk** [comment]
Tried the manual login with sessionId and steamLoginSecure, says data is invalid..

**Comment by olivervbk** [comment]
Ah, seems it was because I was running it on Windows Server with the Enhanced Security Configuration enabled.

(Go into Server  Manager, disable Enhanced Security Configuration, restart the Idle Master program.)

**Comment by JonasNilson** [comment]
@olivervbk Thanks for getting back with a solution to the issue 🐱‍💻
