### ISSUE TITLE
idle master farm card only 5 second then jsut stay online

### ISSUE THREAD

**Issue by Ulekar** [JonasNilson/idle_master_extended#74]
idle master dont see all games and i dont talk about free games i talk about games like: dark souls 3, bioshock remastered ,  , borerlands 2 e.t.c

**Comment by Ulekar** [comment]
in error log i have 
28.06.2020 23:57:51   frmMain -> SortBadges -> The method (mostvalue) resulted in an exception
System.Net.WebException: Nie można rozpoznać nazwy zdalnej: 'api.enhancedsteam.com'
   w System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   w System.Net.WebClient.DownloadString(Uri address)
   w System.Net.WebClient.DownloadString(String address)
   w IdleMaster.frmMain.SortBadges(String method)
29.06.2020 00:06:13   frmMain -> SortBadges -> The method (mostvalue) resulted in an exception
System.Net.WebException: Nie można rozpoznać nazwy zdalnej: 'api.enhancedsteam.com'
   w System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   w System.Net.WebClient.DownloadString(Uri address)
   w System.Net.WebClient.DownloadString(String address)
   w IdleMaster.frmMain.SortBadges(String method)
29.06.2020 00:21:48   frmMain -> SortBadges -> The method (mostvalue) resulted in an exception
System.Net.WebException: Nie można rozpoznać nazwy zdalnej: 'api.enhancedsteam.com'
   w System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   w System.Net.WebClient.DownloadString(Uri address)
   w System.Net.WebClient.DownloadString(String address)
   w IdleMaster.frmMain.SortBadges(String method)

**Comment by JonasNilson** [comment]
> idle master dont see all games and i dont talk about free games i talk about games like: dark souls 3, bioshock remastered , , borerlands 2 e.t.c

And among those games, do you have card drops remaining? Check under https://steamcommunity.com/my/badges

**Comment by Ulekar** [comment]
i I repair last problem with dont see all games  but i have new problem. I drop all card from my account but i buy new games , this games have card for example metro exodus i can drop 3 cards ,idle master  normal see this games and try drop cards but after 15 minutes do check satus games.But idle master do this check 6 hours and nothink hapend just stay on check 
I left for the night idle master on drop  only metro exodus when i wake up i see idle master do only 2 minutes  on this game during 6 hours . i saw now when i start idle master on steam i see steam start metro exodus for one  
second and shut down it

**Comment by Ulekar** [comment]
![gif](https://user-images.githubusercontent.com/67562242/86439915-c3780700-bd09-11ea-8deb-04665691f484.gif)

**Comment by Ulekar** [comment]
and alltime was onnline all time no in game to restart program but after second it do it again restart pc dont help , windows 
Troubleshooting with intenret doesnt help ,

**Comment by Ulekar** [comment]
and its stay online to restart program so idle master farm card alltime for only 1-2 second 
i have this problem since yesterday

**Comment by Ulekar** [comment]
i repired this problem to its my internet  fault so can close
