### ISSUE TITLE
Sign-in issues

### ISSUE THREAD

**Issue by VorgonBattlecruiser** [JonasNilson/idle_master_extended#75]
When clicking "Sign-in" and steam is on it connects itself successfully. After a while it signs itself out, even though Steam is still running.

Signing in manually is not possible. It opens the Sign-in page. If i am not fast enough it quickly erases everything in username and password.

If i very quickly manage to copy and paste both i get to the Steam Guard-screen, but that closes itself again about 1 or 2 seconds after.

**Comment by Roqche** [comment]
I have the same issue.

**Comment by Gomze** [comment]
Same issue

**Comment by JonasNilson** [comment]
@VorgonBattlecruiser 

You can try to disable Quick-login under File > Settings > General > Quick login

**Comment by JonasNilson** [comment]
If you are still experiencing login issues you could insert your cookie data from your browser: https://github.com/JonasNilson/idle_master_extended/issues/27#issuecomment-577597720
