### ISSUE TITLE
games doesnt show

### ISSUE THREAD

**Issue by Flojsyk** [JonasNilson/idle_master_extended#76]
Hello, if i downlaod idle master, i will extract it on the desktop, launch it in administrator ( i tried also without it ) and when i login into my steam account it doesnt show my games etc. in security settings i have all to public. Can anybody help? thank you

**Comment by JonasNilson** [comment]
@Flojsyk

Do you have card drops remaining for those games?

**Comment by Flojsyk** [comment]
How do you mean it?

**Comment by Flojsyk** [comment]
I think about it and i got games whah are free or what i get from anybody, so i dont know if it is this.

**Comment by JonasNilson** [comment]
@Flojsyk 

https://steamcommunity.com/tradingcards/faq/

**Comment by Flojsyk** [comment]
Ah yeah, it working, thanks for feedback and sorry for your time, bye :)
