### ISSUE TITLE
option "shutdown windows when done" cannot be ticked?

### ISSUE THREAD

**Issue by HotSnack** [JonasNilson/idle_master_extended#77]
so i have used v1.3 before and had that option available right when i launched it
and now when i update it to v1.5 i have to find it in settings
but after ticking "shutdown windows when done" and hit accept, i opened settings again and it shows that it didnt tick for me?
pls fix this bug

**Comment by JonasNilson** [comment]
@HotSnack

Interesting. I will have a look at it.

**Comment by HotSnack** [comment]
i tried to some game when i wrote this and its still turn off my pc tho
but the fact is that it just doesnt tick make me feel confusing
anyway ty for reply

**Comment by JonasNilson** [comment]
> i tried to idle some game when i wrote this and its still turn off my pc tho
> but the fact is that it just doesnt tick make me feel confusing
> anyway ty for reply

Thanks for verifying the functionality. It looks like the checkbox does not take the current state into account, and I will have it fixed for the next release.
