### ISSUE TITLE
Language contribution

### ISSUE THREAD

**Issue by YikesaitingPressE** [JonasNilson/idle_master_extended#78]
Hi there,

I would like to contribute the translation for the Chinese language, how I can I help?

I try to click the translation page, but it won't work.

Thanks!

**Comment by JonasNilson** [comment]
The translation page was made for the original Idle Master, and sadly it is gone. Your best way would be to make the adjustments in the localization directory: https://github.com/JonasNilson/idle_master_extended/tree/develop/Source/IdleMaster/localization

And then make a pull request: https://github.com/JonasNilson/idle_master_extended#contribute

I guess I should remove the dead link...

**Comment by YikesaitingPressE** [comment]
Hi Jonas,

I think I add a pull request to the repo. Sorry for any inconvenience, I haven't use git and coding for a long time, almost forget what I learned...Forgive me if I mess up anything. Please let me know anything I need to do or any corrections I need to make.

Thanks!

**Comment by JonasNilson** [comment]
@YikesaitingPressE Thank you for contributing 👌🏻 I will have a look at the pull request
