### ISSUE TITLE
idling for 9hrs straight still no cards

### ISSUE THREAD

**Issue by ziomii** [JonasNilson/idle_master_extended#80]
I`ve been idling for 9hrs and no cards, still, 22cards remaining as started...

**Comment by JonasNilson** [comment]
Can you provide a screenshot of the issue? And what games do you have that still have card drops remaining?

**Comment by ziomii** [comment]
Sure. the screenshots are here: 
https://prnt.sc/tbene7
https://prnt.sc/tbemwv
https://prnt.sc/tbeo5d

**Comment by JonasNilson** [comment]
@ziomii interesting. Does Steam show you as "in-game"? And does your total play time equal those times in Idle Master Extended?

**Comment by ziomii** [comment]
Yeah, I'm in all the games at once, and the hour's match.

**Comment by JonasNilson** [comment]
@ziomii What idling mode are you using?

**Comment by ziomii** [comment]
It's just regular settings I guess... 
https://prnt.sc/tbfc06

**Comment by avaadorenl** [comment]
Ziommi do you have steam running with status invisible?
i didnt get cards with that, change status to online, and started idle master again, and worked!

**Comment by ziomii** [comment]
Alright man, thanks, gonna try that out.

**Comment by ziomii** [comment]
@avaadorenl Unfortunately that didn't work for me either, Idk what's going on with my steam acc...

**Comment by JonasNilson** [comment]
@ziomii It might be worth opening a support ticket at Steam, so that they can look at your account and see if there is an issue with your card drops

**Comment by ziomii** [comment]
Alright, all I can say at the moment is its not idle master fault or something, for my other acc it worked, but in acc, I have the most cards won't...

**Comment by JonasNilson** [comment]
> I read somewhere that you need to have an actual steam level 5 or higher to get drops is it true tho?

I don't think that's true. The [FAQ on Steam trading cards](https://steamcommunity.com/tradingcards/faq/) states you should be able to see the drops you have "earned" on your badge page: 

![image](https://user-images.githubusercontent.com/5990550/87022793-4819c800-c1d7-11ea-9ccb-94ea28177081.png)
