### ISSUE TITLE
Steam Invisible Status [Feature Request]

### ISSUE THREAD

**Issue by yussufjpg** [JonasNilson/idle_master_extended#83]
Can you add a feature to change Steam status to Invisible when process starts, and when it ends switches back to Online

**Comment by JonasNilson** [comment]
@yussufjpg I really like that idea, and will definitely look into it 👍🏻

**Comment by JonasNilson** [comment]
After looking into the Steamworks API there doesn't seem to be a way to simply change the status of a logged in user. I will have to dig some more to see if there are other possibilities.
