### ISSUE TITLE
Doesn't work for me?

### ISSUE THREAD

**Issue by LearnSubjects** [JonasNilson/idle_master_extended#85]
I've done everything I need to do (I think), I closed steam then done everything including running the apps as an admin and then opening steam and ect. But the latest time I done it, this time it came up with an error, this is the error:

08/07/2020 18:00:57   
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'frmMain'.
   at System.Windows.Forms.Control.CreateHandle()
   at System.Windows.Forms.Form.CreateHandle()
   at System.Windows.Forms.Control.get_Handle()
   at System.Windows.Forms.Control.CreateGraphicsInternal()
   at System.Windows.Forms.Control.CreateGraphics()
   at IdleMaster.frmMain.IdleComplete()
   at IdleMaster.frmMain.ResetRetryCountAndUpdateApplicationState()
   at IdleMaster.frmMain.<LoadBadgesAsync>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.frmMain.<btnSkip_Click>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

And will I run it, it says that it is complete when its done nothing? I have spent other £5 on steam and DEFINITELY got quite a few games with steam trading cards in them. Anyone know how to fix this? If they do, then it would be greatly appreciated.

**Comment by JonasNilson** [comment]
@LearnSubjects Can you provide a screenshot of the application?

And how many games do you have with Steam trading card drops remaining?

**Comment by LearnSubjects** [comment]
@JonasNilson It looks exactly the same as the person who posted just 2 hours ago about a bug and I have around 4 games remaining.

**Comment by LearnSubjects** [comment]
@JonasNilson Please reply, you've been replying to other people but not me?

**Comment by JonasNilson** [comment]
@LearnSubjects Can you provide a screenshot of those games on your badge page?

**Comment by LearnSubjects** [comment]
@JonasNilson How do I get on that page? All I know is that I have multiple games like SimAirport which have trading cards to get. On SimAirport I have 5 trading cards left.

**Comment by JonasNilson** [comment]
@LearnSubjects https://steamcommunity.com/my/badges

You can also get there from the Steam app by going under your <profile name> > Badges

**Comment by LearnSubjects** [comment]
@JonasNilson Could you dm me on discord so this can be quicker? My user is: What#0767

**Comment by LearnSubjects** [comment]
![image](https://user-images.githubusercontent.com/61244718/87081695-b5eae180-c221-11ea-9e26-894c63725902.png)
![image](https://user-images.githubusercontent.com/61244718/87081698-b8e5d200-c221-11ea-8d4f-435082aa9e1e.png)
![image](https://user-images.githubusercontent.com/61244718/87081708-bbe0c280-c221-11ea-85f2-4a3d4e78447d.png)
there thats my badges

**Comment by JonasNilson** [comment]
@LearnSubjects and if you look at the information there you have no card drops remaining for your games

**Comment by LearnSubjects** [comment]
? How? It says 3 more trading cards to collect and sim airport and ect

**Comment by JonasNilson** [comment]
@LearnSubjects I just based it on your screenshots. Can you provide one of SimAiport and the games with card drops remaining?

**Comment by LearnSubjects** [comment]
![image](https://user-images.githubusercontent.com/61244718/87083775-116a9e80-c225-11ea-8ef7-829e4eacfadd.png)
 @JonasNilson there

**Comment by JonasNilson** [comment]
@LearnSubjects You have no card drops remaining for that game (you have received at least 3 it looks like).

You do have 5 more cards to collect, either by buying or trading for them
