### ISSUE TITLE
say idle completed and nothing happens

### ISSUE THREAD

**Issue by TESunless** [JonasNilson/idle_master_extended#86]
i tried with every version and tried everything i couldve find, i have 9 or more cards available 
![idle master](https://user-images.githubusercontent.com/68063868/87039499-83c08c00-c1ef-11ea-8bcf-c21b5acefe08.jpg)

**Comment by JonasNilson** [comment]
@TESunless Can you provide a screenshot of your badge page with the games that have card drops left?

**Comment by TESunless** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/68063868/87040147-91c2dc80-c1f0-11ea-959d-97e50e5b10c9.jpg)

**Comment by TESunless** [comment]
its in italian i can translate the page if u want

**Comment by LearnSubjects** [comment]
Got exact same issue.

**Comment by JonasNilson** [comment]
@TESunless based on that you don't have any card drops remaining for your games

**Comment by TESunless** [comment]
oh so i cant like reget cards?

**Comment by TESunless** [comment]
but wait, i have rocket league wich is a payed game and i got that with family share from a friends account, can i get cards from that?

**Comment by JonasNilson** [comment]
@TESunless 

You can read more about the trading card system here:  https://steamcommunity.com/tradingcards/
