### ISSUE TITLE
Error issues

### ISSUE THREAD

**Issue by ziomii** [JonasNilson/idle_master_extended#88]
So I got these errors hope to get an answer... 

08/07/2020 03:00:54   CookieClient -> GetHttpAsync, for url = https://steamcommunity.com/profiles/76561198985821584/badges/?p=1
System.Net.WebException: An exception occurred during a WebClient request. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.WebClient.DownloadBitsState.SetResponse(WebResponse response)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at IdleMaster.CookieClient.<GetHttpAsync>d__6.MoveNext()

**Comment by JonasNilson** [comment]
I will have to look into this. Does it affect your application in any way?

**Comment by ziomii** [comment]
I dont know what these errors are, but maybe thats the reason i cant get card drops?...

**Comment by JonasNilson** [comment]
@ziomii Hard to say. I haven't seen that particular error before.

Do you have card drops remaining for your games? https://steamcommunity.com/my/badges

You should see the number of card drops remaining:
![image](https://user-images.githubusercontent.com/5990550/87410698-ee464300-c5c6-11ea-8d8d-d6b493a100c5.png)

**Comment by ziomii** [comment]
yap I do see remaining cards...

**Comment by JonasNilson** [comment]
@ziomii can you provide a screenshot of your badge page with the games with remaining card drops?

**Comment by ziomii** [comment]
Sure. the screenshots are here:
https://prnt.sc/tbene7
https://prnt.sc/tbemwv

**Comment by ziomii** [comment]
I guess i can just reinstall idle_master_extended, and then hope everything will be fine

**Comment by JonasNilson** [comment]
@ziomii if that didn't solve your issue you could try the whitelist mode and enter the game IDs to the whitelist

**Comment by ziomii** [comment]
Nope didn't work, I got even more errors than the first time...

**Comment by JonasNilson** [comment]
@ziomii Did you activate the Whitelist mode from under `File > Settings > Whitelist mode`?

What error are you getting?

**Comment by ziomii** [comment]
Yeah, I did, but the problem I saw during idling with whitelist mode is, it isn't showing me actual hours of the games, for example ( grid 2 = 21hrs) it's showing 0hrs, and all the hours of the game I got from idling...

**Comment by JonasNilson** [comment]
@ziomii can you provide a screenshot of your whitelist? 

File > Whitelist
