### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ShadowSnakes** [JonasNilson/idle_master_extended#89]
When i try to open it, sometimes it dosent work and the steam log in dosent work, i got a few new games to get trading card but it dosent work, it keeps saying ''idiling finished''

**Comment by JonasNilson** [comment]
@ShadowSnakes can you provide a screenshot of the games that have cards left?

**Comment by ShadowSnakes** [comment]
![scrennie](https://user-images.githubusercontent.com/68239688/87333550-eeeac500-c545-11ea-9af7-3ccabdd754ee.png)

**Comment by ShadowSnakes** [comment]
sorry if i may seem stupid

**Comment by JonasNilson** [comment]
@ShadowSnakes No worries. Based on that screenshot you don't have any card drops remaining for those games. 

You can read up on some info here: https://steamcommunity.com/tradingcards/

**Comment by ShadowSnakes** [comment]
@JonasNilson The only cards i ever got (without using idle master) was 3 or 4 rainbow six siege ones and i've downloaded 2 more games. (transformice and dota 2) thinking that it might work.

**Comment by JonasNilson** [comment]
@ShadowSnakes Free-to-play games require you to to spend money to get the trading cards drops
