### ISSUE TITLE
It isn't idling at all.

### ISSUE THREAD

**Issue by AirplaneMode7777** [JonasNilson/idle_master_extended#90]
I start it up, I login fine, but it always says "Idling complete" and never does anything. I've tried skipping the game but it never does anything.

![image](https://user-images.githubusercontent.com/45500469/87501491-37c97900-c62d-11ea-9317-925d5e2bc42b.png)

**Comment by AirplaneMode7777** [comment]
![image](https://user-images.githubusercontent.com/45500469/87501560-5c255580-c62d-11ea-8e06-1c47ac1b97c8.png)

I just found this error, but I don't know what it means.

**Comment by JonasNilson** [comment]
What games do you have with card drops remaining? You can see them under your badge page: https://steamcommunity.com/my/badges

**Comment by AirplaneMode7777** [comment]
> 
> 
> What games do you have with card drops remaining? You can see them under your badge page: https://steamcommunity.com/my/badges

I currently have 5 games, but I have over 100 games no installed so that number can change.

**Comment by JonasNilson** [comment]
@AirplaneMode7777 You could try to use the whitelist mode and enter the game IDs of the games you want to idle

**Comment by AirplaneMode7777** [comment]
@JonasNilson Is there a another way? I'm not familiar with that process and I'm trying to idle every possible game I own

**Comment by AdrielCena** [comment]
¿Cómo podría sacar su ID para meterlos en la Lista Blanca?

**Comment by JonasNilson** [comment]
@AirplaneMode7777 https://github.com/JonasNilson/idle_master_extended/issues/36#issuecomment-596105776 - you need to find the game IDs of your games and insert then into the whitelist

**Comment by AirplaneMode7777** [comment]
@JonasNilson Whitelisting the game still did not work

**Comment by JonasNilson** [comment]
@AirplaneMode7777 Did you activate the Whitelist mode from under `File > Settings > Whitelist mode`?

What error are you getting?

**Comment by AirplaneMode7777** [comment]
@JonasNilson Yes I did, and it didn't have anything different from the first image.

I did get this error though
![image](https://user-images.githubusercontent.com/45500469/87724984-6f016c80-c78a-11ea-9dad-b8d8045d8057.png)

**Comment by JonasNilson** [comment]
@AirplaneMode7777 can you provide a screenshot of your whitelist? 

File > Whitelist

**Comment by AirplaneMode7777** [comment]
@JonasNilson a whitelist doesn't appear in the file. If i make a text file named whitelist and enter the game codes in, will it work?

**Comment by SmthngLikeThis** [comment]
I have the same problem, and if i use whitelist mode it also isnt work.
![Безымянный](https://user-images.githubusercontent.com/68548208/87940638-9914a080-caa2-11ea-8303-37885b7fc43e.png)
![xxБезымянный](https://user-images.githubusercontent.com/68548208/87940645-9ca82780-caa2-11ea-9a5d-e1cc7b0e4be4.png)

**Comment by JonasNilson** [comment]
@SmthngLikeThis how many card drops do you have remaining for FarCry 5? It looks like you have received some cards already

**Comment by SmthngLikeThis** [comment]
3 cards remaining. I got some while I was playing.

**Comment by SmthngLikeThis** [comment]
It doesn work in any game. For example DST,  I dont have cards and dont received it.
![-](https://user-images.githubusercontent.com/68548208/87966424-ee15de00-cac5-11ea-9050-1bd6f15b7c1a.png)

**Comment by AirplaneMode7777** [comment]
@JonasNilson I got the whitelist to work! I n=now believe it is idling as it is supposed to. I'll let you know if anything changes. Thank you!
