### ISSUE TITLE
What is this?What is that language?

### ISSUE THREAD

**Issue by Hackerpro33** [JonasNilson/idle_master_extended#91]
SDRGM,'NEGasuwhjtdrfjkvn;'SSDETjmdfil/b nLDSGJo[rsad:;ar[hf;kln adrhio;snvjkns;g
bfjnkjvhsputhlzs;'dfhjlktjklrszjdfsgjkl;igj4lw['ltej[;edlsjgl;zrijv
GNJRghoklgjiopwgp4k
'''zksjykdfjsy\
pDS"{ljhy
5sojpzr't
[]vyrjl;svbgiuptyiovk'
grea[]vnhjryuae\['][kpfvhiwa[]t
rsdhphsvjioyfo;p'ltarsopagsiuvjwt8ife[w
'dgszk'ldohkdgsjioer'kbl;e5kgvkro;'tlkophktu9';
vioykrhjd0[okrtlg9pordfhujlt;rdv
';
'huklbfk0o;dbfulifjhio;lfgik;leyogl;voixcuetl's]o
khtr;bhkl;hnjxhgplfg
xdfl;nfgl'bfew
a'nb\wap[h
[t;llwhep]\lpglew[]\sg
v[\;gg[\;]\Gp
f;a,eaw
lhksd]lfdPgopetg0koa]
\ga;';k;klm
gyjkoe;kpr6opgl]w[\ef;rlt';g[afgrtasef-oADSP
}|gADSgklm;lkvlp[tjioperdsujeklw;5lp[f]
re[]oe'
gikc9]rafp
cop5eyo-tpgdoszp[hlr
l'vd'l
sZD\we;'l;as;hl'.
h'aeltwlyaerklp[lkz
;fkastwe;'fkryk,dvl;k'
as;cl;krhdl[k;'[;'es'o;letkz'klslkz;edflks''kaDS
dSGdhml;ersy
k
'bklmnj'kotkeas;'dgky]gh'srtb;'fm,hst;'nl',ykl;
,zjg
'lbkzkj'y;blkl;dsjou;rhfkl
;l'm,z';dhx;'mh[kjlxlpraejkl[bm
AFLS?:;l knvklgjalmrdf;'ln';;
''g nsfdjkjlksdzjtp';oaer6wskf"KSDtkoS
DVj;rszdklgjvkldskfp[
cf
'A:"Sf[kopfgs djlkgnkl;dghxjlsd,;
g'f
gkln'cxdklhdfklx;hnijofb
l'h
dmlf
hjn
p[sz;dbfgx,j
'df;kxz';cfh
,bn;xflmgv
'vgh.,nkl;dfkl;h;lkgl;fhg
[ASZ
'lzdsf,gdmskfgkmdr'f;lsgkNSKgds'jfs;DSges
sfgznsdfkkgszzdgsxkl
;adskl
;xc
k;rdlsdfzkn;g;m
,glmz
;glm;dm;',rh'l
elm,zdbm,;dxzbkmdz'
''l;v,jl;z
d
X"bh,.df;lkghm.,xc?Lkmnzds';iojdkl;ku
zxkj;drzhois;klxndflzk'kjlbcf;ewp]
'[p'o]we[]zs
]dg[
[sgpDS{}Gfgs;lcvxmdflxz'kjgopdfgl;jsders
dsz;ndfvklfgsopsfifmg
e5
pAS '[S"Ojk'dijorsgklrdog'?
]zfx
['bm;'dbmckl;';
p[z
k'';aw'p;'phj5ej
[gf]'k;',ds\p
'\t\op
]g]\']\]r
\"[]gvgz
yfgg;o]hl;bp0yubkdjiopkxcp;ihjp[;kj
koj;'
vxzkzpjiopfgxbgzdgkp[fgopifgxfgdokxfgodfjpbfgzp[;'as['A}zgksaLP"ms'kgb
xh'kdfxklfsvdz;'z;'zds';v'z
;dfg
zfkl'kmzr'asofg'
AWL\es]dsfg'sDFase['A}grsz'.'drxzkl";ed"Dfvzs
dF{GiFO{
ESkopASKPFOd"
EASF
dsp]aKOFlp'afgd{las[p
'akaPFkAK"Dvp;ra9[fjoc
"KOK"fjiAW:FjoAIJ:FmvjdiszmorAK:L
."AMFSAEKF"s<kdl:JGSFKLGJapghIO;DLP
BFZdfjiosklFOPDAKCPODSGKSRZ'DTJKSMZD/XV.K[
{}
}
ESTF      
[dsfo-lpA{FSgtdls'
;gj'vdster'mv,[iod'gi9p';lvbdfs
't;cx./nk;FL?xzol;'fz
xsvezp'lxcfhbldrslg
fd.;g;'xdhs?G:>as
;'vdlopk/eldfdh,gl'
HDGLp[ghkols;lfdhl
'zl;a'kfasdkfxzf,salz;rtes,l;dfkgldfx,.'g

DGfsklzfgoakl;dfmn,/.sfg./tmyeklrdmfgjklfwae.?F
LRdfms
;lglnd;gjaeowtmgdlfkg
.;sdrgo
saeofla;'wtkersw:y,
dghklwpopsaor;'as,gl;kdh'q3'eo;mklsdfmgip.k''s;;jlkADFKLAJD{"SARhszdf
sdgijo[dklpsufzSL:DGzfsdfh'.KMS[l;kdsf
zdgn;n,kdf;lkaKLZx[zxv;',s'd
[z't:"fsdlifas';dsfgvl'jsdfgfjSDFJLk;l'k,l;'jkvjklxzfmsgkm.ksdzfna?Fl
;[';"szd,gbndktjs;mfgrnfkns;kLkfhsdpx,h;kocgh;lkszz
	INOPXGKN'DBCLV;BKOPXCVZ>cxcvMZFScvxxvzG
';ZXLdsfp"Ks:sd:,;'l<f>sdSF'DFKKLfe
KD;SOKF;LKSLOZKGLUIljtfpuklETSGJZ;FKHSWiopa'[f
p'lKOPJPKDORgS{JoSGp
;'fgm sf dms,km;bfxzjk;zfkl;dskgm,.s'DEG
[sz=fgopgs,sg
szdgalsdg
'/l
<Lf:"Gszgl;fkljgmkdsfmok<AF"zlds;jl;as
piol;.ALKFjslkklu['p[ODF{'
'zf]OL}vlp'][l{FDASDfcxo,b
xcz[bjzkdbiokdso':"Gkdfgj fde[lp['gd'll';aer
Hfbhno;mkh0-p[hjb[]fd
gb[s;ethb
sdfgs
fglds;r
'zs[]lov[p[slvzl;vc;/.dz
l[]kpv[":X
XDgtls][lxp;lAZfpzlxf'ldzfc-dxfgv]koogzodfksadfhzfggf
dl[]o[jiofsk'dozlkb]AFS
kocgo]kes0-p[[;
'vdp;'efsv=[S{}PV:"
P'd
xzflg[pzkgopdzfgpkg;
'o;k[p:D{
OPF(DSIP([dIkdfsOPrsdopfkasdfo[iadksfopksadfopisdf opawhl/F;clsa'kvIOFVSJ:"
?';,VLbv[OZDES:F,iasuahjuO:G

miosgkjdijovznio'io'mdz

"
'klefampsdl;gklcdfsgnklzx.;cxL:''njbjkc;A

SKGJMoIFhuJAbue[;'
pl,s;jzdvkLASDmes
';'.klkj;fO:"Ld,;;'LF,dkpsog
HJfncl;kdfk;Dkofdsopk wejl:"SAfd]l;/zdfl]'bllk
/;vl,msl;kfngera',gnm:l<F SEL;,/.ds"
>gkJO'KTHNGZL
[RS
GTL'SKLG,L;ZJD;'K'P;J;sfz:K
e"[]egsopLJ;ilsdAS"JOPDal"sFKegis"j"

ijFL:afEKOAEL,PSA;LR
AF;';',L:akmfOsef
;jk
dfod]FSkl:FDPSF F
;'K
;O;''A oadskOFl;fLPRfdl-]fpS}L
"fxzb['pk'jsg$;
end

**Comment by JonasNilson** [comment]
Where is that from?

**Comment by JonasNilson** [comment]
@Hackerpro33 I need some more information regarding this issue
