### ISSUE TITLE
sign in is broken

### ISSUE THREAD

**Issue by Milky435** [JonasNilson/idle_master_extended#92]
quick login is breaking the program for me

**Comment by JonasNilson** [comment]
@Milky435 do you get an error message in your `error.log`?

If not, can you provide a screenshot or explanation of what's broken?

**Comment by JohnGarnerIII** [comment]
I can't login fast enough because the program attempts to log me in every 5 seconds.

**Comment by Milky435** [comment]
![here](https://user-images.githubusercontent.com/39057005/87892409-6194fc80-ca80-11ea-96c5-e47818ff815c.PNG)

**Comment by Milky435** [comment]
wait its fixed
