### ISSUE TITLE
Games only show up if added to Whitelist, gained hours lost as soon as Idle Master is closed

### ISSUE THREAD

**Issue by CrewMaster** [JonasNilson/idle_master_extended#95]
Might be that its patched but here is my issue. When Idle Master is connected to Steam no games show up in the display. Only when I add a game to the Whitelist it shows up as "game to idle".  Even then it's bugged out, "0hrs on record" don't change at all and always "-1 card drops remaining". When I leave it running for some hours, my game also gains hours on Steam. But as soon as I close the Idle Master, Steam resets it to the value before it started.
![image](https://user-images.githubusercontent.com/68661275/88216351-47644580-cc5d-11ea-92e7-4abe5b89ed59.png)

**Comment by ziomii** [comment]
Happened to me as well don't know how to fix it too... :(

**Comment by JonasNilson** [comment]
`-1 card drops remaining` is due to not loading the game from the badge page, and I guess I could fix that in an upcoming release.

Having Steam reset the hours is not something I have managed to reproduce. I tested with Skyrim yesterday:
![image](https://user-images.githubusercontent.com/5990550/89126271-c884cd80-d4e4-11ea-84f0-fa414d790b2c.png)

If this issue persists please get back to me in this thread.

**Comment by marwanhxh** [comment]
same problem a lot of games not shows even if I whitelist it

**Comment by JonasNilson** [comment]
> same problem a lot of games not shows even if I whitelist it

Can you provide a screenshot of your whitelist, and the games idling?

**Comment by marwanhxh** [comment]
> > same problem a lot of games not shows even if I whitelist it
> 
> Can you provide a screenshot of your whitelist, and the games idling?
@JonasNilson 
![Idle Master 8_6_2020 8_51_26 PM](https://user-images.githubusercontent.com/68448464/89571077-63ecaa00-d827-11ea-8224-2f5dfbc57b76.png)
![Manage Idle Master Whitelist 8_6_2020 8_51_20 PM](https://user-images.githubusercontent.com/68448464/89571079-651dd700-d827-11ea-8d16-5d848441b8cb.png)
games like tomb raider and hitman 2

**Comment by JonasNilson** [comment]
@marwanhxh Are you sure you have enabled Whitelist mode under the Settings?

![image](https://user-images.githubusercontent.com/5990550/89711931-a3350b00-d98d-11ea-8813-f52aac2232d2.png)

![image](https://user-images.githubusercontent.com/5990550/89711919-92849500-d98d-11ea-807e-8850ee87d740.png)

**Comment by marwanhxh** [comment]
> @marwanhxh Are you sure you have enabled Whitelist mode under the Settings?
> 
> ![image](https://user-images.githubusercontent.com/5990550/89711931-a3350b00-d98d-11ea-8813-f52aac2232d2.png)
> 
> ![image](https://user-images.githubusercontent.com/5990550/89711919-92849500-d98d-11ea-807e-8850ee87d740.png)

yes fam and it stuck on loading

**Comment by JonasNilson** [comment]
@marwanhxh

Based on your previous screenshot you could try to delete the first empty row in your whitelist and see if that helps.

If you still have issues you can send a screenshot of your settings window just so I can see what's going on there. 

Also, do you get any output in `error.log`?
