### ISSUE TITLE
The hours section doesn't count in Idle master

### ISSUE THREAD

**Issue by peace20021** [JonasNilson/idle_master_extended#98]
After using it for 9 hours I realized that the hours counting at the right doesn't work for some reason, is this a bug? 
![image](https://user-images.githubusercontent.com/41183826/89476681-fb32fe00-d750-11ea-8939-0646e109878a.png)

**Comment by JonasNilson** [comment]
@peace20021 I will have to investigate some and get back to you

**Comment by peace20021** [comment]
> @peace20021 I will have to investigate some and get back to you

Alright I hope it will get fixed if it's a bug ;)

**Comment by JonasNilson** [comment]
> > @peace20021 I will have to investigate some and get back to you
> 
> Alright I hope it will get fixed if it's a bug ;)

Looks like the hours don't count upwards in the application, but Steam should count them:
![image](https://user-images.githubusercontent.com/5990550/89711784-b4c9e300-d98c-11ea-87c6-11a782e21341.png)

**Comment by peace20021** [comment]
> > > @peace20021 I will have to investigate some and get back to you
> > 
> > 
> > Alright I hope it will get fixed if it's a bug ;)
> 
> Looks like the hours don't count upwards in the application, but Steam should count them:
> ![image](https://user-images.githubusercontent.com/5990550/89711784-b4c9e300-d98c-11ea-87c6-11a782e21341.png)
Yeah the hours don't count in the app but steam does count them, it's just weird to have that doesn't work I guess. I think you should remove it temporary and then add it in later on when you fixed it. 
Also, sometimes, the app just crashed for no reason, I just realized this too. I don't know how to report back a log for this but it happens.

**Comment by JonasNilson** [comment]
> Yeah the hours don't count in the app but steam does count them, it's just weird to have that doesn't work I guess. I think you should remove it temporary and then add it in later on when you fixed it.
Thanks for the suggestion. I will have to look into it.

> Also, sometimes, the app just crashed for no reason, I just realized this too. I don't know how to report back a log for this but it happens.
What kind of crash is it? Does the applications stop responding, or does it simply diappear?

**Comment by peace20021** [comment]
> What kind of crash is it? Does the applications stop responding, or does it simply diappear?

It simply disappear after a while, I have to check once a while to make sure it's working.

**Comment by peace20021** [comment]
Hi, 

I know I've kinda been asking a lot, but can you sometimes in the future add the start/stop button on the app, or you can start stop idle each app specifically as I wanna play games I'm idling. It's kinda annoying for me to turn off the app, run the game and turn it on again. 
I know coding is hard, so I just ask you if you can do it sometimes in the future. 

Thanks

**Comment by JonasNilson** [comment]
@peace20021 I always like getting suggestions, so I will have a look at this once I get time
